import { ActivityMap } from '../../types';

// Default activities for all 12 months — extracted from v1
// Keyed by "M-D" (e.g. "3-1" for March 1)

export const universalActivities: ActivityMap = {
  // ── December ──────────────────────────────────────────────
  '12-1':  { word: 'tree',      subject: 'a Christmas tree',          instruction: 'Color the Christmas tree!',                        colorWord: 'green',  tags: [] },
  '12-2':  { word: 'star',      subject: 'a star',                    instruction: 'Color the stars yellow and the ornaments red!',    colorWord: 'yellow', tags: [] },
  '12-3':  { word: 'angel',     subject: 'an angel',                  instruction: 'Color the angel!',                                 colorWord: 'white',  tags: [] },
  '12-4':  { word: 'candle',    subject: 'a candle',                  instruction: 'Color the candle yellow and the holder red!',      colorWord: 'yellow', tags: [] },
  '12-5':  { word: 'bell',      subject: 'a bell',                    instruction: 'Color the bell gold!',                             colorWord: 'gold',   tags: [] },
  '12-6':  { word: 'wreath',    subject: 'a wreath',                  instruction: 'Color the wreath green and the bow red!',          colorWord: 'green',  tags: [] },
  '12-7':  { word: 'stocking',  subject: 'a stocking',                instruction: 'Color the stocking!',                              colorWord: 'red',    tags: [] },
  '12-8':  { word: 'snow',      subject: 'a snowflake',               instruction: 'Color the snowflake blue!',                        colorWord: 'blue',   tags: [] },
  '12-9':  { word: 'snowman',   subject: 'a snowman',                 instruction: 'Color the snowman!',                               colorWord: 'white',  tags: [] },
  '12-10': { word: 'star',      subject: 'a starry sky',              instruction: 'Color the stars yellow and the sky blue!',         colorWord: 'yellow', tags: [] },
  '12-11': { word: 'ginger',    subject: 'a gingerbread house',       instruction: 'Color the gingerbread house!',                     colorWord: 'brown',  tags: [] },
  '12-12': { word: 'reindeer',  subject: 'a reindeer',                instruction: 'Color the reindeer brown and the nose red!',       colorWord: 'brown',  tags: [] },
  '12-13': { word: 'manger',    subject: 'the manger scene',          instruction: 'Color the manger scene!',                         colorWord: 'gold',   tags: [] },
  '12-14': { word: 'gift',      subject: 'a gift',                    instruction: 'Color the gifts any colors you like!',             colorWord: 'red',    tags: [] },
  '12-15': { word: 'candy',     subject: 'a candy cane',              instruction: 'Color the candy cane red and white!',              colorWord: 'red',    tags: [] },
  '12-16': { word: 'dove',      subject: 'a dove',                    instruction: 'Color the dove white!',                            colorWord: 'white',  tags: [] },
  '12-17': { word: 'sheep',     subject: 'a shepherd and sheep',      instruction: 'Color the shepherd and his sheep!',                colorWord: 'white',  tags: [] },
  '12-18': { word: 'cookie',    subject: 'Christmas cookies',         instruction: 'Color the Christmas cookies!',                     colorWord: 'pink',   tags: [] },
  '12-19': { word: 'Bethlehem', subject: 'the star of Bethlehem',     instruction: 'Color the star of Bethlehem yellow!',              colorWord: 'yellow', tags: [] },
  '12-20': { word: 'sleigh',    subject: 'a sleigh',                  instruction: 'Color the sleigh red and the snow white!',         colorWord: 'red',    tags: [] },
  '12-21': { word: 'wisemen',   subject: 'the three wise men',        instruction: 'Color the three wise men!',                        colorWord: 'gold',   tags: [] },
  '12-22': { word: 'holly',     subject: 'holly berries',             instruction: 'Color the holly berries red and the leaves green!', colorWord: 'red',   tags: [] },
  '12-23': { word: 'Jesus',     subject: 'baby Jesus',                instruction: 'Color the baby Jesus in the manger!',              colorWord: 'gold',   tags: [] },
  '12-24': { word: 'sky',       subject: 'a Christmas Eve sky',       instruction: 'Color the Christmas Eve sky with stars!',          colorWord: 'blue',   tags: [] },
  '12-25': { word: 'nativity',  subject: 'the nativity',              instruction: 'Color the nativity \u2014 use your favorite colors!',   colorWord: 'gold',   tags: [] },
  '12-26': { word: 'bird',      subject: 'a winter bird',             instruction: 'Color the winter birds!',                          colorWord: 'red',    tags: [] },
  '12-27': { word: 'village',   subject: 'a snowy village',           instruction: 'Color the snowy village!',                         colorWord: 'white',  tags: [] },
  '12-28': { word: 'fireworks', subject: 'fireworks',                 instruction: 'Color the fireworks any colors you like!',         colorWord: 'yellow', tags: [] },
  '12-29': { word: 'noel',      subject: 'a Christmas scene',         instruction: 'Color the Christmas story \u2014 any colors you like!', colorWord: 'red',    tags: [] },
  '12-30': { word: 'joy',       subject: "a New Year's scene",        instruction: "Color the New Year's Eve celebration!",            colorWord: 'gold',   tags: [] },
  '12-31': { word: 'peace',     subject: 'a peace dove',              instruction: 'Color the peace dove white!',                      colorWord: 'white',  tags: [] },

  // ── January ───────────────────────────────────────────────
  '1-1':  { word: 'year',      subject: 'a new year banner',         instruction: 'Color the New Year banner!',                        colorWord: 'gold',   tags: [] },
  '1-2':  { word: 'snow',      subject: 'a snowflake',               instruction: 'Color the snowflake blue!',                         colorWord: 'blue',   tags: [] },
  '1-3':  { word: 'penguin',   subject: 'a penguin',                 instruction: 'Color the penguin black and white!',                colorWord: 'black',  tags: [] },
  '1-4':  { word: 'mittens',   subject: 'mittens',                   instruction: 'Color the mittens red!',                            colorWord: 'red',    tags: [] },
  '1-5':  { word: 'scarf',     subject: 'a scarf',                   instruction: 'Color the scarf any colors you like!',              colorWord: 'purple', tags: [] },
  '1-6':  { word: 'hat',       subject: 'a winter hat',              instruction: 'Color the hat blue and the pompom white!',          colorWord: 'blue',   tags: [] },
  '1-7':  { word: 'sled',      subject: 'a sled',                    instruction: 'Color the sled red!',                               colorWord: 'red',    tags: [] },
  '1-8':  { word: 'snowball',  subject: 'a snowball fight',          instruction: 'Color the snow white and the coats colorful!',      colorWord: 'white',  tags: [] },
  '1-9':  { word: 'igloo',     subject: 'an igloo',                  instruction: 'Color the igloo white and the sky blue!',           colorWord: 'white',  tags: [] },
  '1-10': { word: 'polar',     subject: 'a polar bear',              instruction: 'Color the polar bear white!',                       colorWord: 'white',  tags: [] },
  '1-11': { word: 'bird',      subject: 'a winter bird',             instruction: 'Color the winter bird red!',                        colorWord: 'red',    tags: [] },
  '1-12': { word: 'frost',     subject: 'a frosty window',           instruction: 'Color the frost patterns blue and white!',          colorWord: 'blue',   tags: [] },
  '1-13': { word: 'cocoa',     subject: 'a mug of hot cocoa',        instruction: 'Color the cocoa mug red and the cocoa brown!',      colorWord: 'brown',  tags: [] },
  '1-14': { word: 'ice',       subject: 'an ice skater',             instruction: 'Color the ice skater any colors you like!',         colorWord: 'blue',   tags: [] },
  '1-15': { word: 'owl',       subject: 'a snowy owl',               instruction: 'Color the snowy owl white!',                        colorWord: 'white',  tags: [] },
  '1-16': { word: 'cloud',     subject: 'snow clouds',               instruction: 'Color the clouds grey and the snow white!',         colorWord: 'grey',   tags: [] },
  '1-17': { word: 'deer',      subject: 'a deer in the snow',        instruction: 'Color the deer brown and the snow white!',          colorWord: 'brown',  tags: [] },
  '1-18': { word: 'pine',      subject: 'a pine tree',               instruction: 'Color the pine tree green!',                        colorWord: 'green',  tags: [] },
  '1-19': { word: 'wolf',      subject: 'a wolf howling',            instruction: 'Color the wolf grey and the moon yellow!',          colorWord: 'grey',   tags: [] },
  '1-20': { word: 'star',      subject: 'stars in the winter sky',   instruction: 'Color the winter stars yellow!',                    colorWord: 'yellow', tags: [] },
  '1-21': { word: 'rabbit',    subject: 'a snow rabbit',             instruction: 'Color the snow rabbit white!',                      colorWord: 'white',  tags: [] },
  '1-22': { word: 'boot',      subject: 'snow boots',                instruction: 'Color the boots any colors you like!',              colorWord: 'red',    tags: [] },
  '1-23': { word: 'fox',       subject: 'an arctic fox',             instruction: 'Color the fox white and the nose black!',           colorWord: 'white',  tags: [] },
  '1-24': { word: 'moon',      subject: 'a winter moon',             instruction: 'Color the moon yellow and the sky dark blue!',      colorWord: 'yellow', tags: [] },
  '1-25': { word: 'crystal',   subject: 'ice crystals',              instruction: 'Color the ice crystals light blue!',                colorWord: 'blue',   tags: [] },
  '1-26': { word: 'sleep',     subject: 'a sleeping bear',           instruction: 'Color the bear brown and the cave dark!',           colorWord: 'brown',  tags: [] },
  '1-27': { word: 'flake',     subject: 'snowflakes',                instruction: 'Color the snowflakes blue and white!',              colorWord: 'blue',   tags: [] },
  '1-28': { word: 'cabin',     subject: 'a cozy cabin',              instruction: 'Color the cabin brown and the smoke grey!',         colorWord: 'brown',  tags: [] },
  '1-29': { word: 'robin',     subject: 'a robin',                   instruction: "Color the robin's chest red!",                      colorWord: 'red',    tags: [] },
  '1-30': { word: 'seed',      subject: 'seeds in the ground',       instruction: 'Color the seeds brown and the soil dark!',          colorWord: 'brown',  tags: [] },
  '1-31': { word: 'hope',      subject: 'a sunrise',                 instruction: 'Color the January sunrise pink and gold!',          colorWord: 'gold',   tags: [] },

  // ── February ──────────────────────────────────────────────
  '2-1':  { word: 'heart',     subject: 'a big red heart',           instruction: 'Color the big red heart!',                         colorWord: 'red',    tags: [] },
  '2-2':  { word: 'hearts',    subject: 'hearts',                    instruction: 'Color the hearts red and pink!',                   colorWord: 'pink',   tags: [] },
  '2-3':  { word: 'rose',      subject: 'roses',                     instruction: 'Color the roses red!',                             colorWord: 'red',    tags: [] },
  '2-4':  { word: 'card',      subject: 'a Valentine card',          instruction: 'Color the Valentine card any colors you like!',    colorWord: 'pink',   tags: [] },
  '2-5':  { word: 'wreath',    subject: 'a heart wreath',            instruction: 'Color the heart wreath red and pink!',             colorWord: 'red',    tags: [] },
  '2-6':  { word: 'bear',      subject: 'a teddy bear',              instruction: 'Color the teddy bear holding a heart!',            colorWord: 'brown',  tags: [] },
  '2-7':  { word: 'mailbox',   subject: 'a mailbox',                 instruction: 'Color the mailbox red with hearts!',               colorWord: 'red',    tags: [] },
  '2-8':  { word: 'flower',    subject: 'pink flowers',              instruction: 'Color the pink flowers!',                          colorWord: 'pink',   tags: [] },
  '2-9':  { word: 'bracelet',  subject: 'friendship bracelets',      instruction: 'Color the friendship bracelets!',                  colorWord: 'purple', tags: [] },
  '2-10': { word: 'balloon',   subject: 'heart balloons',            instruction: 'Color the heart balloons red and pink!',           colorWord: 'red',    tags: [] },
  '2-11': { word: 'cupcake',   subject: 'a cupcake',                 instruction: 'Color the cupcake with a heart on top!',           colorWord: 'pink',   tags: [] },
  '2-12': { word: 'bird',      subject: 'birds sharing a heart',     instruction: 'Color the birds sharing a heart!',                 colorWord: 'red',    tags: [] },
  '2-13': { word: 'tree',      subject: 'a Valentine tree',          instruction: 'Color the Valentine tree with hearts!',            colorWord: 'pink',   tags: [] },
  '2-14': { word: 'love',      subject: 'a big Valentine heart',     instruction: 'Color the big Valentine heart any colors you like!', colorWord: 'red', tags: [] },
  '2-15': { word: 'rainbow',   subject: 'a rainbow with hearts',     instruction: 'Color the rainbow with hearts!',                   colorWord: 'purple', tags: [] },
  '2-16': { word: 'crown',     subject: 'a crown',                   instruction: 'Color the hearts purple and gold!',                colorWord: 'purple', tags: [] },
  '2-17': { word: 'letter',    subject: 'a love letter',             instruction: 'Color the love letter with hearts!',               colorWord: 'red',    tags: [] },
  '2-18': { word: 'garden',    subject: 'a heart garden',            instruction: 'Color the heart garden!',                          colorWord: 'pink',   tags: [] },
  '2-19': { word: 'kindness',  subject: 'a kindness tree',           instruction: 'Color the kindness tree!',                         colorWord: 'green',  tags: [] },
  '2-20': { word: 'friend',    subject: 'flowers for a friend',      instruction: 'Color the flowers for a friend!',                  colorWord: 'pink',   tags: [] },
  '2-21': { word: 'butterfly', subject: 'butterflies',               instruction: 'Color the butterflies pink and yellow!',           colorWord: 'pink',   tags: [] },
  '2-22': { word: 'lovebird',  subject: 'love birds',                instruction: 'Color the love birds!',                            colorWord: 'red',    tags: [] },
  '2-23': { word: 'mobile',    subject: 'a heart mobile',            instruction: 'Color the heart mobile any colors you like!',      colorWord: 'purple', tags: [] },
  '2-24': { word: 'cookie',    subject: 'Valentine cookies',         instruction: 'Color the Valentine cookies!',                     colorWord: 'pink',   tags: [] },
  '2-25': { word: 'family',    subject: 'a family portrait',         instruction: 'Color the family portrait with hearts!',           colorWord: 'red',    tags: [] },
  '2-26': { word: 'kite',      subject: 'a heart kite',              instruction: 'Color the heart kite!',                            colorWord: 'red',    tags: [] },
  '2-27': { word: 'castle',    subject: 'a pink castle',             instruction: 'Color the pink castle!',                           colorWord: 'pink',   tags: [] },
  '2-28': { word: 'island',    subject: 'a heart-shaped island',     instruction: 'Color the heart-shaped island!',                   colorWord: 'blue',   tags: [] },

  // ── March ─────────────────────────────────────────────────
  '3-1':  { word: 'flower',    subject: 'a flower garden',           instruction: 'Color the flower garden!',                         colorWord: 'pink',   tags: [] },
  '3-2':  { word: 'tulip',     subject: 'tulips',                    instruction: 'Color the tulips red and the leaves green!',       colorWord: 'red',    tags: [] },
  '3-3':  { word: 'butterfly', subject: 'a butterfly',               instruction: 'Color the butterfly!',                             colorWord: 'orange', tags: [] },
  '3-4':  { word: 'rainbow',   subject: 'a rainbow',                 instruction: 'Color the rainbow any colors you like!',           colorWord: 'purple', tags: [] },
  '3-5':  { word: 'turtle',    subject: 'a sea turtle',              instruction: 'Color the sea turtle green!',                      colorWord: 'green',  tags: [] },
  '3-6':  { word: 'bird',      subject: 'spring birds',              instruction: 'Color the spring birds!',                          colorWord: 'yellow', tags: [] },
  '3-7':  { word: 'beach',     subject: 'a beach scene',             instruction: 'Color the beach scene!',                           colorWord: 'blue',   tags: [] },
  '3-8':  { word: 'petal',     subject: 'flowers',                   instruction: 'Color the flowers pink and yellow!',               colorWord: 'pink',   tags: [] },
  '3-9':  { word: 'caterpillar', subject: 'a caterpillar',           instruction: 'Color the caterpillar!',                           colorWord: 'green',  tags: [] },
  '3-10': { word: 'wave',      subject: 'ocean waves',               instruction: 'Color the ocean waves blue!',                      colorWord: 'blue',   tags: [] },
  '3-11': { word: 'chick',     subject: 'baby chicks',               instruction: 'Color the baby chicks yellow!',                    colorWord: 'yellow', tags: [] },
  '3-12': { word: 'kite',      subject: 'a kite',                    instruction: 'Color the kite any colors you like!',              colorWord: 'red',    tags: [] },
  '3-13': { word: 'Holi',      subject: 'Holi colors',               instruction: 'Color the Holi colors!',                           colorWord: 'purple', tags: [] },
  '3-14': { word: 'nest',      subject: 'a bird nest with eggs',     instruction: 'Color the nest brown and the eggs blue!',          colorWord: 'brown',  tags: [] },
  '3-15': { word: 'blossom',   subject: 'a spring tree',             instruction: 'Color the spring tree with pink blossoms!',        colorWord: 'pink',   tags: [] },
  '3-16': { word: 'fish',      subject: 'fish in the sea',           instruction: 'Color the fish in the sea!',                       colorWord: 'orange', tags: [] },
  '3-17': { word: 'shamrock',  subject: 'a shamrock',                instruction: 'Color the shamrock green!',                        colorWord: 'green',  tags: [] },
  '3-18': { word: 'bunny',     subject: 'a bunny',                   instruction: 'Color the bunny white and pink!',                  colorWord: 'pink',   tags: [] },
  '3-19': { word: 'sand',      subject: 'waves and sand',            instruction: 'Color the wave blue and the sand yellow!',         colorWord: 'blue',   tags: [] },
  '3-20': { word: 'tulip',     subject: 'tulips',                    instruction: 'Color the tulips red and yellow!',                 colorWord: 'red',    tags: [] },
  '3-21': { word: 'hula',      subject: 'a hula dancer',             instruction: 'Color the hula dancer!',                           colorWord: 'purple', tags: [] },
  '3-22': { word: 'sunset',    subject: 'a Hawaiian sunset',         instruction: 'Color the Hawaiian sunset!',                       colorWord: 'orange', tags: [] },
  '3-23': { word: 'plumeria',  subject: 'plumeria flowers',          instruction: 'Color the plumeria flowers!',                      colorWord: 'pink',   tags: [] },
  '3-24': { word: 'picnic',    subject: 'a spring picnic',           instruction: 'Color the spring picnic scene!',                   colorWord: 'green',  tags: [] },
  '3-25': { word: 'ladybug',   subject: 'a ladybug',                 instruction: 'Color the ladybug red with black dots!',           colorWord: 'red',    tags: [] },
  '3-26': { word: 'duck',      subject: 'ducks on a pond',           instruction: 'Color the pond with ducks!',                       colorWord: 'yellow', tags: [] },
  '3-27': { word: 'bee',       subject: 'a bee and flowers',         instruction: 'Color the bee and the flowers!',                   colorWord: 'yellow', tags: [] },
  '3-28': { word: 'rain',      subject: 'spring rain and rainbow',   instruction: 'Color the spring rain and rainbow!',               colorWord: 'blue',   tags: [] },
  '3-29': { word: 'lamb',      subject: 'baby animals',              instruction: 'Color the baby animals!',                          colorWord: 'white',  tags: [] },
  '3-30': { word: 'garden',    subject: 'a garden',                  instruction: 'Color the garden any colors you like!',            colorWord: 'green',  tags: [] },
  '3-31': { word: 'spring',    subject: 'a spring scene',            instruction: 'Color the spring scene!',                          colorWord: 'pink',   tags: [] },

  // ── April ─────────────────────────────────────────────────
  '4-1':  { word: 'egg',       subject: 'Easter eggs',               instruction: 'Color the Easter eggs bright colors!',              colorWord: 'pink',   tags: [] },
  '4-2':  { word: 'bunny',     subject: 'an Easter bunny',           instruction: 'Color the Easter bunny white and pink!',            colorWord: 'pink',   tags: [] },
  '4-3':  { word: 'chick',     subject: 'baby chicks',               instruction: 'Color the baby chicks yellow!',                     colorWord: 'yellow', tags: [] },
  '4-4':  { word: 'cross',     subject: 'an Easter cross',           instruction: 'Color the cross gold and the flowers pink!',        colorWord: 'gold',   tags: [] },
  '4-5':  { word: 'basket',    subject: 'an Easter basket filled with eggs', instruction: 'Color the Easter basket and fill the eggs with bright colors!', colorWord: 'yellow', tags: [] },
  '4-6':  { word: 'lamb',      subject: 'a baby lamb',               instruction: 'Color the lamb white and the grass green!',         colorWord: 'white',  tags: [] },
  '4-7':  { word: 'tulip',     subject: 'tulips',                    instruction: 'Color the tulips red and yellow!',                  colorWord: 'red',    tags: [] },
  '4-8':  { word: 'rain',      subject: 'April rain',                instruction: 'Color the raindrops blue and the umbrella yellow!', colorWord: 'blue',   tags: [] },
  '4-9':  { word: 'palm',      subject: 'palm branches',             instruction: 'Color the palm branches green!',                    colorWord: 'green',  tags: [] },
  '4-10': { word: 'robin',     subject: 'a robin',                   instruction: "Color the robin's chest orange-red!",               colorWord: 'red',    tags: [] },
  '4-11': { word: 'butterfly', subject: 'a butterfly',               instruction: 'Color the butterfly any colors you like!',          colorWord: 'orange', tags: [] },
  '4-12': { word: 'daisy',     subject: 'daisies',                   instruction: 'Color the daisies white and yellow!',               colorWord: 'white',  tags: [] },
  '4-13': { word: 'nest',      subject: 'a bird nest with eggs',     instruction: 'Color the nest brown and the eggs blue!',           colorWord: 'brown',  tags: [] },
  '4-14': { word: 'lily',      subject: 'Easter lilies',             instruction: 'Color the lilies white!',                           colorWord: 'white',  tags: [] },
  '4-15': { word: 'garden',    subject: 'a spring garden',           instruction: 'Color the spring garden any colors you like!',      colorWord: 'green',  tags: [] },
  '4-16': { word: 'frog',      subject: 'a frog on a lily pad',      instruction: 'Color the frog green and the lily pad dark green!', colorWord: 'green',  tags: [] },
  '4-17': { word: 'worm',      subject: 'a worm in the rain',        instruction: 'Color the worm pink and the rain blue!',            colorWord: 'pink',   tags: [] },
  '4-18': { word: 'cloud',     subject: 'spring clouds',             instruction: 'Color the clouds white and the sky blue!',          colorWord: 'blue',   tags: [] },
  '4-19': { word: 'duckling',  subject: 'ducklings',                 instruction: 'Color the ducklings yellow!',                       colorWord: 'yellow', tags: [] },
  '4-20': { word: 'rainbow',   subject: 'a spring rainbow',          instruction: 'Color the rainbow any colors you like!',            colorWord: 'purple', tags: [] },
  '4-21': { word: 'kite',      subject: 'a kite',                    instruction: 'Color the kite bright colors!',                     colorWord: 'red',    tags: [] },
  '4-22': { word: 'earth',     subject: 'the earth',                 instruction: 'Color the earth blue and green!',                   colorWord: 'green',  tags: [] },
  '4-23': { word: 'bee',       subject: 'a bee on a flower',         instruction: 'Color the bee yellow and black!',                   colorWord: 'yellow', tags: [] },
  '4-24': { word: 'blossom',   subject: 'cherry blossoms',           instruction: 'Color the cherry blossoms pink!',                   colorWord: 'pink',   tags: [] },
  '4-25': { word: 'snail',     subject: 'a snail',                   instruction: "Color the snail's shell brown and yellow!",         colorWord: 'brown',  tags: [] },
  '4-26': { word: 'ladybug',   subject: 'a ladybug',                 instruction: 'Color the ladybug red with black dots!',            colorWord: 'red',    tags: [] },
  '4-27': { word: 'mud',       subject: 'muddy boots',               instruction: 'Color the boots brown and muddy!',                  colorWord: 'brown',  tags: [] },
  '4-28': { word: 'iris',      subject: 'irises',                    instruction: 'Color the irises purple!',                          colorWord: 'purple', tags: [] },
  '4-29': { word: 'sprout',    subject: 'a seedling sprouting',      instruction: 'Color the sprout green and the soil brown!',        colorWord: 'green',  tags: [] },
  '4-30': { word: 'pond',      subject: 'a spring pond',             instruction: 'Color the pond blue and the lily pads green!',      colorWord: 'blue',   tags: [] },

  // ── May ───────────────────────────────────────────────────
  '5-1':  { word: 'mom',       subject: "a Mother's Day card",       instruction: "Color the Mother's Day card pink and gold!",        colorWord: 'pink',   tags: [] },
  '5-2':  { word: 'rose',      subject: 'roses',                     instruction: 'Color the roses red!',                              colorWord: 'red',    tags: [] },
  '5-3':  { word: 'sun',       subject: 'the bright May sun',        instruction: 'Color the sun yellow!',                             colorWord: 'yellow', tags: [] },
  '5-4':  { word: 'bird',      subject: 'a mother bird and nest',    instruction: 'Color the mama bird and her nest!',                 colorWord: 'brown',  tags: [] },
  '5-5':  { word: 'flower',    subject: 'a bouquet of flowers',      instruction: 'Color the bouquet any colors you like!',            colorWord: 'pink',   tags: [] },
  '5-6':  { word: 'butterfly', subject: 'a butterfly garden',        instruction: 'Color the butterflies bright colors!',              colorWord: 'orange', tags: [] },
  '5-7':  { word: 'garden',    subject: 'a flower garden',           instruction: 'Color the garden any colors you like!',             colorWord: 'green',  tags: [] },
  '5-8':  { word: 'bee',       subject: 'a honeybee',                instruction: 'Color the bee yellow and black!',                   colorWord: 'yellow', tags: [] },
  '5-9':  { word: 'hug',       subject: 'a mother and child hug',    instruction: 'Color the hug scene any colors you like!',          colorWord: 'pink',   tags: [] },
  '5-10': { word: 'crown',     subject: 'a flower crown',            instruction: 'Color the flower crown pink and yellow!',           colorWord: 'pink',   tags: [] },
  '5-11': { word: 'basket',    subject: 'a picnic basket',           instruction: 'Color the picnic basket brown!',                    colorWord: 'brown',  tags: [] },
  '5-12': { word: 'lily',      subject: 'lily of the valley',        instruction: 'Color the flowers white and the leaves green!',     colorWord: 'white',  tags: [] },
  '5-13': { word: 'heart',     subject: 'a heart made of flowers',   instruction: 'Color the flower heart pink and red!',              colorWord: 'red',    tags: [] },
  '5-14': { word: 'gift',      subject: 'a gift for mom',            instruction: 'Color the gift any colors you like!',               colorWord: 'purple', tags: [] },
  '5-15': { word: 'tree',      subject: 'a tree in bloom',           instruction: 'Color the tree pink and green!',                    colorWord: 'green',  tags: [] },
  '5-16': { word: 'ladybug',   subject: 'a ladybug',                 instruction: 'Color the ladybug red with black dots!',            colorWord: 'red',    tags: [] },
  '5-17': { word: 'turtle',    subject: 'a sea turtle',              instruction: 'Color the sea turtle green!',                       colorWord: 'green',  tags: [] },
  '5-18': { word: 'rainbow',   subject: 'a spring rainbow',          instruction: 'Color the rainbow any colors you like!',            colorWord: 'purple', tags: [] },
  '5-19': { word: 'daisy',     subject: 'daisies in a field',        instruction: 'Color the daisies white and yellow!',               colorWord: 'white',  tags: [] },
  '5-20': { word: 'kite',      subject: 'kites in the sky',          instruction: 'Color the kites bright colors!',                    colorWord: 'red',    tags: [] },
  '5-21': { word: 'caterpillar', subject: 'a caterpillar',           instruction: 'Color the caterpillar green!',                      colorWord: 'green',  tags: [] },
  '5-22': { word: 'cloud',     subject: 'fluffy clouds',             instruction: 'Color the clouds white and the sky blue!',          colorWord: 'blue',   tags: [] },
  '5-23': { word: 'snail',     subject: 'a snail on a leaf',         instruction: 'Color the leaf green and the shell yellow!',        colorWord: 'green',  tags: [] },
  '5-24': { word: 'frog',      subject: 'a frog',                    instruction: 'Color the frog green!',                             colorWord: 'green',  tags: [] },
  '5-25': { word: 'pond',      subject: 'a pond with ducks',         instruction: 'Color the pond blue and the ducks yellow!',         colorWord: 'blue',   tags: [] },
  '5-26': { word: 'dandelion', subject: 'dandelions',                instruction: 'Color the dandelions yellow!',                      colorWord: 'yellow', tags: [] },
  '5-27': { word: 'strawberry', subject: 'strawberries',             instruction: 'Color the strawberries red!',                       colorWord: 'red',    tags: [] },
  '5-28': { word: 'school',    subject: 'a schoolhouse',             instruction: 'Color the schoolhouse red!',                        colorWord: 'red',    tags: [] },
  '5-29': { word: 'pencil',    subject: 'pencils and crayons',       instruction: 'Color the pencils yellow and the crayons colorful!', colorWord: 'yellow', tags: [] },
  '5-30': { word: 'summer',    subject: 'a summer scene',            instruction: 'Color the summer scene bright colors!',             colorWord: 'yellow', tags: [] },
  '5-31': { word: 'dragonfly', subject: 'a dragonfly',               instruction: 'Color the dragonfly blue and green!',               colorWord: 'blue',   tags: [] },

  // ── June ──────────────────────────────────────────────────
  '6-1':  { word: 'beach',     subject: 'a beach scene',             instruction: 'Color the beach yellow and the water blue!',        colorWord: 'blue',   tags: [] },
  '6-2':  { word: 'wave',      subject: 'ocean waves',               instruction: 'Color the waves blue and white!',                   colorWord: 'blue',   tags: [] },
  '6-3':  { word: 'shell',     subject: 'seashells',                 instruction: 'Color the shells pink and white!',                  colorWord: 'pink',   tags: [] },
  '6-4':  { word: 'crab',      subject: 'a crab',                    instruction: 'Color the crab red!',                               colorWord: 'red',    tags: [] },
  '6-5':  { word: 'fish',      subject: 'colorful fish',             instruction: 'Color the fish bright colors!',                     colorWord: 'orange', tags: [] },
  '6-6':  { word: 'sun',       subject: 'the summer sun',            instruction: 'Color the sun bright yellow!',                      colorWord: 'yellow', tags: [] },
  '6-7':  { word: 'starfish',  subject: 'a starfish',                instruction: 'Color the starfish orange!',                        colorWord: 'orange', tags: [] },
  '6-8':  { word: 'turtle',    subject: 'a sea turtle',              instruction: 'Color the sea turtle green!',                       colorWord: 'green',  tags: [] },
  '6-9':  { word: 'lei',       subject: 'a Hawaiian lei',            instruction: 'Color the lei pink and purple!',                    colorWord: 'pink',   tags: [] },
  '6-10': { word: 'hula',      subject: 'a hula dancer',             instruction: "Color the hula dancer's skirt green!",              colorWord: 'green',  tags: [] },
  '6-11': { word: 'plumeria',  subject: 'plumeria flowers',          instruction: 'Color the plumeria pink and yellow!',               colorWord: 'pink',   tags: [] },
  '6-12': { word: 'rainbow',   subject: 'a Hawaiian rainbow',        instruction: 'Color the rainbow any colors you like!',            colorWord: 'purple', tags: [] },
  '6-13': { word: 'palm',      subject: 'palm trees',                instruction: 'Color the palm tree green and brown!',              colorWord: 'green',  tags: [] },
  '6-14': { word: 'icecream',  subject: 'an ice cream cone',         instruction: 'Color the ice cream any flavor you like!',          colorWord: 'pink',   tags: [] },
  '6-15': { word: 'turtle',    subject: 'a dad turtle wearing a tie with a baby turtle', instruction: 'Color the dad turtle and baby turtle green!', colorWord: 'green', tags: [] },
  '6-16': { word: 'dolphin',   subject: 'a dolphin',                 instruction: 'Color the dolphin grey and blue!',                  colorWord: 'blue',   tags: [] },
  '6-17': { word: 'sunset',    subject: 'an ocean sunset',           instruction: 'Color the sunset pink, orange, and gold!',          colorWord: 'orange', tags: [] },
  '6-18': { word: 'cloud',     subject: 'summer clouds',             instruction: 'Color the clouds white and the sky blue!',          colorWord: 'blue',   tags: [] },
  '6-19': { word: 'freedom',   subject: 'a hand holding a Juneteenth flag', instruction: 'Color the Juneteenth flag red, white, and blue!', colorWord: 'red', tags: [] },
  '6-20': { word: 'whale',     subject: 'a whale',                   instruction: 'Color the whale blue and the water turquoise!',     colorWord: 'blue',   tags: [] },
  '6-21': { word: 'pineapple', subject: 'a pineapple',               instruction: 'Color the pineapple yellow and green!',             colorWord: 'yellow', tags: [] },
  '6-22': { word: 'mango',     subject: 'mangoes',                   instruction: 'Color the mangoes orange and yellow!',              colorWord: 'orange', tags: [] },
  '6-23': { word: 'coral',     subject: 'coral reef',                instruction: 'Color the coral pink and orange!',                  colorWord: 'pink',   tags: [] },
  '6-24': { word: 'flower',    subject: 'tropical flowers',          instruction: 'Color the tropical flowers bright colors!',         colorWord: 'red',    tags: [] },
  '6-25': { word: 'hermit',    subject: 'a hermit crab',             instruction: 'Color the hermit crab red!',                        colorWord: 'red',    tags: [] },
  '6-26': { word: 'sand',      subject: 'sandcastles',               instruction: 'Color the sandcastle yellow and the sea blue!',     colorWord: 'yellow', tags: [] },
  '6-27': { word: 'seagull',   subject: 'seagulls',                  instruction: 'Color the seagulls white and grey!',                colorWord: 'white',  tags: [] },
  '6-28': { word: 'anchor',    subject: 'an anchor',                 instruction: 'Color the anchor dark blue!',                       colorWord: 'blue',   tags: [] },
  '6-29': { word: 'moonfish',  subject: 'a moonfish',                instruction: 'Color the moonfish silver and yellow!',             colorWord: 'yellow', tags: [] },
  '6-30': { word: 'aloha',     subject: 'an aloha sunset',           instruction: 'Color the aloha sunset any colors you like!',       colorWord: 'gold',   tags: [] },

  // ── July ──────────────────────────────────────────────────
  '7-1':  { word: 'flag',      subject: 'an American flag',          instruction: 'Color the flag red, white, and blue!',              colorWord: 'red',    tags: [] },
  '7-2':  { word: 'star',      subject: 'stars',                     instruction: 'Color the stars red, white, and blue!',             colorWord: 'blue',   tags: [] },
  '7-3':  { word: 'fireworks', subject: 'fireworks',                 instruction: 'Color the fireworks bright colors!',                colorWord: 'red',    tags: [] },
  '7-4':  { word: 'freedom',   subject: 'a 4th of July scene',       instruction: 'Color the 4th of July scene red, white, and blue!', colorWord: 'blue',  tags: [] },
  '7-5':  { word: 'eagle',     subject: 'a bald eagle',              instruction: 'Color the eagle brown with a white head!',          colorWord: 'brown',  tags: [] },
  '7-6':  { word: 'parade',    subject: 'a parade',                  instruction: 'Color the parade floats bright colors!',            colorWord: 'red',    tags: [] },
  '7-7':  { word: 'watermelon', subject: 'a watermelon',             instruction: 'Color the watermelon red and green!',               colorWord: 'red',    tags: [] },
  '7-8':  { word: 'beach',     subject: 'a summer beach',            instruction: 'Color the beach yellow and the sea blue!',          colorWord: 'blue',   tags: [] },
  '7-9':  { word: 'sun',       subject: 'the hot July sun',          instruction: 'Color the sun bright yellow!',                      colorWord: 'yellow', tags: [] },
  '7-10': { word: 'wave',      subject: 'big ocean waves',           instruction: 'Color the waves blue!',                             colorWord: 'blue',   tags: [] },
  '7-11': { word: 'fish',      subject: 'tropical fish',             instruction: 'Color the fish bright colors!',                     colorWord: 'orange', tags: [] },
  '7-12': { word: 'turtle',    subject: 'a sea turtle',              instruction: 'Color the sea turtle green!',                       colorWord: 'green',  tags: [] },
  '7-13': { word: 'dolphin',   subject: 'a jumping dolphin',         instruction: 'Color the dolphin grey and the water blue!',        colorWord: 'grey',   tags: [] },
  '7-14': { word: 'shell',     subject: 'seashells',                 instruction: 'Color the shells pink, white, and tan!',            colorWord: 'pink',   tags: [] },
  '7-15': { word: 'crab',      subject: 'a crab on the beach',       instruction: 'Color the crab orange-red!',                       colorWord: 'orange', tags: [] },
  '7-16': { word: 'turtle',    subject: 'a turtle eating ice cream',  instruction: 'Color the turtle and the ice cream!',               colorWord: 'green',  tags: [] },
  '7-17': { word: 'pineapple', subject: 'a pineapple',               instruction: 'Color the pineapple yellow and the top green!',     colorWord: 'yellow', tags: [] },
  '7-18': { word: 'lei',       subject: 'a flower lei',              instruction: 'Color the lei pink, yellow, and purple!',           colorWord: 'pink',   tags: [] },
  '7-19': { word: 'sunset',    subject: 'a summer sunset',           instruction: 'Color the sunset orange, pink, and purple!',        colorWord: 'orange', tags: [] },
  '7-20': { word: 'sandcastle', subject: 'a sandcastle',             instruction: 'Color the sandcastle golden and the sea blue!',     colorWord: 'yellow', tags: [] },
  '7-21': { word: 'butterfly', subject: 'a butterfly',               instruction: 'Color the butterfly any colors you like!',          colorWord: 'purple', tags: [] },
  '7-22': { word: 'garden',    subject: 'a summer garden',           instruction: 'Color the garden bright colors!',                   colorWord: 'green',  tags: [] },
  '7-23': { word: 'sunflower', subject: 'sunflowers',                instruction: 'Color the sunflowers yellow!',                      colorWord: 'yellow', tags: [] },
  '7-24': { word: 'corn',      subject: 'corn on the cob',           instruction: 'Color the corn yellow!',                            colorWord: 'yellow', tags: [] },
  '7-25': { word: 'berry',     subject: 'berries',                   instruction: 'Color the berries red and purple!',                 colorWord: 'red',    tags: [] },
  '7-26': { word: 'lemonade',  subject: 'a lemonade stand',          instruction: 'Color the lemonade yellow and the stand bright!',   colorWord: 'yellow', tags: [] },
  '7-27': { word: 'kite',      subject: 'kites in a blue sky',       instruction: 'Color the kites bright colors!',                    colorWord: 'red',    tags: [] },
  '7-28': { word: 'cloud',     subject: 'summer clouds',             instruction: 'Color the clouds white and the sky bright blue!',   colorWord: 'blue',   tags: [] },
  '7-29': { word: 'lily',      subject: 'water lilies',              instruction: 'Color the lilies pink and the pads green!',         colorWord: 'pink',   tags: [] },
  '7-30': { word: 'firefly',   subject: 'fireflies at night',        instruction: 'Color the fireflies yellow and the sky dark blue!', colorWord: 'yellow', tags: [] },
  '7-31': { word: 'summer',    subject: 'a summer fun scene',        instruction: 'Color the summer scene any colors you like!',       colorWord: 'orange', tags: [] },

  // ── August ────────────────────────────────────────────────
  '8-1':  { word: 'backpack',  subject: 'a backpack',                instruction: 'Color the backpack any colors you like!',           colorWord: 'blue',   tags: [] },
  '8-2':  { word: 'pencil',    subject: 'pencils',                   instruction: 'Color the pencils yellow!',                         colorWord: 'yellow', tags: [] },
  '8-3':  { word: 'book',      subject: 'books',                     instruction: 'Color the books bright colors!',                    colorWord: 'red',    tags: [] },
  '8-4':  { word: 'apple',     subject: 'an apple for the teacher',  instruction: 'Color the apple red!',                              colorWord: 'red',    tags: [] },
  '8-5':  { word: 'school',    subject: 'a schoolhouse',             instruction: 'Color the schoolhouse red and the door brown!',     colorWord: 'red',    tags: [] },
  '8-6':  { word: 'bus',       subject: 'a school bus',              instruction: 'Color the bus yellow!',                             colorWord: 'yellow', tags: [] },
  '8-7':  { word: 'crayon',    subject: 'crayons',                   instruction: 'Color the crayons all different colors!',           colorWord: 'red',    tags: [] },
  '8-8':  { word: 'ruler',     subject: 'a ruler',                   instruction: 'Color the ruler yellow!',                           colorWord: 'yellow', tags: [] },
  '8-9':  { word: 'beach',     subject: 'a last summer beach day',   instruction: 'Color the beach yellow and the ocean blue!',        colorWord: 'blue',   tags: [] },
  '8-10': { word: 'sun',       subject: 'the late summer sun',       instruction: 'Color the sun golden yellow!',                      colorWord: 'yellow', tags: [] },
  '8-11': { word: 'sunflower', subject: 'sunflowers',                instruction: 'Color the sunflowers yellow and brown!',            colorWord: 'yellow', tags: [] },
  '8-12': { word: 'corn',      subject: 'a cornfield',               instruction: 'Color the corn yellow and the stalks green!',       colorWord: 'yellow', tags: [] },
  '8-13': { word: 'butterfly', subject: 'a butterfly',               instruction: 'Color the butterfly orange and black!',             colorWord: 'orange', tags: [] },
  '8-14': { word: 'dragonfly', subject: 'a dragonfly',               instruction: 'Color the dragonfly blue!',                         colorWord: 'blue',   tags: [] },
  '8-15': { word: 'garden',    subject: 'a summer garden',           instruction: 'Color the garden any colors you like!',             colorWord: 'green',  tags: [] },
  '8-16': { word: 'fish',      subject: 'fish in a pond',            instruction: 'Color the fish orange and the pond blue!',          colorWord: 'orange', tags: [] },
  '8-17': { word: 'frog',      subject: 'a frog',                    instruction: 'Color the frog green!',                             colorWord: 'green',  tags: [] },
  '8-18': { word: 'melon',     subject: 'a watermelon',              instruction: 'Color the watermelon red and green!',               colorWord: 'red',    tags: [] },
  '8-19': { word: 'berry',     subject: 'blueberries',               instruction: 'Color the blueberries blue!',                       colorWord: 'blue',   tags: [] },
  '8-20': { word: 'peach',     subject: 'peaches',                   instruction: 'Color the peaches orange-pink!',                    colorWord: 'orange', tags: [] },
  '8-21': { word: 'cloud',     subject: 'late summer clouds',        instruction: 'Color the clouds white and the sky blue!',          colorWord: 'blue',   tags: [] },
  '8-22': { word: 'leaf',      subject: 'first falling leaves',      instruction: 'Color the leaves green with hints of yellow!',      colorWord: 'green',  tags: [] },
  '8-23': { word: 'acorn',     subject: 'acorns',                    instruction: 'Color the acorns brown!',                           colorWord: 'brown',  tags: [] },
  '8-24': { word: 'spider',    subject: 'a spider web with dew',     instruction: 'Color the web white and the dew drops blue!',       colorWord: 'white',  tags: [] },
  '8-25': { word: 'bee',       subject: 'a bee',                     instruction: 'Color the bee yellow and black!',                   colorWord: 'yellow', tags: [] },
  '8-26': { word: 'grasshopper', subject: 'a grasshopper',           instruction: 'Color the grasshopper green!',                      colorWord: 'green',  tags: [] },
  '8-27': { word: 'scissors',  subject: 'school scissors',           instruction: 'Color the scissors handles red!',                   colorWord: 'red',    tags: [] },
  '8-28': { word: 'glue',      subject: 'a glue stick',              instruction: 'Color the glue stick purple!',                      colorWord: 'purple', tags: [] },
  '8-29': { word: 'notebook',  subject: 'a notebook',                instruction: 'Color the notebook any color you like!',            colorWord: 'blue',   tags: [] },
  '8-30': { word: 'friend',    subject: 'friends at school',         instruction: 'Color the school friends any colors you like!',     colorWord: 'pink',   tags: [] },
  '8-31': { word: 'summer',    subject: 'a summer memory',           instruction: 'Color your favorite summer memory!',                colorWord: 'yellow', tags: [] },

  // ── September ─────────────────────────────────────────────
  '9-1':  { word: 'leaf',      subject: 'autumn leaves',             instruction: 'Color the leaves red, orange, and yellow!',         colorWord: 'orange', tags: [] },
  '9-2':  { word: 'acorn',     subject: 'acorns',                    instruction: 'Color the acorns brown!',                           colorWord: 'brown',  tags: [] },
  '9-3':  { word: 'apple',     subject: 'apples on a tree',          instruction: 'Color the apples red!',                             colorWord: 'red',    tags: [] },
  '9-4':  { word: 'school',    subject: 'a school scene',            instruction: 'Color the school any colors you like!',             colorWord: 'red',    tags: [] },
  '9-5':  { word: 'bus',       subject: 'a school bus',              instruction: 'Color the bus yellow!',                             colorWord: 'yellow', tags: [] },
  '9-6':  { word: 'pencil',    subject: 'pencils and paper',         instruction: 'Color the pencils yellow!',                         colorWord: 'yellow', tags: [] },
  '9-7':  { word: 'squirrel',  subject: 'a squirrel with a nut',     instruction: 'Color the squirrel brown!',                         colorWord: 'brown',  tags: [] },
  '9-8':  { word: 'mushroom',  subject: 'mushrooms',                 instruction: 'Color the mushroom cap red with white dots!',       colorWord: 'red',    tags: [] },
  '9-9':  { word: 'pear',      subject: 'pears',                     instruction: 'Color the pears yellow-green!',                     colorWord: 'green',  tags: [] },
  '9-10': { word: 'harvest',   subject: 'a harvest basket',          instruction: 'Color the basket brown and the produce colorful!',  colorWord: 'orange', tags: [] },
  '9-11': { word: 'corn',      subject: 'corn',                      instruction: 'Color the corn golden yellow!',                     colorWord: 'yellow', tags: [] },
  '9-12': { word: 'spider',    subject: 'a spider and web',          instruction: 'Color the spider black and the web white!',         colorWord: 'black',  tags: [] },
  '9-13': { word: 'owl',       subject: 'an owl on a branch',        instruction: 'Color the owl brown and the branch dark!',          colorWord: 'brown',  tags: [] },
  '9-14': { word: 'sunflower', subject: 'sunflowers',                instruction: 'Color the sunflowers yellow and brown!',            colorWord: 'yellow', tags: [] },
  '9-15': { word: 'pumpkin',   subject: 'pumpkins',                  instruction: 'Color the pumpkins orange!',                        colorWord: 'orange', tags: [] },
  '9-16': { word: 'tree',      subject: 'an autumn tree',            instruction: 'Color the tree red, orange, and yellow!',           colorWord: 'orange', tags: [] },
  '9-17': { word: 'grape',     subject: 'grapes',                    instruction: 'Color the grapes purple!',                          colorWord: 'purple', tags: [] },
  '9-18': { word: 'fog',       subject: 'a foggy morning',           instruction: 'Color the foggy scene grey and white!',             colorWord: 'grey',   tags: [] },
  '9-19': { word: 'deer',      subject: 'a deer in the forest',      instruction: 'Color the deer brown!',                             colorWord: 'brown',  tags: [] },
  '9-20': { word: 'berry',     subject: 'berries on a branch',       instruction: 'Color the berries red and the leaves orange!',      colorWord: 'red',    tags: [] },
  '9-21': { word: 'bat',       subject: 'a bat at dusk',             instruction: 'Color the bat black and the sky purple!',           colorWord: 'black',  tags: [] },
  '9-22': { word: 'hayride',   subject: 'a hayride',                 instruction: 'Color the hay golden and the wagon brown!',         colorWord: 'gold',   tags: [] },
  '9-23': { word: 'maple',     subject: 'a maple leaf',              instruction: 'Color the maple leaf bright red!',                  colorWord: 'red',    tags: [] },
  '9-24': { word: 'pinecone',  subject: 'pinecones',                 instruction: 'Color the pinecones brown!',                        colorWord: 'brown',  tags: [] },
  '9-25': { word: 'gourd',     subject: 'gourds',                    instruction: 'Color the gourds orange, yellow, and green!',       colorWord: 'orange', tags: [] },
  '9-26': { word: 'wagon',     subject: 'a red wagon of apples',     instruction: 'Color the wagon red and the apples red!',           colorWord: 'red',    tags: [] },
  '9-27': { word: 'scarecrow', subject: 'a scarecrow',               instruction: 'Color the scarecrow any colors you like!',          colorWord: 'orange', tags: [] },
  '9-28': { word: 'moon',      subject: 'a harvest moon',            instruction: 'Color the harvest moon orange!',                    colorWord: 'orange', tags: [] },
  '9-29': { word: 'crow',      subject: 'a crow on a fence',         instruction: 'Color the crow black!',                             colorWord: 'black',  tags: [] },
  '9-30': { word: 'autumn',    subject: 'an autumn scene',           instruction: 'Color the autumn scene any colors you like!',       colorWord: 'orange', tags: [] },

  // ── October ───────────────────────────────────────────────
  '10-1':  { word: 'pumpkin',   subject: 'a pumpkin',                instruction: 'Color the pumpkin!',                               colorWord: 'orange', tags: [] },
  '10-2':  { word: 'star',      subject: 'stars',                    instruction: 'Color the pumpkins orange and the stars yellow!',  colorWord: 'yellow', tags: [] },
  '10-3':  { word: 'leaf',      subject: 'autumn leaves',            instruction: 'Color the autumn leaves!',                         colorWord: 'orange', tags: [] },
  '10-4':  { word: 'haystack',  subject: 'a haystack',               instruction: 'Color the haystack golden and the sky blue!',      colorWord: 'gold',   tags: [] },
  '10-5':  { word: 'owl',       subject: 'an owl',                   instruction: 'Color the owl!',                                   colorWord: 'brown',  tags: [] },
  '10-6':  { word: 'apple',     subject: 'an apple tree',            instruction: 'Color the apple tree red and green!',              colorWord: 'red',    tags: [] },
  '10-7':  { word: 'scarecrow', subject: 'a scarecrow',              instruction: 'Color the scarecrow!',                             colorWord: 'orange', tags: [] },
  '10-8':  { word: 'moon',      subject: 'a moon',                   instruction: 'Color the moon yellow and the sky dark blue!',     colorWord: 'yellow', tags: [] },
  '10-9':  { word: 'corn',      subject: 'corn',                     instruction: 'Color the corn golden yellow!',                    colorWord: 'yellow', tags: [] },
  '10-10': { word: 'forest',    subject: 'an autumn forest',         instruction: 'Color the autumn forest!',                         colorWord: 'orange', tags: [] },
  '10-11': { word: 'bat',       subject: 'a bat',                    instruction: 'Color the bat black and the moon yellow!',         colorWord: 'black',  tags: [] },
  '10-12': { word: 'web',       subject: 'a spider web',             instruction: 'Color the spider web!',                            colorWord: 'white',  tags: [] },
  '10-13': { word: 'harvest',   subject: 'a harvest basket',         instruction: 'Color the harvest basket!',                        colorWord: 'orange', tags: [] },
  '10-14': { word: 'diya',      subject: 'a diya lamp',              instruction: 'Color the diya lamp!',                             colorWord: 'red',    tags: [] },
  '10-15': { word: 'lantern',   subject: 'Diwali lanterns',          instruction: 'Color the Diwali lanterns orange and yellow!',     colorWord: 'orange', tags: [] },
  '10-16': { word: 'Rangoli',   subject: 'a Rangoli pattern',        instruction: 'Color the Rangoli pattern!',                       colorWord: 'purple', tags: [] },
  '10-17': { word: 'peacock',   subject: 'a peacock',                instruction: 'Color the peacock!',                               colorWord: 'blue',   tags: [] },
  '10-18': { word: 'fireworks', subject: 'fireworks',                instruction: 'Color the fireworks any colors you like!',         colorWord: 'yellow', tags: [] },
  '10-19': { word: 'Rama',      subject: 'a Ramayana scene',         instruction: 'Color the Ramayana scene!',                        colorWord: 'gold',   tags: [] },
  '10-20': { word: 'sweet',     subject: 'Diwali sweets',            instruction: 'Color the Diwali sweets!',                         colorWord: 'pink',   tags: [] },
  '10-21': { word: 'flame',     subject: 'diyas',                    instruction: 'Color the diyas red and yellow!',                  colorWord: 'yellow', tags: [] },
  '10-22': { word: 'unicorn',   subject: 'a unicorn',                instruction: 'Color the magical unicorn!',                       colorWord: 'purple', tags: [] },
  '10-23': { word: 'elephant',  subject: 'a decorated elephant',     instruction: 'Color the elephant with decorations!',             colorWord: 'purple', tags: [] },
  '10-24': { word: 'patch',     subject: 'a pumpkin patch',          instruction: 'Color the autumn pumpkin patch!',                  colorWord: 'orange', tags: [] },
  '10-25': { word: 'jack',      subject: 'a Jack-o-lantern',         instruction: 'Color the Jack-o-lantern!',                        colorWord: 'orange', tags: [] },
  '10-26': { word: 'witch',     subject: 'a witch hat',              instruction: 'Color the witch hat black and purple!',            colorWord: 'purple', tags: [] },
  '10-27': { word: 'candy',     subject: 'candy corn',               instruction: 'Color the candy corn yellow, orange, and white!',  colorWord: 'orange', tags: [] },
  '10-28': { word: 'ghost',     subject: 'a ghost',                  instruction: 'Color the ghost!',                                 colorWord: 'white',  tags: [] },
  '10-29': { word: 'tree',      subject: 'an autumn tree',           instruction: 'Color the autumn tree!',                           colorWord: 'orange', tags: [] },
  '10-30': { word: 'Halloween', subject: 'a Halloween scene',        instruction: 'Color the Halloween scene any colors you like!',   colorWord: 'purple', tags: [] },
  '10-31': { word: 'sky',       subject: 'a Halloween night sky',    instruction: 'Color the Halloween night sky!',                   colorWord: 'black',  tags: [] },

  // ── November ──────────────────────────────────────────────
  '11-1':  { word: 'turkey',    subject: 'a turkey',                 instruction: 'Color the turkey brown and the feathers colorful!', colorWord: 'brown', tags: [] },
  '11-2':  { word: 'leaf',      subject: 'falling leaves',           instruction: 'Color the leaves red, orange, and yellow!',        colorWord: 'orange', tags: [] },
  '11-3':  { word: 'saint',     subject: 'All Saints Day scene',     instruction: "Color the saints' scene gold and white!",          colorWord: 'gold',   tags: [] },
  '11-4':  { word: 'thankful',  subject: 'a thankful heart',         instruction: 'Color the thankful heart red and gold!',           colorWord: 'red',    tags: [] },
  '11-5':  { word: 'acorn',     subject: 'acorns and leaves',        instruction: 'Color the acorns brown and the leaves orange!',    colorWord: 'brown',  tags: [] },
  '11-6':  { word: 'pie',       subject: 'a pumpkin pie',            instruction: 'Color the pie orange and the crust golden!',       colorWord: 'orange', tags: [] },
  '11-7':  { word: 'corn',      subject: 'Indian corn',              instruction: 'Color the corn with many colors!',                 colorWord: 'yellow', tags: [] },
  '11-8':  { word: 'harvest',   subject: 'a harvest table',          instruction: 'Color the harvest table brown and colorful!',      colorWord: 'brown',  tags: [] },
  '11-9':  { word: 'deer',      subject: 'a deer in autumn',         instruction: 'Color the deer brown!',                            colorWord: 'brown',  tags: [] },
  '11-10': { word: 'candle',    subject: 'a Thanksgiving candle',    instruction: 'Color the candle orange and the flame yellow!',    colorWord: 'orange', tags: [] },
  '11-11': { word: 'veteran',   subject: 'a flag for Veterans Day',  instruction: 'Color the flag red, white, and blue!',             colorWord: 'red',    tags: [] },
  '11-12': { word: 'owl',       subject: 'an owl in the leaves',     instruction: 'Color the owl brown and the leaves orange!',       colorWord: 'brown',  tags: [] },
  '11-13': { word: 'apple',     subject: 'an apple pie',             instruction: 'Color the pie golden brown!',                      colorWord: 'brown',  tags: [] },
  '11-14': { word: 'squirrel',  subject: 'a squirrel gathering nuts', instruction: 'Color the squirrel orange-brown!',               colorWord: 'brown',  tags: [] },
  '11-15': { word: 'pumpkin',   subject: 'a pumpkin',                instruction: 'Color the pumpkin orange!',                        colorWord: 'orange', tags: [] },
  '11-16': { word: 'pinecone',  subject: 'pinecones',                instruction: 'Color the pinecones brown!',                       colorWord: 'brown',  tags: [] },
  '11-17': { word: 'bread',     subject: 'a loaf of bread',          instruction: 'Color the bread golden brown!',                    colorWord: 'brown',  tags: [] },
  '11-18': { word: 'family',    subject: 'a family together',        instruction: 'Color the family scene any colors you like!',      colorWord: 'red',    tags: [] },
  '11-19': { word: 'maple',     subject: 'a maple tree',             instruction: 'Color the maple tree red and orange!',             colorWord: 'red',    tags: [] },
  '11-20': { word: 'feast',     subject: 'a Thanksgiving feast',     instruction: 'Color the feast table any colors you like!',       colorWord: 'orange', tags: [] },
  '11-21': { word: 'pilgrim',   subject: 'a Pilgrim hat',            instruction: 'Color the Pilgrim hat black and the buckle gold!', colorWord: 'black',  tags: [] },
  '11-22': { word: 'cornucopia', subject: 'a cornucopia',            instruction: 'Color the cornucopia brown and the fruits colorful!', colorWord: 'brown', tags: [] },
  '11-23': { word: 'wagon',     subject: 'a covered wagon',          instruction: 'Color the wagon brown!',                           colorWord: 'brown',  tags: [] },
  '11-24': { word: 'Native',    subject: 'a Native American scene',  instruction: 'Color the scene with warm, earthy colors!',        colorWord: 'brown',  tags: [] },
  '11-25': { word: 'autumn',    subject: 'an autumn forest',         instruction: 'Color the forest red, orange, and yellow!',        colorWord: 'orange', tags: [] },
  '11-26': { word: 'star',      subject: 'a star of gratitude',      instruction: 'Color the gratitude star gold!',                   colorWord: 'gold',   tags: [] },
  '11-27': { word: 'thanks',    subject: 'a Thanksgiving scene',     instruction: 'Color the Thanksgiving scene any colors you like!', colorWord: 'orange', tags: [] },
  '11-28': { word: 'tree',      subject: 'a bare winter tree',       instruction: 'Color the bare tree brown and the sky grey!',      colorWord: 'brown',  tags: [] },
  '11-29': { word: 'advent',    subject: 'an Advent wreath',         instruction: 'Color the Advent wreath green with purple candles!', colorWord: 'purple', tags: [] },
  '11-30': { word: 'hope',      subject: 'a candle of hope',         instruction: 'Color the candle purple and the flame yellow!',    colorWord: 'purple', tags: [] },
};
