import { AffirmationMap } from '../../types';

// Non-religious wisdom quotes — 365 entries, one per day
// Extracted from v1 GENERIC_AFFIRMATIONS

export const universalAffirmations: AffirmationMap = {
  // ── JANUARY ──────────────────────────────────────────────────────────────
  "1-1": { quote: "Tomorrow is the first blank page of a 365-page book. Write a good one.", ref: "Brad Paisley", tradition: "universal" },
  "1-2": { quote: "Enjoy the little things, for one day you may look back and realize they were the big things.", ref: "R. Brault", tradition: "universal" },
  "1-3": { quote: "You are braver than you believe, stronger than you seem, and smarter than you think.", ref: "A.A. Milne", tradition: "universal" },
  "1-4": { quote: "No act of kindness, no matter how small, is ever wasted.", ref: "Aesop", tradition: "universal" },
  "1-5": { quote: "Look deep into nature, and then you will understand everything better.", ref: "Einstein", tradition: "universal" },
  "1-6": { quote: "We rise by lifting others.", ref: "R.G. Ingersoll", tradition: "universal" },
  "1-7": { quote: "You can't use up creativity. The more you use, the more you have.", ref: "Maya Angelou", tradition: "universal" },
  "1-8": { quote: "The best thing to hold onto in life is each other.", ref: "Audrey Hepburn", tradition: "universal" },
  "1-9": { quote: "The world is full of magical things, patiently waiting for our senses to grow sharper.", ref: "W.B. Yeats", tradition: "universal" },
  "1-10": { quote: "Happiness is only real when shared.", ref: "Jon Krakauer", tradition: "universal" },
  "1-11": { quote: "Kind words can be short and easy to speak, but their echoes are truly endless.", ref: "Mother Teresa", tradition: "universal" },
  "1-12": { quote: "Patience is not the ability to wait, but how you act while you're waiting.", ref: "Joyce Meyer", tradition: "universal" },
  "1-13": { quote: "Music gives a soul to the universe and wings to the mind.", ref: "Plato", tradition: "universal" },
  "1-14": { quote: "Almost everything will work again if you unplug it for a few minutes — including you.", ref: "Anne Lamott", tradition: "universal" },
  "1-15": { quote: "The time is always right to do what is right.", ref: "Martin Luther King Jr.", tradition: "universal" },
  "1-16": { quote: "Every child is an artist. The challenge is staying an artist when you grow up.", ref: "Picasso", tradition: "universal" },
  "1-17": { quote: "Not all those who wander are lost.", ref: "J.R.R. Tolkien", tradition: "universal" },
  "1-18": { quote: "It takes great bravery to stand up to our enemies, but even more to stand up to our friends.", ref: "J.K. Rowling", tradition: "universal" },
  "1-19": { quote: "Be the change you wish to see in the world.", ref: "Gandhi", tradition: "universal" },
  "1-20": { quote: "If you have good thoughts, they will shine out of your face like sunbeams.", ref: "Roald Dahl", tradition: "universal" },
  "1-21": { quote: "In every walk with nature, one receives far more than they seek.", ref: "John Muir", tradition: "universal" },
  "1-22": { quote: "When you are grateful, fear disappears and abundance appears.", ref: "Tony Robbins", tradition: "universal" },
  "1-23": { quote: "We have two ears and one mouth so we can listen twice as much as we speak.", ref: "Epictetus", tradition: "universal" },
  "1-24": { quote: "Wherever you are, be all there.", ref: "Jim Elliot", tradition: "universal" },
  "1-25": { quote: "What is done in love is done well.", ref: "Vincent van Gogh", tradition: "universal" },
  "1-26": { quote: "It always seems impossible until it is done.", ref: "Nelson Mandela", tradition: "universal" },
  "1-27": { quote: "Too often we underestimate the power of a smile.", ref: "Leo Buscaglia", tradition: "universal" },
  "1-28": { quote: "You yourself, as much as anybody in the universe, deserve your love.", ref: "Buddha", tradition: "universal" },
  "1-29": { quote: "The sky is everywhere. It begins at your feet.", ref: "Jandy Nelson", tradition: "universal" },
  "1-30": { quote: "The purpose of life is to contribute in some way to making things better.", ref: "Robert F. Kennedy", tradition: "universal" },
  "1-31": { quote: "Life is what happens when you're busy making other plans.", ref: "John Lennon", tradition: "universal" },
  // ── FEBRUARY ─────────────────────────────────────────────────────────────
  "2-1": { quote: "I have a dream that my children will live in a nation where they will not be judged by the color of their skin.", ref: "Dr. Martin Luther King Jr.", tradition: "universal" },
  "2-2": { quote: "If you're always trying to be normal, you will never know how amazing you can be.", ref: "Maya Angelou", tradition: "universal" },
  "2-3": { quote: "When you learn, teach. When you get, give.", ref: "Maya Angelou", tradition: "universal" },
  "2-4": { quote: "The most common way people give up their power is by thinking they don't have any.", ref: "Alice Walker", tradition: "universal" },
  "2-5": { quote: "We must believe that we are gifted for something, and that this thing must be attained.", ref: "Marie Curie", tradition: "universal" },
  "2-6": { quote: "Darkness cannot drive out darkness — only light can do that.", ref: "Dr. Martin Luther King Jr.", tradition: "universal" },
  "2-7": { quote: "I am no longer accepting the things I cannot change. I am changing the things I cannot accept.", ref: "Angela Davis", tradition: "universal" },
  "2-8": { quote: "You are enough just as you are.", ref: "Harriet Tubman", tradition: "universal" },
  "2-9": { quote: "In recognizing the humanity of our fellow beings, we pay ourselves the highest tribute.", ref: "Thurgood Marshall", tradition: "universal" },
  "2-10": { quote: "Change will not come if we wait for some other person or some other time.", ref: "Barack Obama", tradition: "universal" },
  "2-11": { quote: "If you can't fly, then run. If you can't run, then walk. But whatever you do, keep moving forward.", ref: "Dr. Martin Luther King Jr.", tradition: "universal" },
  "2-12": { quote: "Music is the shorthand of emotion.", ref: "Leo Tolstoy", tradition: "universal" },
  "2-13": { quote: "You alone are enough. You have nothing to prove to anyone.", ref: "Maya Angelou", tradition: "universal" },
  "2-14": { quote: "The best and most beautiful things cannot be seen or touched — they must be felt with the heart.", ref: "Helen Keller", tradition: "universal" },
  "2-15": { quote: "Love recognizes no barriers.", ref: "Maya Angelou", tradition: "universal" },
  "2-16": { quote: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", ref: "James Baldwin", tradition: "universal" },
  "2-17": { quote: "We must learn to live together as brothers or perish together as fools.", ref: "Dr. Martin Luther King Jr.", tradition: "universal" },
  "2-18": { quote: "There is no greater agony than bearing an untold story inside you.", ref: "Maya Angelou", tradition: "universal" },
  "2-19": { quote: "Do what you can, with what you have, where you are.", ref: "Booker T. Washington", tradition: "universal" },
  "2-20": { quote: "If I didn't leave bitterness and hatred behind, I'd still be in prison.", ref: "Nelson Mandela", tradition: "universal" },
  "2-21": { quote: "Education is the most powerful weapon which you can use to change the world.", ref: "Nelson Mandela", tradition: "universal" },
  "2-22": { quote: "Honesty and transparency make you vulnerable. Be honest and transparent anyway.", ref: "Mother Teresa", tradition: "universal" },
  "2-23": { quote: "Life's most persistent and urgent question is: What are you doing for others?", ref: "Dr. Martin Luther King Jr.", tradition: "universal" },
  "2-24": { quote: "Creativity takes courage.", ref: "Henri Matisse", tradition: "universal" },
  "2-25": { quote: "Gratitude is the fairest blossom which springs from the soul.", ref: "Henry Ward Beecher", tradition: "universal" },
  "2-26": { quote: "Peace is not the absence of conflict, but the ability to handle conflict by peaceful means.", ref: "Ronald Reagan", tradition: "universal" },
  "2-27": { quote: "I can't change the direction of the wind, but I can adjust my sails.", ref: "Jimmy Dean", tradition: "universal" },
  "2-28": { quote: "The time is always right to do what is right.", ref: "Dr. Martin Luther King Jr.", tradition: "universal" },
  // ── MARCH ────────────────────────────────────────────────────────────────
  "3-1": { quote: "Well-behaved women seldom make history.", ref: "Laurel Thatcher Ulrich", tradition: "universal" },
  "3-2": { quote: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", ref: "Mother Teresa", tradition: "universal" },
  "3-3": { quote: "The most courageous act is still to think for yourself. Aloud.", ref: "Coco Chanel", tradition: "universal" },
  "3-4": { quote: "I paint my own reality.", ref: "Frida Kahlo", tradition: "universal" },
  "3-5": { quote: "The greatness of a nation can be judged by the way its animals are treated.", ref: "Gandhi", tradition: "universal" },
  "3-6": { quote: "Music can change the world because it can change people.", ref: "Bono", tradition: "universal" },
  "3-7": { quote: "The world is big and I want to have a good look at it before it gets dark.", ref: "John Muir", tradition: "universal" },
  "3-8": { quote: "A woman is like a tea bag — you never know how strong she is until she's in hot water.", ref: "Eleanor Roosevelt", tradition: "universal" },
  "3-9": { quote: "Have patience with all things, but first of all with yourself.", ref: "St. Francis de Sales", tradition: "universal" },
  "3-10": { quote: "Life isn't about waiting for the storm to pass — it's about learning to dance in the rain.", ref: "Vivian Greene", tradition: "universal" },
  "3-11": { quote: "Alone we can do so little; together we can do so much.", ref: "Helen Keller", tradition: "universal" },
  "3-12": { quote: "Laughter is the sun that drives winter from the human face.", ref: "Victor Hugo", tradition: "universal" },
  "3-13": { quote: "Adventure is worthwhile in itself.", ref: "Amelia Earhart", tradition: "universal" },
  "3-14": { quote: "Despite everything, I believe that people are really good at heart.", ref: "Anne Frank", tradition: "universal" },
  "3-15": { quote: "No one has ever become poor by giving.", ref: "Anne Frank", tradition: "universal" },
  "3-16": { quote: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", ref: "Anne Frank", tradition: "universal" },
  "3-17": { quote: "May your thoughts be as glad as the shamrocks. May your heart be as light as a song.", ref: "Irish Blessing", tradition: "universal" },
  "3-18": { quote: "One child, one teacher, one book, one pen can change the world.", ref: "Malala Yousafzai", tradition: "universal" },
  "3-19": { quote: "If we had no winter, the spring would not be so pleasant.", ref: "Anne Bradstreet", tradition: "universal" },
  "3-20": { quote: "No matter how long the winter, spring is sure to follow.", ref: "African Proverb", tradition: "universal" },
  "3-21": { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", ref: "Chinese Proverb", tradition: "universal" },
  "3-22": { quote: "Wherever you go, no matter what the weather, always bring your own sunshine.", ref: "Anthony D'Angelo", tradition: "universal" },
  "3-23": { quote: "Earth has no sorrow that earth cannot heal.", ref: "John Muir", tradition: "universal" },
  "3-24": { quote: "Too often we underestimate the power of a kind word.", ref: "Leo Buscaglia", tradition: "universal" },
  "3-25": { quote: "Be kind, for everyone you meet is fighting a harder battle.", ref: "Plato", tradition: "universal" },
  "3-26": { quote: "The smallest act of kindness is worth more than the grandest intention.", ref: "Oscar Wilde", tradition: "universal" },
  "3-27": { quote: "Between every two pines is a doorway to a new world.", ref: "John Muir", tradition: "universal" },
  "3-28": { quote: "Creativity is intelligence having fun.", ref: "Einstein", tradition: "universal" },
  "3-29": { quote: "If you want others to be happy, practice compassion.", ref: "Dalai Lama", tradition: "universal" },
  "3-30": { quote: "Enough is a feast.", ref: "Buddhist Proverb", tradition: "universal" },
  "3-31": { quote: "Write it on your heart that every day is the best day in the year.", ref: "Ralph Waldo Emerson", tradition: "universal" },
  // ── APRIL ────────────────────────────────────────────────────────────────
  "4-1": { quote: "April hath put a spirit of youth in everything.", ref: "Shakespeare", tradition: "universal" },
  "4-2": { quote: "In a gentle way, you can shake the world.", ref: "Gandhi", tradition: "universal" },
  "4-3": { quote: "Love is not something you go out and look for. Love is something that finds you.", ref: "Loretta Young", tradition: "universal" },
  "4-4": { quote: "Everything is made of light. Everything.", ref: "Rumi", tradition: "universal" },
  "4-5": { quote: "Nothing is impossible. The word itself says I'm possible!", ref: "Audrey Hepburn", tradition: "universal" },
  "4-6": { quote: "Joy is not in things; it is in us.", ref: "Richard Wagner", tradition: "universal" },
  "4-7": { quote: "To plant a garden is to believe in tomorrow.", ref: "Audrey Hepburn", tradition: "universal" },
  "4-8": { quote: "Let the rain kiss you. Let the rain beat upon your head with silver liquid drops.", ref: "Langston Hughes", tradition: "universal" },
  "4-9": { quote: "A bird does not sing because it has an answer. It sings because it has a song.", ref: "Chinese Proverb", tradition: "universal" },
  "4-10": { quote: "Happiness is a butterfly — the more you chase it, the more it eludes you.", ref: "Nathaniel Hawthorne", tradition: "universal" },
  "4-11": { quote: "Follow your bliss and the universe will open doors where there were only walls.", ref: "Joseph Campbell", tradition: "universal" },
  "4-12": { quote: "Service to others is the rent you pay for your room here on earth.", ref: "Muhammad Ali", tradition: "universal" },
  "4-13": { quote: "We do not inherit the earth from our ancestors; we borrow it from our children.", ref: "Native American Proverb", tradition: "universal" },
  "4-14": { quote: "A smile is the shortest distance between two people.", ref: "Victor Borge", tradition: "universal" },
  "4-15": { quote: "No matter what people tell you, words and ideas can change the world.", ref: "Robin Williams", tradition: "universal" },
  "4-16": { quote: "If you look the right way, you can see that the whole world is a garden.", ref: "Frances Hodgson Burnett", tradition: "universal" },
  "4-17": { quote: "Dare to live the life you have dreamed for yourself.", ref: "Emerson", tradition: "universal" },
  "4-18": { quote: "Until one has loved an animal, a part of one's soul remains unawakened.", ref: "Anatole France", tradition: "universal" },
  "4-19": { quote: "When you realize how perfect everything is, you will tilt your head back and laugh at the sky.", ref: "Buddha", tradition: "universal" },
  "4-20": { quote: "Whatever you are, be a good one.", ref: "Abraham Lincoln", tradition: "universal" },
  "4-21": { quote: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", ref: "Einstein", tradition: "universal" },
  "4-22": { quote: "The earth does not belong to us. We belong to the earth.", ref: "Chief Seattle", tradition: "universal" },
  "4-23": { quote: "Three things matter most in human life: be kind, be kind, be kind.", ref: "Henry James", tradition: "universal" },
  "4-24": { quote: "Children flourish when they feel good about themselves.", ref: "Barbara Bush", tradition: "universal" },
  "4-25": { quote: "The two most powerful warriors are patience and time.", ref: "Leo Tolstoy", tradition: "universal" },
  "4-26": { quote: "I think it pisses God off if you walk by the color purple in a field somewhere and don't notice it.", ref: "Alice Walker", tradition: "universal" },
  "4-27": { quote: "The silence of nature is very real. It surrounds you.", ref: "Ted Trueblood", tradition: "universal" },
  "4-28": { quote: "A friend is someone who knows all about you and still loves you.", ref: "Elbert Hubbard", tradition: "universal" },
  "4-29": { quote: "In the middle of every difficulty lies opportunity.", ref: "Einstein", tradition: "universal" },
  "4-30": { quote: "And into the forest I go, to lose my mind and find my soul.", ref: "John Muir", tradition: "universal" },
  // ── MAY ──────────────────────────────────────────────────────────────────
  "5-1": { quote: "Today is your day! Your mountain is waiting, so get on your way!", ref: "Dr. Seuss", tradition: "universal" },
  "5-2": { quote: "Earth laughs in flowers.", ref: "Ralph Waldo Emerson", tradition: "universal" },
  "5-3": { quote: "Live in the sunshine, swim the sea, drink the wild air.", ref: "Emerson", tradition: "universal" },
  "5-4": { quote: "A mother's love enables a normal human being to do the impossible.", ref: "Marion C. Garretty", tradition: "universal" },
  "5-5": { quote: "The flower that blooms in adversity is the most rare and beautiful of all.", ref: "Walt Disney", tradition: "universal" },
  "5-6": { quote: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through.", ref: "Maya Angelou", tradition: "universal" },
  "5-7": { quote: "To forget how to dig the earth and tend the soil is to forget ourselves.", ref: "Gandhi", tradition: "universal" },
  "5-8": { quote: "The bee is more honored than other animals not because it labors, but because it labors for others.", ref: "St. John Chrysostom", tradition: "universal" },
  "5-9": { quote: "A mother is she who can take the place of all others, but whose place no one else can take.", ref: "Cardinal Mermillod", tradition: "universal" },
  "5-10": { quote: "The secret of getting ahead is getting started.", ref: "Mark Twain", tradition: "universal" },
  "5-11": { quote: "Motherhood is the greatest thing and the hardest thing.", ref: "Ricki Lake", tradition: "universal" },
  "5-12": { quote: "Kindness in words creates confidence. Kindness in thinking creates profoundness.", ref: "Lao Tzu", tradition: "universal" },
  "5-13": { quote: "Flowers always make people better, happier, and more helpful.", ref: "Luther Burbank", tradition: "universal" },
  "5-14": { quote: "Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.", ref: "Dr. Seuss", tradition: "universal" },
  "5-15": { quote: "A tree that is unbending is easily broken.", ref: "Lao Tzu", tradition: "universal" },
  "5-16": { quote: "Courage is not the absence of fear but the triumph over it.", ref: "Nelson Mandela", tradition: "universal" },
  "5-17": { quote: "The greatness of a nation can be judged by the way its animals are treated.", ref: "Gandhi", tradition: "universal" },
  "5-18": { quote: "The only way to do great work is to love what you do.", ref: "Steve Jobs", tradition: "universal" },
  "5-19": { quote: "There is no place like home.", ref: "L. Frank Baum", tradition: "universal" },
  "5-20": { quote: "Your time is limited, so don't waste it living someone else's life.", ref: "Steve Jobs", tradition: "universal" },
  "5-21": { quote: "Every strike brings me closer to the next home run.", ref: "Babe Ruth", tradition: "universal" },
  "5-22": { quote: "Climb the mountains and get their good tidings.", ref: "John Muir", tradition: "universal" },
  "5-23": { quote: "Nature does not hurry, yet everything is accomplished.", ref: "Lao Tzu", tradition: "universal" },
  "5-24": { quote: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", ref: "Dr. Seuss", tradition: "universal" },
  "5-25": { quote: "Water is the driving force of all nature.", ref: "Leonardo da Vinci", tradition: "universal" },
  "5-26": { quote: "We must find time to stop and thank the people who make a difference in our lives.", ref: "JFK", tradition: "universal" },
  "5-27": { quote: "One of the nicest things about life is the way we must regularly stop to eat.", ref: "Pavarotti", tradition: "universal" },
  "5-28": { quote: "The more that you read, the more things you will know.", ref: "Dr. Seuss", tradition: "universal" },
  "5-29": { quote: "Drawing is the honesty of art.", ref: "Salvador Dali", tradition: "universal" },
  "5-30": { quote: "The future belongs to those who believe in the beauty of their dreams.", ref: "Eleanor Roosevelt", tradition: "universal" },
  "5-31": { quote: "In every walk with nature, one receives far more than they seek.", ref: "John Muir", tradition: "universal" },
  // ── JUNE ─────────────────────────────────────────────────────────────────
  "6-1": { quote: "Summer is the time when one sheds one's tensions with one's clothes.", ref: "Ada Louise Huxtable", tradition: "universal" },
  "6-2": { quote: "You can't stop the waves, but you can learn to surf.", ref: "Jon Kabat-Zinn", tradition: "universal" },
  "6-3": { quote: "The earth has music for those who listen.", ref: "George Santayana", tradition: "universal" },
  "6-4": { quote: "Happiness depends upon ourselves.", ref: "Aristotle", tradition: "universal" },
  "6-5": { quote: "The sea, once it casts its spell, holds one in its net of wonder forever.", ref: "Jacques Cousteau", tradition: "universal" },
  "6-6": { quote: "Keep your face always toward the sunshine, and shadows will fall behind you.", ref: "Walt Whitman", tradition: "universal" },
  "6-7": { quote: "Reach for the stars, even if you have to stand on a cactus.", ref: "Susan Longacre", tradition: "universal" },
  "6-8": { quote: "Water is life's matter and matrix, mother and medium.", ref: "Albert Szent-Gyorgyi", tradition: "universal" },
  "6-9": { quote: "Somewhere over the rainbow, skies are blue, and the dreams that you dare to dream really do come true.", ref: "E.Y. Harburg", tradition: "universal" },
  "6-10": { quote: "To watch us dance is to hear our hearts speak.", ref: "Indian Proverb", tradition: "universal" },
  "6-11": { quote: "Laughter is sunshine. It chases winter from the human face.", ref: "Victor Hugo", tradition: "universal" },
  "6-12": { quote: "Try to be a rainbow in someone's cloud.", ref: "Maya Angelou", tradition: "universal" },
  "6-13": { quote: "The world is a book, and those who do not travel read only one page.", ref: "Saint Augustine", tradition: "universal" },
  "6-14": { quote: "Life is short. Eat dessert first.", ref: "Jacques Torres", tradition: "universal" },
  "6-15": { quote: "My father gave me the greatest gift anyone could give another person: he believed in me.", ref: "Jim Valvano", tradition: "universal" },
  "6-16": { quote: "Any man can be a father, but it takes someone special to be a dad.", ref: "Anne Geddes", tradition: "universal" },
  "6-17": { quote: "Live in the sunshine, swim the sea, drink the wild air.", ref: "Ralph Waldo Emerson", tradition: "universal" },
  "6-18": { quote: "Clouds come floating into my life to add color to my sunset sky.", ref: "Tagore", tradition: "universal" },
  "6-19": { quote: "Freedom is never really won. You earn it and win it in every generation.", ref: "Coretta Scott King", tradition: "universal" },
  "6-20": { quote: "The ocean is a mighty harmonist.", ref: "William Wordsworth", tradition: "universal" },
  "6-21": { quote: "Good food is the foundation of genuine happiness.", ref: "Auguste Escoffier", tradition: "universal" },
  "6-22": { quote: "Summer afternoon — to me those have always been the two most beautiful words.", ref: "Henry James", tradition: "universal" },
  "6-23": { quote: "The more I learn, the more I realize how much I don't know.", ref: "Einstein", tradition: "universal" },
  "6-24": { quote: "Where flowers bloom, so does hope.", ref: "Lady Bird Johnson", tradition: "universal" },
  "6-25": { quote: "Look closely. The beautiful may be small.", ref: "Immanuel Kant", tradition: "universal" },
  "6-26": { quote: "Every moment is a fresh beginning.", ref: "T.S. Eliot", tradition: "universal" },
  "6-27": { quote: "One touch of nature makes the whole world kin.", ref: "Shakespeare", tradition: "universal" },
  "6-28": { quote: "You are the sky. Everything else is just the weather.", ref: "Pema Chödrön", tradition: "universal" },
  "6-29": { quote: "In all things of nature there is something of the marvelous.", ref: "Aristotle", tradition: "universal" },
  "6-30": { quote: "Let us meet each other with a smile, when it is difficult to smile.", ref: "Mother Teresa", tradition: "universal" },
  // ── JULY ─────────────────────────────────────────────────────────────────
  "7-1": { quote: "It's kind of fun to do the impossible.", ref: "Walt Disney", tradition: "universal" },
  "7-2": { quote: "Let your light shine. Shine within you so that it can shine on someone else.", ref: "Oprah Winfrey", tradition: "universal" },
  "7-3": { quote: "You have to be burning with an idea or a problem that you want to make right.", ref: "Steve Jobs", tradition: "universal" },
  "7-4": { quote: "For to be free is to live in a way that respects and enhances the freedom of others.", ref: "Nelson Mandela", tradition: "universal" },
  "7-5": { quote: "You were born with wings, why prefer to crawl through life?", ref: "Rumi", tradition: "universal" },
  "7-6": { quote: "All our dreams can come true, if we have the courage to pursue them.", ref: "Walt Disney", tradition: "universal" },
  "7-7": { quote: "A little nonsense now and then is relished by the wisest men.", ref: "Roald Dahl", tradition: "universal" },
  "7-8": { quote: "To me the sea is a continual miracle.", ref: "Walt Whitman", tradition: "universal" },
  "7-9": { quote: "The more you praise and celebrate your life, the more there is in life to celebrate.", ref: "Oprah Winfrey", tradition: "universal" },
  "7-10": { quote: "You can't calm the storm, so stop trying. What you can do is calm yourself.", ref: "Timber Hawkeye", tradition: "universal" },
  "7-11": { quote: "The butterfly counts not months but moments, and has time enough.", ref: "Tagore", tradition: "universal" },
  "7-12": { quote: "Rest when you're weary. Refresh and renew yourself.", ref: "Ralph Marston", tradition: "universal" },
  "7-13": { quote: "Life is either a daring adventure or nothing at all.", ref: "Helen Keller", tradition: "universal" },
  "7-14": { quote: "To the mind that is still, the whole universe surrenders.", ref: "Lao Tzu", tradition: "universal" },
  "7-15": { quote: "Through humor, you can soften some of the worst blows that life delivers.", ref: "Bill Cosby", tradition: "universal" },
  "7-16": { quote: "Happiness is not something ready made. It comes from your own actions.", ref: "Dalai Lama", tradition: "universal" },
  "7-17": { quote: "The things that make me different are the things that make me.", ref: "Winnie the Pooh (A.A. Milne)", tradition: "universal" },
  "7-18": { quote: "Study nature, love nature, stay close to nature. It will never fail you.", ref: "Frank Lloyd Wright", tradition: "universal" },
  "7-19": { quote: "If I have seen further, it is by standing on the shoulders of giants.", ref: "Isaac Newton", tradition: "universal" },
  "7-20": { quote: "Build your own dreams, or someone else will hire you to build theirs.", ref: "Farrah Gray", tradition: "universal" },
  "7-21": { quote: "Imagination is the beginning of creation.", ref: "George Bernard Shaw", tradition: "universal" },
  "7-22": { quote: "The trees that are slow to grow bear the best fruit.", ref: "Moliere", tradition: "universal" },
  "7-23": { quote: "Turn your face to the sun and the shadows fall behind you.", ref: "Maori Proverb", tradition: "universal" },
  "7-24": { quote: "If you want to go fast, go alone. If you want to go far, go together.", ref: "African Proverb", tradition: "universal" },
  "7-25": { quote: "You always pass failure on the way to success.", ref: "Mickey Rooney", tradition: "universal" },
  "7-26": { quote: "When life gives you lemons, make lemonade.", ref: "Elbert Hubbard", tradition: "universal" },
  "7-27": { quote: "Don't let your dreams be dreams.", ref: "Jack Johnson", tradition: "universal" },
  "7-28": { quote: "Look up at the stars and not down at your feet.", ref: "Stephen Hawking", tradition: "universal" },
  "7-29": { quote: "Go with the flow.", ref: "Lao Tzu", tradition: "universal" },
  "7-30": { quote: "There is light in this world, a healing spirit more powerful than any darkness.", ref: "Mother Teresa", tradition: "universal" },
  "7-31": { quote: "We don't remember days; we remember moments.", ref: "Cesare Pavese", tradition: "universal" },
  // ── AUGUST ───────────────────────────────────────────────────────────────
  "8-1": { quote: "Adventure is out there!", ref: "Disney's Up", tradition: "universal" },
  "8-2": { quote: "Education is not the filling of a pail, but the lighting of a fire.", ref: "W.B. Yeats", tradition: "universal" },
  "8-3": { quote: "A reader lives a thousand lives before he dies.", ref: "George R.R. Martin", tradition: "universal" },
  "8-4": { quote: "It is the supreme art of the teacher to awaken joy in creative expression.", ref: "Einstein", tradition: "universal" },
  "8-5": { quote: "The beautiful thing about learning is that no one can take it away from you.", ref: "B.B. King", tradition: "universal" },
  "8-6": { quote: "The only impossible journey is the one you never begin.", ref: "Tony Robbins", tradition: "universal" },
  "8-7": { quote: "The world is but a canvas to our imagination.", ref: "Thoreau", tradition: "universal" },
  "8-8": { quote: "Measure your life in love.", ref: "Jonathan Larson", tradition: "universal" },
  "8-9": { quote: "Summer will end soon enough, and childhood as well.", ref: "George R.R. Martin", tradition: "universal" },
  "8-10": { quote: "Keep your face to the sunshine and you cannot see a shadow.", ref: "Helen Keller", tradition: "universal" },
  "8-11": { quote: "Eat food, not too much, mostly plants.", ref: "Michael Pollan", tradition: "universal" },
  "8-12": { quote: "Growth is the only evidence of life.", ref: "John Henry Newman", tradition: "universal" },
  "8-13": { quote: "The universe is under no obligation to make sense to you.", ref: "Neil deGrasse Tyson", tradition: "universal" },
  "8-14": { quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", ref: "Benjamin Franklin", tradition: "universal" },
  "8-15": { quote: "Almost everything will work again if you unplug it.", ref: "Anne Lamott", tradition: "universal" },
  "8-16": { quote: "There is no charm equal to tenderness of heart.", ref: "Jane Austen", tradition: "universal" },
  "8-17": { quote: "Be present in all things and thankful for all things.", ref: "Maya Angelou", tradition: "universal" },
  "8-18": { quote: "Colors, like features, follow the changes of the emotions.", ref: "Picasso", tradition: "universal" },
  "8-19": { quote: "Autumn is a second spring when every leaf is a flower.", ref: "Albert Camus", tradition: "universal" },
  "8-20": { quote: "To every thing there is a season, and a time to every purpose under the heaven.", ref: "Ecclesiastes 3:1", tradition: "universal" },
  "8-21": { quote: "Every leaf speaks bliss to me, fluttering from the autumn tree.", ref: "Emily Bronte", tradition: "universal" },
  "8-22": { quote: "From a little spark may burst a mighty flame.", ref: "Dante Alighieri", tradition: "universal" },
  "8-23": { quote: "The most common form of despair is not being who you are.", ref: "Kierkegaard", tradition: "universal" },
  "8-24": { quote: "The bee labors for others, not for itself.", ref: "St. John Chrysostom", tradition: "universal" },
  "8-25": { quote: "Leap and the net will appear.", ref: "John Burroughs", tradition: "universal" },
  "8-26": { quote: "Creativity is connecting things.", ref: "Steve Jobs", tradition: "universal" },
  "8-27": { quote: "A friend is someone who gives you total freedom to be yourself.", ref: "Jim Morrison", tradition: "universal" },
  "8-28": { quote: "Logic will get you from A to B. Imagination will take you everywhere.", ref: "Albert Einstein", tradition: "universal" },
  "8-29": { quote: "A good friend is a connection to life, a tie to the past, a road to the future.", ref: "Lois Wyse", tradition: "universal" },
  "8-30": { quote: "What we learn with pleasure we never forget.", ref: "Alfred Mercier", tradition: "universal" },
  "8-31": { quote: "What lies within you is far greater than what lies before or behind you.", ref: "Emerson", tradition: "universal" },
  // ── SEPTEMBER ────────────────────────────────────────────────────────────
  "9-1": { quote: "Life is change. Growth is optional. Choose wisely.", ref: "Karen Kaiser Clark", tradition: "universal" },
  "9-2": { quote: "Notice the small things. The rewards are inversely proportional.", ref: "Liz Vassey", tradition: "universal" },
  "9-3": { quote: "One must maintain a little bit of summer, even in the middle of winter.", ref: "Henry David Thoreau", tradition: "universal" },
  "9-4": { quote: "You have to be brave with your life so that others can be brave with theirs.", ref: "Katherine Center", tradition: "universal" },
  "9-5": { quote: "A warm smile is the universal language of kindness.", ref: "William Arthur Ward", tradition: "universal" },
  "9-6": { quote: "Writing is the painting of the voice.", ref: "Voltaire", tradition: "universal" },
  "9-7": { quote: "By failing to prepare, you are preparing to fail.", ref: "Benjamin Franklin", tradition: "universal" },
  "9-8": { quote: "To see a world in a grain of sand, hold infinity in the palm of your hand.", ref: "William Blake", tradition: "universal" },
  "9-9": { quote: "Let food be thy medicine and medicine be thy food.", ref: "Hippocrates", tradition: "universal" },
  "9-10": { quote: "Nature always wears the colors of the spirit.", ref: "Emerson", tradition: "universal" },
  "9-11": { quote: "The bravest are those who have the clearest vision of what is before them.", ref: "Thucydides", tradition: "universal" },
  "9-12": { quote: "You are never too old to set another goal or dream a new dream.", ref: "C.S. Lewis", tradition: "universal" },
  "9-13": { quote: "Knowledge speaks, but wisdom listens.", ref: "Jimi Hendrix", tradition: "universal" },
  "9-14": { quote: "Obstacles are those frightful things you see when you take your eyes off your goal.", ref: "Henry Ford", tradition: "universal" },
  "9-15": { quote: "You'll never find a rainbow if you're looking down.", ref: "Charlie Chaplin", tradition: "universal" },
  "9-16": { quote: "No two leaves are alike, and yet there is no antagonism between them.", ref: "Gandhi", tradition: "universal" },
  "9-17": { quote: "The only way to have a friend is to be one.", ref: "Ralph Waldo Emerson", tradition: "universal" },
  "9-18": { quote: "We are all just walking each other home.", ref: "Ram Dass", tradition: "universal" },
  "9-19": { quote: "Silence is the sleep that nourishes wisdom.", ref: "Francis Bacon", tradition: "universal" },
  "9-20": { quote: "What you do makes a difference, and you have to decide what kind of difference you want to make.", ref: "Jane Goodall", tradition: "universal" },
  "9-21": { quote: "Shoot for the moon. Even if you miss, you'll land among the stars.", ref: "Norman Vincent Peale", tradition: "universal" },
  "9-22": { quote: "The more you praise and celebrate your life, the more there is to celebrate.", ref: "Oprah Winfrey", tradition: "universal" },
  "9-23": { quote: "Autumn is a second spring when every leaf is a flower.", ref: "Albert Camus", tradition: "universal" },
  "9-24": { quote: "Within you right now is the power to do things you never dreamed possible.", ref: "Maxwell Maltz", tradition: "universal" },
  "9-25": { quote: "Imagination is more important than knowledge.", ref: "Einstein", tradition: "universal" },
  "9-26": { quote: "We make a living by what we get. We make a life by what we give.", ref: "Winston Churchill", tradition: "universal" },
  "9-27": { quote: "You have to believe in yourself when no one else does — that makes you a winner.", ref: "Venus Williams", tradition: "universal" },
  "9-28": { quote: "The moon does not fight. It does not worry. It simply shines and is beautiful.", ref: "Tao Te Ching", tradition: "universal" },
  "9-29": { quote: "Laughter is an instant vacation.", ref: "Milton Berle", tradition: "universal" },
  "9-30": { quote: "Piglet noticed that even though he had a very small heart, it could hold a rather large amount of gratitude.", ref: "A.A. Milne", tradition: "universal" },
  // ── OCTOBER ──────────────────────────────────────────────────────────────
  "10-1": { quote: "October is the fallen leaf, but it is also a wider sky.", ref: "Hal Borland", tradition: "universal" },
  "10-2": { quote: "Play is the highest form of research.", ref: "Einstein", tradition: "universal" },
  "10-3": { quote: "One of the very nicest things about life is the way we must regularly stop and eat.", ref: "Pavarotti", tradition: "universal" },
  "10-4": { quote: "Until one has loved an animal, a part of one's soul remains unawakened.", ref: "Anatole France", tradition: "universal" },
  "10-5": { quote: "How beautifully leaves grow old. How full of light and color are their last days.", ref: "John Burroughs", tradition: "universal" },
  "10-6": { quote: "One cannot think well, love well, sleep well, if one has not dined well.", ref: "Virginia Woolf", tradition: "universal" },
  "10-7": { quote: "There is nothing like staying at home for real comfort.", ref: "Jane Austen", tradition: "universal" },
  "10-8": { quote: "I would rather sit on a pumpkin and have it all to myself, than be crowded on a velvet cushion.", ref: "Thoreau", tradition: "universal" },
  "10-9": { quote: "Delicious autumn! My very soul is wedded to it.", ref: "George Eliot", tradition: "universal" },
  "10-10": { quote: "Beauty is not in the face. Beauty is a light in the heart.", ref: "Kahlil Gibran", tradition: "universal" },
  "10-11": { quote: "There is no such thing as bad weather, only inappropriate clothing.", ref: "Alfred Wainwright", tradition: "universal" },
  "10-12": { quote: "Art enables us to find ourselves and lose ourselves at the same time.", ref: "Thomas Merton", tradition: "universal" },
  "10-13": { quote: "Not I, nor anyone else can travel that road for you. You must travel it yourself.", ref: "Walt Whitman", tradition: "universal" },
  "10-14": { quote: "The creation of a thousand forests is in one acorn.", ref: "Ralph Waldo Emerson", tradition: "universal" },
  "10-15": { quote: "A smile is a curve that sets everything straight.", ref: "Phyllis Diller", tradition: "universal" },
  "10-16": { quote: "Life starts all over again when it gets crisp in the fall.", ref: "F. Scott Fitzgerald", tradition: "universal" },
  "10-17": { quote: "Good apple pies are a considerable part of our domestic happiness.", ref: "Jane Austen", tradition: "universal" },
  "10-18": { quote: "In every real person a child is hidden that wants to play.", ref: "Nietzsche", tradition: "universal" },
  "10-19": { quote: "The details are not the details. They make the design.", ref: "Charles Eames", tradition: "universal" },
  "10-20": { quote: "Every artist dips his brush in his own soul and paints his own nature into his pictures.", ref: "Henry Ward Beecher", tradition: "universal" },
  "10-21": { quote: "You're off to great places! Today is your day! Your mountain is waiting, so get on your way!", ref: "Dr. Seuss", tradition: "universal" },
  "10-22": { quote: "Courage is the quiet voice at the end of the day saying I will try again tomorrow.", ref: "Mary Anne Radmacher", tradition: "universal" },
  "10-23": { quote: "It is better to light one small candle than to curse the darkness.", ref: "Eleanor Roosevelt", tradition: "universal" },
  "10-24": { quote: "The purpose of art is washing the dust of daily life off our souls.", ref: "Picasso", tradition: "universal" },
  "10-25": { quote: "Laughter is the closest distance between two people.", ref: "Victor Borge", tradition: "universal" },
  "10-26": { quote: "Life is a rainbow which also includes black.", ref: "Yevgeny Yevtushenko", tradition: "universal" },
  "10-27": { quote: "Variety is the spice of life.", ref: "William Cowper", tradition: "universal" },
  "10-28": { quote: "Nothing in life is to be feared, it is only to be understood.", ref: "Marie Curie", tradition: "universal" },
  "10-29": { quote: "There is something incredibly nostalgic and special about autumn.", ref: "Albert Camus", tradition: "universal" },
  "10-30": { quote: "The sight of the stars always makes me dream.", ref: "Van Gogh", tradition: "universal" },
  "10-31": { quote: "It is the sweet, simple things of life which are the real ones after all.", ref: "Laura Ingalls Wilder", tradition: "universal" },
  // ── NOVEMBER ─────────────────────────────────────────────────────────────
  "11-1": { quote: "We are all leaves of one tree. We are all waves of one sea.", ref: "Thich Nhat Hanh", tradition: "universal" },
  "11-2": { quote: "Gratitude is when memory is stored in the heart, not in the mind.", ref: "Lionel Hampton", tradition: "universal" },
  "11-3": { quote: "There are only two ways to live your life — as though nothing is a miracle, or as though everything is.", ref: "Einstein", tradition: "universal" },
  "11-4": { quote: "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.", ref: "Melody Beattie", tradition: "universal" },
  "11-5": { quote: "For every minute spent organizing, an hour is earned.", ref: "Benjamin Franklin", tradition: "universal" },
  "11-6": { quote: "There is no small act of kindness. Every compassionate act makes large the world.", ref: "Mary Anne Radmacher", tradition: "universal" },
  "11-7": { quote: "The secret of happiness is not in doing what one likes, but in liking what one does.", ref: "James M. Barrie", tradition: "universal" },
  "11-8": { quote: "It is better to light one small candle than to curse the darkness.", ref: "Eleanor Roosevelt", tradition: "universal" },
  "11-9": { quote: "Sometimes you will never know the value of a moment until it becomes a memory.", ref: "Dr. Seuss", tradition: "universal" },
  "11-10": { quote: "A candle loses nothing by lighting another candle.", ref: "James Keller", tradition: "universal" },
  "11-11": { quote: "This nation will remain the land of the free only so long as it is the home of the brave.", ref: "Elmer Davis", tradition: "universal" },
  "11-12": { quote: "Even the darkest night will end and the sun will rise.", ref: "Victor Hugo", tradition: "universal" },
  "11-13": { quote: "Cooking is like love. It should be entered into with abandon or not at all.", ref: "Harriet Van Horne", tradition: "universal" },
  "11-14": { quote: "A place for everything, everything in its place.", ref: "Benjamin Franklin", tradition: "universal" },
  "11-15": { quote: "Family means no one gets left behind or forgotten.", ref: "David Ogden Stiers", tradition: "universal" },
  "11-16": { quote: "Gratitude is not only the greatest of virtues, but the parent of all others.", ref: "Cicero", tradition: "universal" },
  "11-17": { quote: "Home is not a place — it's a feeling.", ref: "Cecelia Ahern", tradition: "universal" },
  "11-18": { quote: "The world needs dreamers and the world needs doers. But above all, the world needs dreamers who do.", ref: "Sarah Ban Breathnach", tradition: "universal" },
  "11-19": { quote: "Act as if what you do makes a difference. It does.", ref: "William James", tradition: "universal" },
  "11-20": { quote: "Sharing food with another human being is an intimate act that should not be indulged in lightly.", ref: "M.F.K. Fisher", tradition: "universal" },
  "11-21": { quote: "If you can make someone laugh, you can make them do anything.", ref: "Marilyn Monroe", tradition: "universal" },
  "11-22": { quote: "If the only prayer you ever say is thank you, it will be enough.", ref: "Meister Eckhart", tradition: "universal" },
  "11-23": { quote: "The journey of a thousand miles begins with a single step.", ref: "Lao Tzu", tradition: "universal" },
  "11-24": { quote: "In the end, it's not the years in your life that count. It's the life in your years.", ref: "Abraham Lincoln", tradition: "universal" },
  "11-25": { quote: "Enough is a feast.", ref: "Buddhist Proverb", tradition: "universal" },
  "11-26": { quote: "Not what we have but what we enjoy constitutes our abundance.", ref: "Epicurus", tradition: "universal" },
  "11-27": { quote: "No one has ever become poor by giving.", ref: "Anne Frank", tradition: "universal" },
  "11-28": { quote: "Rest is not idleness. To lie under trees on a summer's day is by no means a waste of time.", ref: "John Lubbock", tradition: "universal" },
  "11-29": { quote: "Patience, persistence and perspiration make an unbeatable combination for success.", ref: "Napoleon Hill", tradition: "universal" },
  "11-30": { quote: "Reflect upon your present blessings, of which every person has many.", ref: "Charles Dickens", tradition: "universal" },
  // ── DECEMBER ─────────────────────────────────────────────────────────────
  "12-1": { quote: "To give without any reward, or any notice, has a special quality of its own.", ref: "Anne Morrow Lindbergh", tradition: "universal" },
  "12-2": { quote: "What good is the warmth of summer, without the cold of winter to give it sweetness.", ref: "John Steinbeck", tradition: "universal" },
  "12-3": { quote: "We make a living by what we get. We make a life by what we give.", ref: "Winston Churchill", tradition: "universal" },
  "12-4": { quote: "A candle loses nothing by lighting another candle.", ref: "James Keller", tradition: "universal" },
  "12-5": { quote: "A letter always seemed to me like immortality.", ref: "Emily Dickinson", tradition: "universal" },
  "12-6": { quote: "Unexpected kindness is the most powerful, least costly, and most underrated agent of human change.", ref: "Bob Kerrey", tradition: "universal" },
  "12-7": { quote: "Music gives a soul to the universe, wings to the mind, flight to the imagination.", ref: "Plato", tradition: "universal" },
  "12-8": { quote: "Kindness is the language which the deaf can hear and the blind can see.", ref: "Mark Twain", tradition: "universal" },
  "12-9": { quote: "Two things are infinite: the universe and human kindness.", ref: "Einstein (adapted)", tradition: "universal" },
  "12-10": { quote: "Family is not an important thing. It's everything.", ref: "Michael J. Fox", tradition: "universal" },
  "12-11": { quote: "Loneliness is the poverty of self; solitude is richness of self.", ref: "May Sarton", tradition: "universal" },
  "12-12": { quote: "Memories are the treasures that we keep locked deep within the storehouse of our souls.", ref: "Becky Aligada", tradition: "universal" },
  "12-13": { quote: "Yesterday is history. Tomorrow is a mystery. Today is a gift.", ref: "Alice Morse Earle", tradition: "universal" },
  "12-14": { quote: "The manner of giving is worth more than the gift.", ref: "Pierre Corneille", tradition: "universal" },
  "12-15": { quote: "A little thought and a little kindness are often worth more than a great deal of money.", ref: "John Ruskin", tradition: "universal" },
  "12-16": { quote: "Peace comes from within. Do not seek it without.", ref: "Buddha", tradition: "universal" },
  "12-17": { quote: "The sight of the stars always makes me dream.", ref: "Van Gogh", tradition: "universal" },
  "12-18": { quote: "How far that little candle throws his beams! So shines a good deed in a weary world.", ref: "Shakespeare", tradition: "universal" },
  "12-19": { quote: "You have to find what sparks a light in you so that you can illuminate the world.", ref: "Oprah Winfrey", tradition: "universal" },
  "12-20": { quote: "Wherever there is a human being, there is an opportunity for a kindness.", ref: "Seneca", tradition: "universal" },
  "12-21": { quote: "The best gift is a portion of yourself.", ref: "Emerson", tradition: "universal" },
  "12-22": { quote: "The universe is circular. Come back to the beginning.", ref: "Native American Saying", tradition: "universal" },
  "12-23": { quote: "The best is yet to come.", ref: "Frank Sinatra", tradition: "universal" },
  "12-24": { quote: "There are more things in heaven and earth than are dreamt of in your philosophy.", ref: "Shakespeare", tradition: "universal" },
  "12-25": { quote: "The best and most beautiful things cannot be seen or touched — they must be felt with the heart.", ref: "Helen Keller", tradition: "universal" },
  "12-26": { quote: "When you share your joy, it doubles. When you share your sorrow, it halves.", ref: "Swedish Proverb", tradition: "universal" },
  "12-27": { quote: "Peace is not the absence of conflict, but the presence of creative alternatives.", ref: "Dorothy Thompson", tradition: "universal" },
  "12-28": { quote: "You are never too old to set another goal or to dream a new dream.", ref: "C.S. Lewis", tradition: "universal" },
  "12-29": { quote: "There is no greater agony than bearing an untold story inside you.", ref: "Maya Angelou", tradition: "universal" },
  "12-30": { quote: "Joy is the simplest form of gratitude.", ref: "Karl Barth", tradition: "universal" },
  "12-31": { quote: "Every new beginning comes from some other beginning's end.", ref: "Seneca", tradition: "universal" },
};
