import { AffirmationMap } from '../../types';

// Torah, Talmud, Jewish wisdom quotes — 365 entries, one per day
// Sources: Torah (Genesis-Deuteronomy), Psalms, Proverbs, Talmud, Pirkei Avot, Mishnah

export const jewishAffirmations: AffirmationMap = {
  // ===== JANUARY (Winter, Tu BiShvat themes) =====
  "1-1": { quote: "The world was created for you — take care of it with love.", ref: "Talmud, Sanhedrin 37a", tradition: "jewish" },
  "1-2": { quote: "In the beginning, God created the heavens and the earth.", ref: "Gen 1:1", tradition: "jewish" },
  "1-3": { quote: "God saw everything He had made, and it was very good.", ref: "Gen 1:31", tradition: "jewish" },
  "1-4": { quote: "The Lord is my shepherd; I have everything I need.", ref: "Ps 23:1", tradition: "jewish" },
  "1-5": { quote: "Trust in God with all your heart.", ref: "Prov 3:5", tradition: "jewish" },
  "1-6": { quote: "God made the sun to warm the day and the moon to light the night.", ref: "Gen 1:16", tradition: "jewish" },
  "1-7": { quote: "On the seventh day, God rested. Rest is a gift.", ref: "Gen 2:2", tradition: "jewish" },
  "1-8": { quote: "Love your neighbor as yourself.", ref: "Lev 19:18", tradition: "jewish" },
  "1-9": { quote: "A kind word is like a tree of life.", ref: "Prov 15:4", tradition: "jewish" },
  "1-10": { quote: "God made every person special and unique.", ref: "Talmud, Sanhedrin 37a", tradition: "jewish" },
  "1-11": { quote: "It is not up to you to finish the work, but you must not stop trying.", ref: "Pirkei Avot 2:16", tradition: "jewish" },
  "1-12": { quote: "Be strong and brave! God is with you wherever you go.", ref: "Josh 1:9", tradition: "jewish" },
  "1-13": { quote: "A good friend is a wonderful treasure.", ref: "Pirkei Avot 2:9", tradition: "jewish" },
  "1-14": { quote: "God counts the stars and calls each one by name.", ref: "Ps 147:4", tradition: "jewish" },
  "1-15": { quote: "Trees are our friends — they give us shade, fruit, and fresh air.", ref: "Deut 20:19", tradition: "jewish" },
  "1-16": { quote: "When you eat fruit from a tree, thank God for the tree.", ref: "Deut 8:10", tradition: "jewish" },
  "1-17": { quote: "Plant a tree today, even if the world ends tomorrow.", ref: "Talmud", tradition: "jewish" },
  "1-18": { quote: "A person is like a tree — strong roots help us grow tall.", ref: "Ps 1:3", tradition: "jewish" },
  "1-19": { quote: "God waters the mountains and fills the earth with good things.", ref: "Ps 104:13", tradition: "jewish" },
  "1-20": { quote: "The earth is the Lord's, and everything in it.", ref: "Ps 24:1", tradition: "jewish" },
  "1-21": { quote: "Whoever saves one life, it is as if they saved the whole world.", ref: "Talmud, Sanhedrin 37a", tradition: "jewish" },
  "1-22": { quote: "God gives wisdom, and from His mouth comes understanding.", ref: "Prov 2:6", tradition: "jewish" },
  "1-23": { quote: "Happy are those who find wisdom and understanding.", ref: "Prov 3:13", tradition: "jewish" },
  "1-24": { quote: "Even a small candle can push away a lot of darkness.", ref: "Jewish wisdom", tradition: "jewish" },
  "1-25": { quote: "Thank God for the rain that helps flowers grow.", ref: "Deut 11:14", tradition: "jewish" },
  "1-26": { quote: "God planted a beautiful garden for all to enjoy.", ref: "Gen 2:8", tradition: "jewish" },
  "1-27": { quote: "Every seed you plant is a prayer for the future.", ref: "Jewish wisdom", tradition: "jewish" },
  "1-28": { quote: "God made the animals — each one is wonderful.", ref: "Gen 1:25", tradition: "jewish" },
  "1-29": { quote: "Sing to God a new song! Let the whole earth sing!", ref: "Ps 96:1", tradition: "jewish" },
  "1-30": { quote: "When we share with others, we make the world brighter.", ref: "Prov 11:25", tradition: "jewish" },
  "1-31": { quote: "God loves a cheerful heart.", ref: "Prov 17:22", tradition: "jewish" },

  // ===== FEBRUARY (Winter, Tu BiShvat, kindness) =====
  "2-1": { quote: "The fruit of a tree is sweet — enjoy the gifts of nature.", ref: "Prov 27:18", tradition: "jewish" },
  "2-2": { quote: "Let us go out to the fields and see the blossoms.", ref: "Song 7:12", tradition: "jewish" },
  "2-3": { quote: "God made winter and summer, each one beautiful.", ref: "Ps 74:17", tradition: "jewish" },
  "2-4": { quote: "Who is wise? The one who learns from every person.", ref: "Pirkei Avot 4:1", tradition: "jewish" },
  "2-5": { quote: "A soft answer turns away anger.", ref: "Prov 15:1", tradition: "jewish" },
  "2-6": { quote: "God dresses the fields in beauty — even in winter.", ref: "Ps 65:13", tradition: "jewish" },
  "2-7": { quote: "It is a tree of life for those who hold on to it.", ref: "Prov 3:18", tradition: "jewish" },
  "2-8": { quote: "Give thanks to the Lord, for He is good.", ref: "Ps 107:1", tradition: "jewish" },
  "2-9": { quote: "Say something kind today — your words can heal.", ref: "Prov 12:18", tradition: "jewish" },
  "2-10": { quote: "Shabbat is a special day to rest and be thankful.", ref: "Ex 20:8", tradition: "jewish" },
  "2-11": { quote: "God blesses those who help the poor.", ref: "Prov 19:17", tradition: "jewish" },
  "2-12": { quote: "Doing a mitzvah makes the whole world better.", ref: "Jewish wisdom", tradition: "jewish" },
  "2-13": { quote: "God made you with love — you are wonderfully made.", ref: "Ps 139:14", tradition: "jewish" },
  "2-14": { quote: "Love is as strong as the stars in the sky.", ref: "Song 8:6", tradition: "jewish" },
  "2-15": { quote: "On Tu BiShvat, we celebrate the birthday of the trees!", ref: "Mishnah, Rosh Hashanah 1:1", tradition: "jewish" },
  "2-16": { quote: "God made fruit trees to share their sweetness with us.", ref: "Gen 1:29", tradition: "jewish" },
  "2-17": { quote: "A righteous person is like a tree planted by streams of water.", ref: "Ps 1:3", tradition: "jewish" },
  "2-18": { quote: "Take care of the earth — it is God's gift to us.", ref: "Gen 2:15", tradition: "jewish" },
  "2-19": { quote: "You shall not destroy fruit trees, for they give life.", ref: "Deut 20:19", tradition: "jewish" },
  "2-20": { quote: "Thank God for almonds, olives, and figs.", ref: "Deut 8:8", tradition: "jewish" },
  "2-21": { quote: "A happy heart is good medicine.", ref: "Prov 17:22", tradition: "jewish" },
  "2-22": { quote: "God's love is as wide as the sky.", ref: "Ps 36:5", tradition: "jewish" },
  "2-23": { quote: "Be kind to animals — God made them for us to care for.", ref: "Prov 12:10", tradition: "jewish" },
  "2-24": { quote: "The Lord is close to everyone who calls on Him.", ref: "Ps 145:18", tradition: "jewish" },
  "2-25": { quote: "When you help a friend, you help yourself too.", ref: "Talmud, Shabbat 31a", tradition: "jewish" },
  "2-26": { quote: "Teach a child the right way — they will remember it always.", ref: "Prov 22:6", tradition: "jewish" },
  "2-27": { quote: "God's kindness lasts forever and ever.", ref: "Ps 136:1", tradition: "jewish" },
  "2-28": { quote: "Every creature that breathes praises God.", ref: "Ps 150:6", tradition: "jewish" },

  // ===== MARCH (Purim, early spring, courage) =====
  "3-1": { quote: "Be brave like Queen Esther — speak up for what is right.", ref: "Esther 4:14", tradition: "jewish" },
  "3-2": { quote: "God turns our sadness into dancing!", ref: "Ps 30:11", tradition: "jewish" },
  "3-3": { quote: "Who knows? Maybe you were born for such a time as this.", ref: "Esther 4:14", tradition: "jewish" },
  "3-4": { quote: "On Purim, we share treats with friends and neighbors.", ref: "Esther 9:22", tradition: "jewish" },
  "3-5": { quote: "When we give to others, our hearts grow bigger.", ref: "Prov 11:25", tradition: "jewish" },
  "3-6": { quote: "Even the smallest person can make a big difference.", ref: "Jewish wisdom", tradition: "jewish" },
  "3-7": { quote: "Helping someone in need is one of the greatest mitzvahs.", ref: "Talmud, Sukkah 49b", tradition: "jewish" },
  "3-8": { quote: "God fills the earth with new life every spring.", ref: "Ps 104:30", tradition: "jewish" },
  "3-9": { quote: "Queen Esther was brave — you can be brave too.", ref: "Esther 7:3", tradition: "jewish" },
  "3-10": { quote: "Joy is a mitzvah! Be happy today.", ref: "Deut 16:14", tradition: "jewish" },
  "3-11": { quote: "Good friends stick together, no matter what.", ref: "Prov 17:17", tradition: "jewish" },
  "3-12": { quote: "God makes everything beautiful in its own time.", ref: "Eccl 3:11", tradition: "jewish" },
  "3-13": { quote: "For everything there is a season — a time for every purpose.", ref: "Eccl 3:1", tradition: "jewish" },
  "3-14": { quote: "Spring is coming! God renews the face of the earth.", ref: "Ps 104:30", tradition: "jewish" },
  "3-15": { quote: "Courage means doing the right thing, even when you are scared.", ref: "Jewish wisdom", tradition: "jewish" },
  "3-16": { quote: "God keeps His promises — the seasons always return.", ref: "Gen 8:22", tradition: "jewish" },
  "3-17": { quote: "Sharing food with others brings joy to everyone.", ref: "Esther 9:22", tradition: "jewish" },
  "3-18": { quote: "Let your light shine for all to see.", ref: "Jewish wisdom", tradition: "jewish" },
  "3-19": { quote: "God hears your prayers, even the quiet ones.", ref: "Ps 65:2", tradition: "jewish" },
  "3-20": { quote: "A friend loves at all times.", ref: "Prov 17:17", tradition: "jewish" },
  "3-21": { quote: "Spring flowers remind us that God keeps the world beautiful.", ref: "Song 2:12", tradition: "jewish" },
  "3-22": { quote: "Stand up for truth and peace.", ref: "Zech 8:16", tradition: "jewish" },
  "3-23": { quote: "There is a time to plant and a time to harvest.", ref: "Eccl 3:2", tradition: "jewish" },
  "3-24": { quote: "God watches over you when you sleep and when you wake.", ref: "Ps 121:8", tradition: "jewish" },
  "3-25": { quote: "Speak the truth to your neighbor.", ref: "Zech 8:16", tradition: "jewish" },
  "3-26": { quote: "Do not be afraid — I am with you, says God.", ref: "Isa 41:10", tradition: "jewish" },
  "3-27": { quote: "God is our helper and our shield.", ref: "Ps 33:20", tradition: "jewish" },
  "3-28": { quote: "A person's kindness makes room for them everywhere.", ref: "Prov 18:16", tradition: "jewish" },
  "3-29": { quote: "God created people to take care of one another.", ref: "Jewish wisdom", tradition: "jewish" },
  "3-30": { quote: "I will sing to God because He has been so good to me.", ref: "Ps 13:6", tradition: "jewish" },
  "3-31": { quote: "Tomorrow is a new day, full of new blessings.", ref: "Lam 3:23", tradition: "jewish" },

  // ===== APRIL (Passover, freedom, gratitude) =====
  "4-1": { quote: "In every generation, we remember that God set us free.", ref: "Passover Haggadah", tradition: "jewish" },
  "4-2": { quote: "God brought us from slavery to freedom with a strong hand.", ref: "Ex 13:14", tradition: "jewish" },
  "4-3": { quote: "Why is this night different from all other nights?", ref: "Passover Haggadah", tradition: "jewish" },
  "4-4": { quote: "God parted the sea so His people could walk through safely.", ref: "Ex 14:21", tradition: "jewish" },
  "4-5": { quote: "Freedom is a gift from God — treasure it.", ref: "Ex 6:6", tradition: "jewish" },
  "4-6": { quote: "At the Seder, we eat matzah and remember our story.", ref: "Ex 12:17", tradition: "jewish" },
  "4-7": { quote: "Moses said, 'Let my people go!'", ref: "Ex 5:1", tradition: "jewish" },
  "4-8": { quote: "God protects those who trust in Him.", ref: "Ps 91:4", tradition: "jewish" },
  "4-9": { quote: "Tell the story of Passover to your children.", ref: "Ex 13:8", tradition: "jewish" },
  "4-10": { quote: "We dip parsley in salt water to remember the tears of our ancestors.", ref: "Passover Haggadah", tradition: "jewish" },
  "4-11": { quote: "Dayenu — it would have been enough! We are thankful for everything.", ref: "Passover Haggadah", tradition: "jewish" },
  "4-12": { quote: "God sees the tears of those who are hurting and comes to help.", ref: "Ex 3:7", tradition: "jewish" },
  "4-13": { quote: "Next year in Jerusalem! We dream of peace.", ref: "Passover Haggadah", tradition: "jewish" },
  "4-14": { quote: "God led His people with a pillar of cloud by day and fire by night.", ref: "Ex 13:21", tradition: "jewish" },
  "4-15": { quote: "Miriam danced and sang when God saved her people.", ref: "Ex 15:20", tradition: "jewish" },
  "4-16": { quote: "Thank God for bread, water, and all the food we eat.", ref: "Deut 8:10", tradition: "jewish" },
  "4-17": { quote: "God opens doors that no one can shut.", ref: "Isa 22:22", tradition: "jewish" },
  "4-18": { quote: "When we help others be free, we become more free too.", ref: "Jewish wisdom", tradition: "jewish" },
  "4-19": { quote: "God heard the cries of His people and remembered them.", ref: "Ex 2:24", tradition: "jewish" },
  "4-20": { quote: "The Lord is my strength and my song.", ref: "Ex 15:2", tradition: "jewish" },
  "4-21": { quote: "Every child who asks a question is learning wisdom.", ref: "Passover Haggadah", tradition: "jewish" },
  "4-22": { quote: "God takes care of the birds — how much more will He take care of you!", ref: "Ps 147:9", tradition: "jewish" },
  "4-23": { quote: "Spring rain brings flowers — God sends blessings in every season.", ref: "Deut 11:14", tradition: "jewish" },
  "4-24": { quote: "Remember the wonders that God has done.", ref: "Ps 105:5", tradition: "jewish" },
  "4-25": { quote: "Teach your children well, and they will grow strong.", ref: "Deut 6:7", tradition: "jewish" },
  "4-26": { quote: "The flowers appear on the earth — spring is here!", ref: "Song 2:12", tradition: "jewish" },
  "4-27": { quote: "Count your blessings, one by one, like counting the Omer.", ref: "Lev 23:15", tradition: "jewish" },
  "4-28": { quote: "God made you to be free and to bring freedom to others.", ref: "Jewish wisdom", tradition: "jewish" },
  "4-29": { quote: "Open your hand to those who need help.", ref: "Deut 15:11", tradition: "jewish" },
  "4-30": { quote: "God holds you in the palm of His hand.", ref: "Isa 49:16", tradition: "jewish" },

  // ===== MAY (Shavuot, Torah, learning, harvest) =====
  "5-1": { quote: "The Torah is a tree of life — hold on to it.", ref: "Prov 3:18", tradition: "jewish" },
  "5-2": { quote: "Learning Torah is the greatest mitzvah of all.", ref: "Talmud, Shabbat 127a", tradition: "jewish" },
  "5-3": { quote: "God gave us the Torah at Mount Sinai as a gift of love.", ref: "Ex 19:5", tradition: "jewish" },
  "5-4": { quote: "Your word is a lamp to my feet and a light to my path.", ref: "Ps 119:105", tradition: "jewish" },
  "5-5": { quote: "Honor your father and your mother.", ref: "Ex 20:12", tradition: "jewish" },
  "5-6": { quote: "The words of Torah are as sweet as honey.", ref: "Ps 19:10", tradition: "jewish" },
  "5-7": { quote: "On Shavuot, we celebrate receiving the Torah.", ref: "Ex 19:1", tradition: "jewish" },
  "5-8": { quote: "Love God with all your heart, all your soul, and all your might.", ref: "Deut 6:5", tradition: "jewish" },
  "5-9": { quote: "God spoke the Ten Commandments, and the whole mountain shook.", ref: "Ex 20:18", tradition: "jewish" },
  "5-10": { quote: "Ruth said, 'Where you go, I will go.' She was loyal and kind.", ref: "Ruth 1:16", tradition: "jewish" },
  "5-11": { quote: "We eat dairy foods on Shavuot — cheesecake is a blessing!", ref: "Shavuot tradition", tradition: "jewish" },
  "5-12": { quote: "A mother's love is one of God's greatest gifts.", ref: "Prov 31:28", tradition: "jewish" },
  "5-13": { quote: "Study, study, study — for it is all within the Torah.", ref: "Pirkei Avot 5:22", tradition: "jewish" },
  "5-14": { quote: "God gave us rules so we can live together in peace.", ref: "Ex 20:1", tradition: "jewish" },
  "5-15": { quote: "The harvest is a time to thank God for food.", ref: "Deut 16:10", tradition: "jewish" },
  "5-16": { quote: "Flowers bloom in the field — God makes the earth beautiful.", ref: "Song 2:12", tradition: "jewish" },
  "5-17": { quote: "Every person has something special to teach you.", ref: "Pirkei Avot 4:1", tradition: "jewish" },
  "5-18": { quote: "Be slow to anger and full of kindness.", ref: "Pirkei Avot 2:10", tradition: "jewish" },
  "5-19": { quote: "God carved the commandments in stone with His own finger.", ref: "Ex 31:18", tradition: "jewish" },
  "5-20": { quote: "The world stands on three things: Torah, prayer, and acts of kindness.", ref: "Pirkei Avot 1:2", tradition: "jewish" },
  "5-21": { quote: "When we learn, our minds grow like gardens.", ref: "Jewish wisdom", tradition: "jewish" },
  "5-22": { quote: "God gives you new blessings every single morning.", ref: "Lam 3:23", tradition: "jewish" },
  "5-23": { quote: "Seek peace and pursue it wherever you go.", ref: "Ps 34:14", tradition: "jewish" },
  "5-24": { quote: "A wise child makes their parents proud.", ref: "Prov 10:1", tradition: "jewish" },
  "5-25": { quote: "The Torah teaches us to love, to share, and to be fair.", ref: "Jewish wisdom", tradition: "jewish" },
  "5-26": { quote: "God set a rainbow in the sky as a promise of love.", ref: "Gen 9:13", tradition: "jewish" },
  "5-27": { quote: "Listen carefully — God speaks in a still, small voice.", ref: "1 Kgs 19:12", tradition: "jewish" },
  "5-28": { quote: "Who is strong? The one who controls their temper.", ref: "Pirkei Avot 4:1", tradition: "jewish" },
  "5-29": { quote: "Joy comes in the morning!", ref: "Ps 30:5", tradition: "jewish" },
  "5-30": { quote: "God made the sun, the moon, and every twinkling star for you.", ref: "Gen 1:16", tradition: "jewish" },
  "5-31": { quote: "Do what is right and good in the sight of God.", ref: "Deut 6:18", tradition: "jewish" },

  // ===== JUNE (Summer, community, family) =====
  "6-1": { quote: "How good it is when families live together in peace.", ref: "Ps 133:1", tradition: "jewish" },
  "6-2": { quote: "Children are a gift from God.", ref: "Ps 127:3", tradition: "jewish" },
  "6-3": { quote: "Let the little children come and learn.", ref: "Jewish wisdom", tradition: "jewish" },
  "6-4": { quote: "A gentle tongue is a tree of life.", ref: "Prov 15:4", tradition: "jewish" },
  "6-5": { quote: "God made the oceans, the rivers, and every drop of rain.", ref: "Ps 95:5", tradition: "jewish" },
  "6-6": { quote: "Shabbat shalom! May your Shabbat be filled with peace.", ref: "Jewish liturgy", tradition: "jewish" },
  "6-7": { quote: "Do not follow the crowd to do wrong — be brave and do right.", ref: "Ex 23:2", tradition: "jewish" },
  "6-8": { quote: "God is like a shade tree on a hot summer day.", ref: "Ps 121:5", tradition: "jewish" },
  "6-9": { quote: "The sun rises and the sun sets — God keeps the world turning.", ref: "Eccl 1:5", tradition: "jewish" },
  "6-10": { quote: "If I am not for myself, who will be? If I am only for myself, what am I?", ref: "Pirkei Avot 1:14", tradition: "jewish" },
  "6-11": { quote: "God gives the sunshine and the rain in their perfect time.", ref: "Deut 11:14", tradition: "jewish" },
  "6-12": { quote: "Share your toys and your snacks — sharing is a mitzvah.", ref: "Jewish wisdom", tradition: "jewish" },
  "6-13": { quote: "Clap your hands and shout for joy!", ref: "Ps 47:1", tradition: "jewish" },
  "6-14": { quote: "A father's teaching is a crown of grace upon your head.", ref: "Prov 1:9", tradition: "jewish" },
  "6-15": { quote: "Walk humbly with your God.", ref: "Mic 6:8", tradition: "jewish" },
  "6-16": { quote: "Abraham and Sarah welcomed every stranger into their tent.", ref: "Gen 18:2", tradition: "jewish" },
  "6-17": { quote: "God loves justice and fairness.", ref: "Ps 33:5", tradition: "jewish" },
  "6-18": { quote: "Be a blessing to everyone you meet today.", ref: "Gen 12:2", tradition: "jewish" },
  "6-19": { quote: "Tzedakah — giving to those in need — makes the world better.", ref: "Deut 15:10", tradition: "jewish" },
  "6-20": { quote: "When you see something beautiful, say a blessing.", ref: "Talmud, Berakhot 58b", tradition: "jewish" },
  "6-21": { quote: "The longest day of the year is a gift — enjoy every minute!", ref: "Jewish wisdom", tradition: "jewish" },
  "6-22": { quote: "God made the world in six days — you can do great things too.", ref: "Gen 2:1", tradition: "jewish" },
  "6-23": { quote: "Who is happy? The one who is thankful for what they have.", ref: "Pirkei Avot 4:1", tradition: "jewish" },
  "6-24": { quote: "Rebecca was kind to the camels — kindness to animals matters.", ref: "Gen 24:19", tradition: "jewish" },
  "6-25": { quote: "Make today count — do one more good deed.", ref: "Jewish wisdom", tradition: "jewish" },
  "6-26": { quote: "God remembered Noah and all the animals in the ark.", ref: "Gen 8:1", tradition: "jewish" },
  "6-27": { quote: "Like a garden needs water, your heart needs kindness.", ref: "Jewish wisdom", tradition: "jewish" },
  "6-28": { quote: "May God bless you and keep you safe.", ref: "Num 6:24", tradition: "jewish" },
  "6-29": { quote: "May God's face shine upon you and be kind to you.", ref: "Num 6:25", tradition: "jewish" },
  "6-30": { quote: "May God look upon you with favor and give you peace.", ref: "Num 6:26", tradition: "jewish" },

  // ===== JULY (Summer, creation, wonder) =====
  "7-1": { quote: "Look at the sky — God's handiwork is amazing.", ref: "Ps 19:1", tradition: "jewish" },
  "7-2": { quote: "God made the great sea creatures and all the fish of the sea.", ref: "Gen 1:21", tradition: "jewish" },
  "7-3": { quote: "Let freedom ring! God wants all people to be free.", ref: "Lev 25:10", tradition: "jewish" },
  "7-4": { quote: "Proclaim liberty throughout the land!", ref: "Lev 25:10", tradition: "jewish" },
  "7-5": { quote: "God stretched out the heavens like a curtain.", ref: "Ps 104:2", tradition: "jewish" },
  "7-6": { quote: "Drink water and thank God for every sip.", ref: "Talmud, Berakhot 44a", tradition: "jewish" },
  "7-7": { quote: "God made each day — let us be glad in it.", ref: "Ps 118:24", tradition: "jewish" },
  "7-8": { quote: "Even the birds of the sky praise God with their songs.", ref: "Ps 104:12", tradition: "jewish" },
  "7-9": { quote: "Joseph forgave his brothers and showed them love.", ref: "Gen 50:21", tradition: "jewish" },
  "7-10": { quote: "Peace, peace to those who are near and to those who are far.", ref: "Isa 57:19", tradition: "jewish" },
  "7-11": { quote: "God is our rock and our safe place.", ref: "Ps 18:2", tradition: "jewish" },
  "7-12": { quote: "Do not be afraid of the dark — God is there too.", ref: "Ps 139:12", tradition: "jewish" },
  "7-13": { quote: "The mountains sing for joy before God.", ref: "Ps 98:8", tradition: "jewish" },
  "7-14": { quote: "God's love is higher than the highest mountain.", ref: "Ps 103:11", tradition: "jewish" },
  "7-15": { quote: "A mitzvah done with joy is worth even more.", ref: "Jewish wisdom", tradition: "jewish" },
  "7-16": { quote: "Jacob dreamed of a ladder reaching up to heaven.", ref: "Gen 28:12", tradition: "jewish" },
  "7-17": { quote: "Every good deed is a step on a ladder to heaven.", ref: "Jewish wisdom", tradition: "jewish" },
  "7-18": { quote: "The Torah is more precious than gold and silver.", ref: "Ps 19:10", tradition: "jewish" },
  "7-19": { quote: "God made the whale and the tiny ant — He loves them all.", ref: "Ps 104:25", tradition: "jewish" },
  "7-20": { quote: "Your body is strong and healthy — thank God for it.", ref: "Jewish morning prayer", tradition: "jewish" },
  "7-21": { quote: "Think good thoughts and good things will come.", ref: "Jewish wisdom", tradition: "jewish" },
  "7-22": { quote: "I will lie down and sleep in peace, for God watches over me.", ref: "Ps 4:8", tradition: "jewish" },
  "7-23": { quote: "The whole world is full of God's glory.", ref: "Isa 6:3", tradition: "jewish" },
  "7-24": { quote: "God gives strength to those who are tired.", ref: "Isa 40:29", tradition: "jewish" },
  "7-25": { quote: "Be like Aaron — love peace and pursue peace.", ref: "Pirkei Avot 1:12", tradition: "jewish" },
  "7-26": { quote: "Every morning, thank God for a brand new day.", ref: "Modeh Ani prayer", tradition: "jewish" },
  "7-27": { quote: "God is everywhere — in the sky, in the sea, and in your heart.", ref: "Ps 139:7", tradition: "jewish" },
  "7-28": { quote: "When Moses was a baby, his mother kept him safe.", ref: "Ex 2:3", tradition: "jewish" },
  "7-29": { quote: "Daniel was brave in the lions' den because God was with him.", ref: "Dan 6:22", tradition: "jewish" },
  "7-30": { quote: "God calls the stars by name — He knows your name too.", ref: "Isa 40:26", tradition: "jewish" },
  "7-31": { quote: "Summertime is a time to play, learn, and grow.", ref: "Jewish wisdom", tradition: "jewish" },

  // ===== AUGUST (Late summer, preparation, growth) =====
  "8-1": { quote: "Hear, O Israel — the Lord our God, the Lord is One.", ref: "Deut 6:4", tradition: "jewish" },
  "8-2": { quote: "Write God's words on your heart.", ref: "Deut 6:6", tradition: "jewish" },
  "8-3": { quote: "Talk about God's words when you walk, when you sit, and when you lie down.", ref: "Deut 6:7", tradition: "jewish" },
  "8-4": { quote: "God chose you because He loves you.", ref: "Deut 7:7", tradition: "jewish" },
  "8-5": { quote: "Remember the good things God has done for you.", ref: "Deut 8:2", tradition: "jewish" },
  "8-6": { quote: "God brought you to a good land, full of streams and springs.", ref: "Deut 8:7", tradition: "jewish" },
  "8-7": { quote: "When you have eaten and are full, bless the Lord.", ref: "Deut 8:10", tradition: "jewish" },
  "8-8": { quote: "Man does not live by bread alone, but by every word of God.", ref: "Deut 8:3", tradition: "jewish" },
  "8-9": { quote: "Keep trying, keep growing — God is cheering you on.", ref: "Jewish wisdom", tradition: "jewish" },
  "8-10": { quote: "God carries you like a parent carries a child.", ref: "Deut 1:31", tradition: "jewish" },
  "8-11": { quote: "The secret things belong to God — but what He reveals is ours.", ref: "Deut 29:29", tradition: "jewish" },
  "8-12": { quote: "Choose life, so that you and your children may live.", ref: "Deut 30:19", tradition: "jewish" },
  "8-13": { quote: "God's word is very near you — it is in your mouth and in your heart.", ref: "Deut 30:14", tradition: "jewish" },
  "8-14": { quote: "Do justly, love mercy, and walk humbly with God.", ref: "Mic 6:8", tradition: "jewish" },
  "8-15": { quote: "Each new day is a chance to start fresh.", ref: "Jewish wisdom", tradition: "jewish" },
  "8-16": { quote: "God created the world with words — your words are powerful too.", ref: "Gen 1:3", tradition: "jewish" },
  "8-17": { quote: "Be careful with your words — they can help or hurt.", ref: "Prov 18:21", tradition: "jewish" },
  "8-18": { quote: "A good name is worth more than great riches.", ref: "Prov 22:1", tradition: "jewish" },
  "8-19": { quote: "God made you to be a light in the world.", ref: "Isa 42:6", tradition: "jewish" },
  "8-20": { quote: "Before you were born, God knew you and loved you.", ref: "Jer 1:5", tradition: "jewish" },
  "8-21": { quote: "The Lord is my light and my salvation — whom shall I fear?", ref: "Ps 27:1", tradition: "jewish" },
  "8-22": { quote: "Wait for God and be strong — He will help you.", ref: "Ps 27:14", tradition: "jewish" },
  "8-23": { quote: "God hears your voice when you call to Him.", ref: "Ps 55:17", tradition: "jewish" },
  "8-24": { quote: "As the new year approaches, think about how to be even kinder.", ref: "Jewish wisdom", tradition: "jewish" },
  "8-25": { quote: "Teshuvah means turning back to God — it is always the right time.", ref: "Jewish wisdom", tradition: "jewish" },
  "8-26": { quote: "God is patient and forgiving — we should be too.", ref: "Ex 34:6", tradition: "jewish" },
  "8-27": { quote: "When you make a mistake, say sorry and try again.", ref: "Jewish wisdom", tradition: "jewish" },
  "8-28": { quote: "God loves a humble heart.", ref: "Prov 22:4", tradition: "jewish" },
  "8-29": { quote: "The month of Elul is a time to get ready for the new year.", ref: "Jewish tradition", tradition: "jewish" },
  "8-30": { quote: "God is close to you — especially when you seek Him.", ref: "Ps 145:18", tradition: "jewish" },
  "8-31": { quote: "Prepare your heart for wonderful new beginnings.", ref: "Jewish wisdom", tradition: "jewish" },

  // ===== SEPTEMBER (Rosh Hashanah, Yom Kippur, new beginnings) =====
  "9-1": { quote: "Today is the birthday of the world!", ref: "Rosh Hashanah liturgy", tradition: "jewish" },
  "9-2": { quote: "Hear the shofar blow — wake up to a brand new year!", ref: "Rosh Hashanah liturgy", tradition: "jewish" },
  "9-3": { quote: "Dip the apple in honey for a sweet new year.", ref: "Rosh Hashanah tradition", tradition: "jewish" },
  "9-4": { quote: "Shanah Tovah! May you have a good and sweet year.", ref: "Rosh Hashanah greeting", tradition: "jewish" },
  "9-5": { quote: "God writes your name in the Book of Life.", ref: "Rosh Hashanah liturgy", tradition: "jewish" },
  "9-6": { quote: "The shofar calls us to be our best selves.", ref: "Jewish wisdom", tradition: "jewish" },
  "9-7": { quote: "On Rosh Hashanah, we say we are sorry and start fresh.", ref: "Jewish tradition", tradition: "jewish" },
  "9-8": { quote: "A new year means new chances to be kind.", ref: "Jewish wisdom", tradition: "jewish" },
  "9-9": { quote: "God remembers every good thing you have ever done.", ref: "Rosh Hashanah liturgy", tradition: "jewish" },
  "9-10": { quote: "Forgive others the way God forgives you.", ref: "Jewish wisdom", tradition: "jewish" },
  "9-11": { quote: "Yom Kippur is the day of forgiveness — say sorry with your whole heart.", ref: "Lev 16:30", tradition: "jewish" },
  "9-12": { quote: "On Yom Kippur, God cleans our hearts and makes them new.", ref: "Yom Kippur liturgy", tradition: "jewish" },
  "9-13": { quote: "Who is the bravest? The one who says, 'I am sorry.'", ref: "Jewish wisdom", tradition: "jewish" },
  "9-14": { quote: "God's mercy is new every morning.", ref: "Lam 3:23", tradition: "jewish" },
  "9-15": { quote: "Teshuvah, tefillah, tzedakah — returning, prayer, and charity change everything.", ref: "Yom Kippur liturgy", tradition: "jewish" },
  "9-16": { quote: "Build a sukkah and invite everyone in!", ref: "Lev 23:42", tradition: "jewish" },
  "9-17": { quote: "In the sukkah, we sit under the stars and thank God.", ref: "Sukkot tradition", tradition: "jewish" },
  "9-18": { quote: "The lulav and etrog remind us of God's beautiful creation.", ref: "Lev 23:40", tradition: "jewish" },
  "9-19": { quote: "Shake the lulav in every direction — God is everywhere!", ref: "Sukkot tradition", tradition: "jewish" },
  "9-20": { quote: "Sukkot is the happiest holiday — be full of joy!", ref: "Deut 16:14", tradition: "jewish" },
  "9-21": { quote: "Thank God for the roof over your head and the food on your table.", ref: "Jewish wisdom", tradition: "jewish" },
  "9-22": { quote: "Ushpizin — we welcome special guests into the sukkah.", ref: "Sukkot tradition", tradition: "jewish" },
  "9-23": { quote: "God is our shelter, just like the sukkah.", ref: "Ps 27:5", tradition: "jewish" },
  "9-24": { quote: "On Simchat Torah, we dance with the Torah and start reading again!", ref: "Simchat Torah tradition", tradition: "jewish" },
  "9-25": { quote: "The Torah has no end — we read it again and again.", ref: "Jewish wisdom", tradition: "jewish" },
  "9-26": { quote: "Rejoice in the Torah! It is our greatest treasure.", ref: "Simchat Torah tradition", tradition: "jewish" },
  "9-27": { quote: "God creates new beginnings for everyone.", ref: "Jewish wisdom", tradition: "jewish" },
  "9-28": { quote: "This is the day the Lord has made — let us be glad and rejoice.", ref: "Ps 118:24", tradition: "jewish" },
  "9-29": { quote: "God gives us each new year as a fresh start.", ref: "Jewish wisdom", tradition: "jewish" },
  "9-30": { quote: "Be grateful for the harvest and all of God's gifts.", ref: "Deut 16:15", tradition: "jewish" },

  // ===== OCTOBER (Post-holidays, gratitude, Torah study) =====
  "10-1": { quote: "In the beginning, God said, 'Let there be light!' — and there was light.", ref: "Gen 1:3", tradition: "jewish" },
  "10-2": { quote: "Noah built an ark and saved the animals — two by two.", ref: "Gen 6:19", tradition: "jewish" },
  "10-3": { quote: "After the flood, God put a rainbow in the sky as a promise.", ref: "Gen 9:13", tradition: "jewish" },
  "10-4": { quote: "Abraham looked at the stars and believed God's promise.", ref: "Gen 15:6", tradition: "jewish" },
  "10-5": { quote: "Sarah laughed when she heard good news — laughter is a blessing.", ref: "Gen 18:12", tradition: "jewish" },
  "10-6": { quote: "Be like Abraham — welcome strangers with kindness.", ref: "Gen 18:3", tradition: "jewish" },
  "10-7": { quote: "Isaac means 'laughter' — God fills our lives with joy.", ref: "Gen 21:6", tradition: "jewish" },
  "10-8": { quote: "Jacob wrestled all night and would not give up.", ref: "Gen 32:24", tradition: "jewish" },
  "10-9": { quote: "Joseph had a coat of many colors — you are colorful too!", ref: "Gen 37:3", tradition: "jewish" },
  "10-10": { quote: "Even when things are hard, God has a plan for good.", ref: "Gen 50:20", tradition: "jewish" },
  "10-11": { quote: "Moses saw a burning bush and stopped to listen to God.", ref: "Ex 3:2", tradition: "jewish" },
  "10-12": { quote: "God told Moses, 'I will be with you.' He is with you too.", ref: "Ex 3:12", tradition: "jewish" },
  "10-13": { quote: "The Red Sea parted — nothing is impossible for God.", ref: "Ex 14:21", tradition: "jewish" },
  "10-14": { quote: "God fed His people with manna from heaven.", ref: "Ex 16:15", tradition: "jewish" },
  "10-15": { quote: "Autumn leaves fall, but the tree stays strong.", ref: "Jewish wisdom", tradition: "jewish" },
  "10-16": { quote: "God gives us seasons to enjoy — fall is full of color.", ref: "Gen 8:22", tradition: "jewish" },
  "10-17": { quote: "Be thankful for your family — they are God's gift to you.", ref: "Jewish wisdom", tradition: "jewish" },
  "10-18": { quote: "A kind deed done in secret is the most beautiful.", ref: "Talmud, Sukkah 49b", tradition: "jewish" },
  "10-19": { quote: "The world was built on kindness.", ref: "Ps 89:2", tradition: "jewish" },
  "10-20": { quote: "God remembers the good in every person.", ref: "Jewish wisdom", tradition: "jewish" },
  "10-21": { quote: "Learn from your mistakes — that is how you grow.", ref: "Prov 24:16", tradition: "jewish" },
  "10-22": { quote: "A righteous person falls seven times and gets back up.", ref: "Prov 24:16", tradition: "jewish" },
  "10-23": { quote: "Guard your tongue from speaking unkind words.", ref: "Ps 34:13", tradition: "jewish" },
  "10-24": { quote: "God is near to those with a broken heart.", ref: "Ps 34:18", tradition: "jewish" },
  "10-25": { quote: "Your words can build someone up — choose them carefully.", ref: "Prov 12:25", tradition: "jewish" },
  "10-26": { quote: "Trust in God and do good.", ref: "Ps 37:3", tradition: "jewish" },
  "10-27": { quote: "Delight yourself in God, and He will give you the desires of your heart.", ref: "Ps 37:4", tradition: "jewish" },
  "10-28": { quote: "Be still and know that God is God.", ref: "Ps 46:10", tradition: "jewish" },
  "10-29": { quote: "Create in me a clean heart, O God.", ref: "Ps 51:10", tradition: "jewish" },
  "10-30": { quote: "God sets the lonely in families — you are never alone.", ref: "Ps 68:6", tradition: "jewish" },
  "10-31": { quote: "How wonderful are Your works, O God!", ref: "Ps 104:24", tradition: "jewish" },

  // ===== NOVEMBER (Hanukkah preparation, gratitude, light) =====
  "11-1": { quote: "Thank God for your home, your family, and your friends.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-2": { quote: "God is your hiding place — He keeps you safe.", ref: "Ps 32:7", tradition: "jewish" },
  "11-3": { quote: "Sing a new song to God — He has done wonderful things.", ref: "Ps 98:1", tradition: "jewish" },
  "11-4": { quote: "Gratitude is the beginning of wisdom.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-5": { quote: "God heals the brokenhearted and bandages their wounds.", ref: "Ps 147:3", tradition: "jewish" },
  "11-6": { quote: "Open your heart wide and let God fill it with joy.", ref: "Ps 81:10", tradition: "jewish" },
  "11-7": { quote: "Come, let us sing for joy to the Lord!", ref: "Ps 95:1", tradition: "jewish" },
  "11-8": { quote: "Give thanks to God for every meal, every hug, every day.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-9": { quote: "A thankful heart sees blessings everywhere.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-10": { quote: "God watches over you like a loving parent.", ref: "Ps 121:4", tradition: "jewish" },
  "11-11": { quote: "The Lord will guard you from all harm.", ref: "Ps 121:7", tradition: "jewish" },
  "11-12": { quote: "I lift up my eyes to the mountains — where does my help come from?", ref: "Ps 121:1", tradition: "jewish" },
  "11-13": { quote: "My help comes from the Lord, who made heaven and earth.", ref: "Ps 121:2", tradition: "jewish" },
  "11-14": { quote: "God never sleeps — He is always watching over you.", ref: "Ps 121:4", tradition: "jewish" },
  "11-15": { quote: "A little light can chase away a lot of darkness.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-16": { quote: "The Maccabees were brave — you can be brave too.", ref: "Hanukkah tradition", tradition: "jewish" },
  "11-17": { quote: "One small jar of oil burned for eight whole nights — a miracle!", ref: "Talmud, Shabbat 21b", tradition: "jewish" },
  "11-18": { quote: "Light one candle and push back the darkness.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-19": { quote: "God does miracles for those who believe.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-20": { quote: "The menorah shines in the window for all to see.", ref: "Talmud, Shabbat 21b", tradition: "jewish" },
  "11-21": { quote: "Not by might, not by power, but by My spirit, says God.", ref: "Zech 4:6", tradition: "jewish" },
  "11-22": { quote: "Give thanks to God — His love endures forever.", ref: "Ps 136:1", tradition: "jewish" },
  "11-23": { quote: "Every good gift comes from above.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-24": { quote: "Be thankful for the food on your table — it is a blessing.", ref: "Deut 8:10", tradition: "jewish" },
  "11-25": { quote: "Light the shamash candle — it helps light all the others.", ref: "Hanukkah tradition", tradition: "jewish" },
  "11-26": { quote: "Hanukkah gelt reminds us to share our blessings.", ref: "Hanukkah tradition", tradition: "jewish" },
  "11-27": { quote: "Spin the dreidel! A great miracle happened there.", ref: "Hanukkah tradition", tradition: "jewish" },
  "11-28": { quote: "God's miracles happen every day — look for them.", ref: "Jewish liturgy", tradition: "jewish" },
  "11-29": { quote: "The light of God can never be put out.", ref: "Jewish wisdom", tradition: "jewish" },
  "11-30": { quote: "Be a light to those around you.", ref: "Isa 42:6", tradition: "jewish" },

  // ===== DECEMBER (Hanukkah, light, miracles, winter) =====
  "12-1": { quote: "Happy Hanukkah! The Festival of Lights has begun!", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-2": { quote: "Light the first candle and watch the darkness disappear.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-3": { quote: "Two candles now — the light is growing!", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-4": { quote: "Three candles glow — miracles happen when we believe.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-5": { quote: "Four candles shine — each night we add more light.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-6": { quote: "Five candles now — the world is getting brighter.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-7": { quote: "Six candles burn — God's love grows stronger each day.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-8": { quote: "Seven candles shine — we are almost there!", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-9": { quote: "Eight candles blaze — the menorah is full of light!", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-10": { quote: "The Maccabees stood up for what was right — you can too.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-11": { quote: "Even a small flame lights up a dark room.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-12": { quote: "God makes miracles — keep your eyes open for them.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-13": { quote: "Latkes and sufganiyot remind us of the oil that lasted eight nights.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-14": { quote: "Share your light with others, just like the shamash candle.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-15": { quote: "Judah Maccabee was brave and trusted in God.", ref: "Hanukkah tradition", tradition: "jewish" },
  "12-16": { quote: "A miracle is something wonderful that only God can do.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-17": { quote: "When you light a candle for someone else, your own light grows.", ref: "Talmud", tradition: "jewish" },
  "12-18": { quote: "The menorah reminds us that God is the light of the world.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-19": { quote: "Winter nights are long, but God's light never fades.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-20": { quote: "God wraps the earth in snow like a warm white blanket.", ref: "Ps 147:16", tradition: "jewish" },
  "12-21": { quote: "The shortest day of the year — but God's light shines even brighter.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-22": { quote: "God sends snow like wool and scatters frost like ashes.", ref: "Ps 147:16", tradition: "jewish" },
  "12-23": { quote: "In the cold of winter, God keeps your heart warm.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-24": { quote: "God is faithful — He keeps every promise He makes.", ref: "Deut 7:9", tradition: "jewish" },
  "12-25": { quote: "Spread kindness like light — it costs nothing and means everything.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-26": { quote: "God's goodness and mercy follow you all the days of your life.", ref: "Ps 23:6", tradition: "jewish" },
  "12-27": { quote: "You are a child of God — you are precious and loved.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-28": { quote: "God holds the whole world in His hands.", ref: "Isa 40:12", tradition: "jewish" },
  "12-29": { quote: "Look back on this year and thank God for every blessing.", ref: "Jewish wisdom", tradition: "jewish" },
  "12-30": { quote: "God has great plans for you — trust in Him.", ref: "Jer 29:11", tradition: "jewish" },
  "12-31": { quote: "Thank God for this year and get ready for the next one!", ref: "Jewish wisdom", tradition: "jewish" },
};
