import { ColoringBook } from './types';

// Coloring book catalog metadata
// All books start as "Coming Soon" (available: false)

export const coloringBooks: ColoringBook[] = [
  // Hindu
  {
    id: 'hindu-diwali',
    title: 'The First Diwali',
    description: 'Celebrate the festival of lights with beautiful coloring pages featuring diyas, rangoli, and the story of Rama and Sita.',
    coverEmoji: '🪔',
    traditions: ['hindu'],
    regions: ['us', 'india', 'global'],
    months: [10, 11],
    tags: ['diwali', 'light', 'festival', 'rama', 'sita'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
  {
    id: 'hindu-holi',
    title: 'Holi — Festival of Colors',
    description: 'A burst of color! Pages featuring gulal, water balloons, Krishna and Radha, and joyful celebrations.',
    coverEmoji: '🎨',
    traditions: ['hindu'],
    regions: ['us', 'india', 'global'],
    months: [3],
    tags: ['holi', 'colors', 'festival', 'krishna'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
  {
    id: 'hindu-ganesha',
    title: 'Ganesha — The Remover of Obstacles',
    description: 'Meet Lord Ganesha! Color his elephant head, his mouse vehicle, and learn about the god of new beginnings.',
    coverEmoji: '🐘',
    traditions: ['hindu'],
    regions: ['us', 'india', 'global'],
    months: [9],
    tags: ['ganesha', 'chaturthi', 'elephant', 'wisdom'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
  {
    id: 'hindu-rama-sita',
    title: 'The Story of Rama and Sita',
    description: 'Follow the epic adventure of Prince Rama and Princess Sita through beautiful coloring pages.',
    coverEmoji: '🏹',
    traditions: ['hindu'],
    regions: ['us', 'india', 'global'],
    months: [10],
    tags: ['rama', 'sita', 'ramayana', 'dussehra'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },

  // Christian
  {
    id: 'christian-easter',
    title: 'The Easter Story',
    description: 'The story of Easter told through gentle coloring pages — palm branches, the empty tomb, and new life in spring.',
    coverEmoji: '🐣',
    traditions: ['christian-catholic', 'christian-protestant'],
    regions: ['us', 'uk', 'global'],
    months: [3, 4],
    tags: ['easter', 'resurrection', 'spring', 'jesus'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
  {
    id: 'christian-christmas',
    title: 'The Christmas Nativity',
    description: 'Color the nativity scene — baby Jesus, Mary and Joseph, the shepherds, and the star of Bethlehem.',
    coverEmoji: '⭐',
    traditions: ['christian-catholic', 'christian-protestant'],
    regions: ['us', 'uk', 'global'],
    months: [12],
    tags: ['christmas', 'nativity', 'jesus', 'bethlehem'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
  {
    id: 'christian-saints',
    title: 'Saints for Little Ones',
    description: 'Meet the saints! Simple, friendly coloring pages of beloved saints and their stories.',
    coverEmoji: '😇',
    traditions: ['christian-catholic'],
    regions: ['us', 'uk', 'global'],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tags: ['saints', 'catholic', 'heroes'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },

  // Universal
  {
    id: 'universal-seasons',
    title: 'Seasons of the Year',
    description: 'Spring flowers, summer sunshine, autumn leaves, and winter snow — color your way through the year!',
    coverEmoji: '🌸',
    traditions: ['universal'],
    regions: ['us', 'uk', 'india', 'global'],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tags: ['seasons', 'nature', 'weather'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
  {
    id: 'universal-animals',
    title: 'Animals of the World',
    description: 'Lions, elephants, penguins, and more — color animals from every continent!',
    coverEmoji: '🦁',
    traditions: ['universal'],
    regions: ['us', 'uk', 'india', 'global'],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tags: ['animals', 'nature', 'wildlife'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
  {
    id: 'universal-family',
    title: 'My Family',
    description: 'Color pages about families — grandparents, siblings, pets, and all the people who love you!',
    coverEmoji: '👨‍👩‍👧‍👦',
    traditions: ['universal'],
    regions: ['us', 'uk', 'india', 'global'],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tags: ['family', 'love', 'home'],
    price: 9.99,
    pageCount: 24,
    available: false,
  },
];
