import { AffirmationMap } from '../../types';

// Quran verses, Hadith wisdom quotes — 365 entries, one per day
// Sources: Quran, Hadith (Bukhari, Muslim, Tirmidhi, etc.), Islamic wisdom

export const muslimAffirmations: AffirmationMap = {
  // ── January — New beginnings, gratitude, trust in Allah ──────────────
  "1-1": { quote: "In the name of Allah, the Most Gracious, the Most Merciful.", ref: "Quran 1:1", tradition: "muslim" },
  "1-2": { quote: "All praise belongs to Allah, the Lord of all the worlds.", ref: "Quran 1:2", tradition: "muslim" },
  "1-3": { quote: "Say good words or stay silent.", ref: "Bukhari", tradition: "muslim" },
  "1-4": { quote: "Allah is with those who are patient.", ref: "Quran 2:153", tradition: "muslim" },
  "1-5": { quote: "The best among you are those with the best manners.", ref: "Bukhari", tradition: "muslim" },
  "1-6": { quote: "Be kind to everyone you meet.", ref: "Muslim", tradition: "muslim" },
  "1-7": { quote: "Allah loves those who do good.", ref: "Quran 2:195", tradition: "muslim" },
  "1-8": { quote: "A smile for your brother is charity.", ref: "Tirmidhi", tradition: "muslim" },
  "1-9": { quote: "Trust in Allah and He will guide your way.", ref: "Quran 65:3", tradition: "muslim" },
  "1-10": { quote: "Be thankful and Allah will give you more.", ref: "Quran 14:7", tradition: "muslim" },
  "1-11": { quote: "The strong person is the one who controls their anger.", ref: "Bukhari", tradition: "muslim" },
  "1-12": { quote: "Allah does not burden anyone beyond what they can bear.", ref: "Quran 2:286", tradition: "muslim" },
  "1-13": { quote: "Speak the truth even when it is hard.", ref: "Muslim", tradition: "muslim" },
  "1-14": { quote: "Whoever is kind to others, Allah will be kind to them.", ref: "Bukhari", tradition: "muslim" },
  "1-15": { quote: "Remember Allah and your heart will find peace.", ref: "Quran 13:28", tradition: "muslim" },
  "1-16": { quote: "The best gift a parent can give is good manners.", ref: "Tirmidhi", tradition: "muslim" },
  "1-17": { quote: "Allah made you special and loves you very much.", ref: "Quran 95:4", tradition: "muslim" },
  "1-18": { quote: "Be gentle — gentleness makes everything more beautiful.", ref: "Muslim", tradition: "muslim" },
  "1-19": { quote: "Ask Allah for help — He always hears your prayers.", ref: "Quran 2:186", tradition: "muslim" },
  "1-20": { quote: "Do not be sad. Allah is always with us.", ref: "Quran 9:40", tradition: "muslim" },
  "1-21": { quote: "Feed the hungry and spread peace.", ref: "Bukhari", tradition: "muslim" },
  "1-22": { quote: "Allah created everything in the heavens and the earth.", ref: "Quran 6:1", tradition: "muslim" },
  "1-23": { quote: "Kindness is a mark of faith.", ref: "Muslim", tradition: "muslim" },
  "1-24": { quote: "Whoever believes in Allah, let them speak good or be silent.", ref: "Bukhari", tradition: "muslim" },
  "1-25": { quote: "Allah is the Light of the heavens and the earth.", ref: "Quran 24:35", tradition: "muslim" },
  "1-26": { quote: "The best of people are those who are most helpful to others.", ref: "Tirmidhi", tradition: "muslim" },
  "1-27": { quote: "With every difficulty there is ease.", ref: "Quran 94:6", tradition: "muslim" },
  "1-28": { quote: "Love for others what you love for yourself.", ref: "Bukhari", tradition: "muslim" },
  "1-29": { quote: "Allah knows what is in every heart.", ref: "Quran 3:119", tradition: "muslim" },
  "1-30": { quote: "A kind word is charity.", ref: "Bukhari", tradition: "muslim" },
  "1-31": { quote: "Allah is the Most Forgiving and the Most Merciful.", ref: "Quran 2:173", tradition: "muslim" },

  // ── February — Love, mercy, family, compassion ──────────────────────
  "2-1": { quote: "Show mercy to those on earth and the One in heaven will show mercy to you.", ref: "Tirmidhi", tradition: "muslim" },
  "2-2": { quote: "The best of you are those who are best to their families.", ref: "Tirmidhi", tradition: "muslim" },
  "2-3": { quote: "Allah's mercy covers everything.", ref: "Quran 7:156", tradition: "muslim" },
  "2-4": { quote: "Be good to your parents — Allah has commanded it.", ref: "Quran 17:23", tradition: "muslim" },
  "2-5": { quote: "Whoever does a tiny bit of good will see it.", ref: "Quran 99:7", tradition: "muslim" },
  "2-6": { quote: "Love one another and you will be true believers.", ref: "Muslim", tradition: "muslim" },
  "2-7": { quote: "Allah created you from love and for love.", ref: "", tradition: "muslim" },
  "2-8": { quote: "A cheerful face is an act of kindness.", ref: "Tirmidhi", tradition: "muslim" },
  "2-9": { quote: "Tie your bonds of family — Allah will bless you.", ref: "Bukhari", tradition: "muslim" },
  "2-10": { quote: "Whoever is merciful to others will receive Allah's mercy.", ref: "Bukhari", tradition: "muslim" },
  "2-11": { quote: "Speak gently to everyone you meet.", ref: "Quran 2:83", tradition: "muslim" },
  "2-12": { quote: "The believers are like one family — they care for each other.", ref: "Bukhari", tradition: "muslim" },
  "2-13": { quote: "Do good deeds, for Allah loves those who do good.", ref: "Quran 3:134", tradition: "muslim" },
  "2-14": { quote: "Love is a gift from Allah. Share it with everyone.", ref: "", tradition: "muslim" },
  "2-15": { quote: "Allah is closer to you than your own heartbeat.", ref: "Quran 50:16", tradition: "muslim" },
  "2-16": { quote: "The hand that gives is better than the hand that takes.", ref: "Bukhari", tradition: "muslim" },
  "2-17": { quote: "Be patient — good things come to those who wait.", ref: "Quran 11:115", tradition: "muslim" },
  "2-18": { quote: "Every child is born with a pure, good heart.", ref: "Bukhari", tradition: "muslim" },
  "2-19": { quote: "Help your neighbor and you will find joy.", ref: "Bukhari", tradition: "muslim" },
  "2-20": { quote: "Allah sees all the good you do, even the smallest act.", ref: "Quran 99:7", tradition: "muslim" },
  "2-21": { quote: "Honor your guests — it is part of faith.", ref: "Bukhari", tradition: "muslim" },
  "2-22": { quote: "The earth is a mosque for you — pray wherever you are.", ref: "Bukhari", tradition: "muslim" },
  "2-23": { quote: "Be humble. Allah loves those who are humble.", ref: "Muslim", tradition: "muslim" },
  "2-24": { quote: "Guard your tongue — say only what is true and kind.", ref: "Tirmidhi", tradition: "muslim" },
  "2-25": { quote: "Forgive others and Allah will forgive you.", ref: "Quran 24:22", tradition: "muslim" },
  "2-26": { quote: "The most beloved deed to Allah is kindness to people.", ref: "Bukhari", tradition: "muslim" },
  "2-27": { quote: "Your mother deserves your kindness three times over.", ref: "Bukhari", tradition: "muslim" },
  "2-28": { quote: "Allah is beautiful and He loves beauty.", ref: "Muslim", tradition: "muslim" },

  // ── March — Spring, renewal, preparation, Ramadan themes ────────────
  "3-1": { quote: "He is Allah, the Creator, who gives everything its shape.", ref: "Quran 59:24", tradition: "muslim" },
  "3-2": { quote: "Planting a tree is charity that keeps on giving.", ref: "Bukhari", tradition: "muslim" },
  "3-3": { quote: "Allah sends down rain and brings the earth back to life.", ref: "Quran 30:24", tradition: "muslim" },
  "3-4": { quote: "Seek knowledge from the cradle to the grave.", ref: "", tradition: "muslim" },
  "3-5": { quote: "Whoever follows a path to learn, Allah makes the path to Paradise easy.", ref: "Muslim", tradition: "muslim" },
  "3-6": { quote: "The ink of a scholar is holier than the blood of a martyr.", ref: "", tradition: "muslim" },
  "3-7": { quote: "Share your food with others — that is true generosity.", ref: "Bukhari", tradition: "muslim" },
  "3-8": { quote: "Look at the flowers and the trees — they are signs of Allah's love.", ref: "Quran 6:99", tradition: "muslim" },
  "3-9": { quote: "Be grateful for every blessing, big or small.", ref: "Quran 14:7", tradition: "muslim" },
  "3-10": { quote: "Fasting teaches us to be patient and thankful.", ref: "", tradition: "muslim" },
  "3-11": { quote: "The month of Ramadan is a time for kindness and prayer.", ref: "", tradition: "muslim" },
  "3-12": { quote: "Giving charity purifies your heart.", ref: "Quran 9:103", tradition: "muslim" },
  "3-13": { quote: "In Ramadan, the gates of heaven are open wide.", ref: "Bukhari", tradition: "muslim" },
  "3-14": { quote: "Read and learn — Allah taught us with the pen.", ref: "Quran 96:4", tradition: "muslim" },
  "3-15": { quote: "Be generous during Ramadan — share what you have.", ref: "Bukhari", tradition: "muslim" },
  "3-16": { quote: "When you fast, your heart grows stronger.", ref: "", tradition: "muslim" },
  "3-17": { quote: "The Quran was sent down in the month of Ramadan.", ref: "Quran 2:185", tradition: "muslim" },
  "3-18": { quote: "Make dua for others — the angels say amen for you.", ref: "Muslim", tradition: "muslim" },
  "3-19": { quote: "Patience during fasting brings you closer to Allah.", ref: "", tradition: "muslim" },
  "3-20": { quote: "Every good deed is multiplied in Ramadan.", ref: "Bukhari", tradition: "muslim" },
  "3-21": { quote: "Ramadan is a time to help those in need.", ref: "", tradition: "muslim" },
  "3-22": { quote: "Break your fast with dates and water, just like the Prophet.", ref: "Abu Dawud", tradition: "muslim" },
  "3-23": { quote: "The night of power is better than a thousand months.", ref: "Quran 97:3", tradition: "muslim" },
  "3-24": { quote: "Pray together as a family — it brings Allah's blessings.", ref: "", tradition: "muslim" },
  "3-25": { quote: "Give sadaqah and watch your blessings grow.", ref: "Quran 2:261", tradition: "muslim" },
  "3-26": { quote: "Allah loves those who turn to Him again and again.", ref: "Quran 2:222", tradition: "muslim" },
  "3-27": { quote: "Laylat al-Qadr is the most special night of the year.", ref: "Quran 97:1", tradition: "muslim" },
  "3-28": { quote: "Stand in prayer at night and your heart will shine.", ref: "Quran 73:6", tradition: "muslim" },
  "3-29": { quote: "Sharing your iftar meal is a beautiful act of charity.", ref: "Tirmidhi", tradition: "muslim" },
  "3-30": { quote: "Allah accepts the prayers of those who ask with a sincere heart.", ref: "Quran 40:60", tradition: "muslim" },
  "3-31": { quote: "Ramadan helps us remember those who have less.", ref: "", tradition: "muslim" },

  // ── April — Eid, celebration, gratitude, sharing ────────────────────
  "4-1": { quote: "Eid is a day of joy and thanksgiving to Allah.", ref: "", tradition: "muslim" },
  "4-2": { quote: "On Eid we celebrate with family and give thanks.", ref: "", tradition: "muslim" },
  "4-3": { quote: "Eid Mubarak! May Allah bless you and your family.", ref: "", tradition: "muslim" },
  "4-4": { quote: "Wear your best clothes and share your happiness on Eid.", ref: "Bukhari", tradition: "muslim" },
  "4-5": { quote: "Give Zakat al-Fitr so everyone can celebrate Eid.", ref: "Bukhari", tradition: "muslim" },
  "4-6": { quote: "Allah is pleased when you share your food with others.", ref: "Bukhari", tradition: "muslim" },
  "4-7": { quote: "Thank Allah for the blessing of Ramadan.", ref: "", tradition: "muslim" },
  "4-8": { quote: "Celebrate with sweets, hugs, and prayers on Eid.", ref: "", tradition: "muslim" },
  "4-9": { quote: "After Ramadan, keep being kind and generous.", ref: "", tradition: "muslim" },
  "4-10": { quote: "Gratitude makes your blessings grow even bigger.", ref: "Quran 14:7", tradition: "muslim" },
  "4-11": { quote: "Say Alhamdulillah for every good thing in your life.", ref: "", tradition: "muslim" },
  "4-12": { quote: "Allah made the sun, the moon, and the stars for you.", ref: "Quran 14:33", tradition: "muslim" },
  "4-13": { quote: "Play, laugh, and enjoy — Allah loves a happy heart.", ref: "", tradition: "muslim" },
  "4-14": { quote: "Be a good friend and Allah will bless your friendships.", ref: "Abu Dawud", tradition: "muslim" },
  "4-15": { quote: "When you help someone, you help yourself.", ref: "Muslim", tradition: "muslim" },
  "4-16": { quote: "Say Bismillah before you eat and thank Allah when you finish.", ref: "Bukhari", tradition: "muslim" },
  "4-17": { quote: "Every creature on earth depends on Allah for food.", ref: "Quran 11:6", tradition: "muslim" },
  "4-18": { quote: "Allah loves those who share with others.", ref: "Quran 2:195", tradition: "muslim" },
  "4-19": { quote: "Take care of animals — they are part of Allah's creation.", ref: "Bukhari", tradition: "muslim" },
  "4-20": { quote: "Your body is a gift from Allah — take good care of it.", ref: "Bukhari", tradition: "muslim" },
  "4-21": { quote: "Cleanliness is half of faith.", ref: "Muslim", tradition: "muslim" },
  "4-22": { quote: "The earth is a blessing — keep it clean and beautiful.", ref: "", tradition: "muslim" },
  "4-23": { quote: "Learning is a treasure that follows you everywhere.", ref: "", tradition: "muslim" },
  "4-24": { quote: "Read the Quran and let its words fill your heart with light.", ref: "Muslim", tradition: "muslim" },
  "4-25": { quote: "The best worship is thinking about Allah's creation.", ref: "", tradition: "muslim" },
  "4-26": { quote: "Honesty is the path to goodness.", ref: "Bukhari", tradition: "muslim" },
  "4-27": { quote: "Keep your promises — Allah loves those who keep their word.", ref: "Quran 2:177", tradition: "muslim" },
  "4-28": { quote: "Every morning is a new chance to do good.", ref: "", tradition: "muslim" },
  "4-29": { quote: "Allah created you to be a helper in this world.", ref: "Quran 2:30", tradition: "muslim" },
  "4-30": { quote: "Make dua before you sleep and when you wake up.", ref: "Bukhari", tradition: "muslim" },

  // ── May — Growth, learning, nature, knowledge ───────────────────────
  "5-1": { quote: "Say Alhamdulillah — all praise is for Allah.", ref: "Quran 1:2", tradition: "muslim" },
  "5-2": { quote: "The world is green and beautiful, and Allah made you its caretaker.", ref: "Muslim", tradition: "muslim" },
  "5-3": { quote: "Allah made every living thing from water.", ref: "Quran 21:30", tradition: "muslim" },
  "5-4": { quote: "Learning something new every day is pleasing to Allah.", ref: "", tradition: "muslim" },
  "5-5": { quote: "Be curious and ask questions — that is how you grow.", ref: "", tradition: "muslim" },
  "5-6": { quote: "Allah gave you eyes to see, ears to hear, and a heart to understand.", ref: "Quran 16:78", tradition: "muslim" },
  "5-7": { quote: "Treat every person with respect and dignity.", ref: "Quran 17:70", tradition: "muslim" },
  "5-8": { quote: "Honor your mother — paradise is at her feet.", ref: "Ibn Majah", tradition: "muslim" },
  "5-9": { quote: "The birds in the sky praise Allah every day.", ref: "Quran 24:41", tradition: "muslim" },
  "5-10": { quote: "Your duas are like seeds — plant them and watch them grow.", ref: "", tradition: "muslim" },
  "5-11": { quote: "Remove something harmful from the road — that is charity.", ref: "Bukhari", tradition: "muslim" },
  "5-12": { quote: "Allah is the best of planners.", ref: "Quran 8:30", tradition: "muslim" },
  "5-13": { quote: "A person who plants a tree gets reward every time someone rests in its shade.", ref: "Muslim", tradition: "muslim" },
  "5-14": { quote: "Speak the truth, even if your voice shakes.", ref: "", tradition: "muslim" },
  "5-15": { quote: "The sun and the moon move by Allah's perfect plan.", ref: "Quran 55:5", tradition: "muslim" },
  "5-16": { quote: "Be like rain — bring goodness wherever you go.", ref: "", tradition: "muslim" },
  "5-17": { quote: "Allah taught the bee to build its home — He guides all creation.", ref: "Quran 16:68", tradition: "muslim" },
  "5-18": { quote: "The prophets were the kindest of all people.", ref: "", tradition: "muslim" },
  "5-19": { quote: "Say SubhanAllah when you see something beautiful.", ref: "", tradition: "muslim" },
  "5-20": { quote: "A garden grows because Allah sends the rain.", ref: "Quran 56:68", tradition: "muslim" },
  "5-21": { quote: "Help others learn and you will be rewarded too.", ref: "Muslim", tradition: "muslim" },
  "5-22": { quote: "Sleep early, wake early, and start your day with prayer.", ref: "Bukhari", tradition: "muslim" },
  "5-23": { quote: "Allah made the mountains strong and steady, just like your faith.", ref: "Quran 78:7", tradition: "muslim" },
  "5-24": { quote: "When you feel scared, say Bismillah and trust Allah.", ref: "", tradition: "muslim" },
  "5-25": { quote: "Every leaf that falls is known to Allah.", ref: "Quran 6:59", tradition: "muslim" },
  "5-26": { quote: "Be brave and always do what is right.", ref: "", tradition: "muslim" },
  "5-27": { quote: "The rivers and oceans are signs of Allah's power.", ref: "Quran 55:19", tradition: "muslim" },
  "5-28": { quote: "Think before you speak — wise words are a treasure.", ref: "Tirmidhi", tradition: "muslim" },
  "5-29": { quote: "Allah hears you even when you whisper.", ref: "Quran 20:7", tradition: "muslim" },
  "5-30": { quote: "Plant goodness today and harvest blessings tomorrow.", ref: "", tradition: "muslim" },
  "5-31": { quote: "Thank your teachers — they help you learn and grow.", ref: "", tradition: "muslim" },

  // ── June — Friendship, community, summer joy ────────────────────────
  "6-1": { quote: "A true friend reminds you of Allah.", ref: "Abu Dawud", tradition: "muslim" },
  "6-2": { quote: "Be happy with what Allah has given you.", ref: "Quran 16:53", tradition: "muslim" },
  "6-3": { quote: "Share your toys and your friends will love you more.", ref: "", tradition: "muslim" },
  "6-4": { quote: "Allah made people in different colors and languages — how wonderful!", ref: "Quran 30:22", tradition: "muslim" },
  "6-5": { quote: "Play outside and enjoy the world Allah created.", ref: "", tradition: "muslim" },
  "6-6": { quote: "Good friends help each other be better.", ref: "Tirmidhi", tradition: "muslim" },
  "6-7": { quote: "The Prophet Muhammad was the kindest to children.", ref: "Bukhari", tradition: "muslim" },
  "6-8": { quote: "Drink water and say Alhamdulillah — it is a gift from Allah.", ref: "Muslim", tradition: "muslim" },
  "6-9": { quote: "Allah loves you more than you can ever imagine.", ref: "", tradition: "muslim" },
  "6-10": { quote: "A good neighbor is one of the greatest blessings.", ref: "Bukhari", tradition: "muslim" },
  "6-11": { quote: "Give salam to everyone — spread peace wherever you go.", ref: "Muslim", tradition: "muslim" },
  "6-12": { quote: "Allah made the shade of trees so you can rest.", ref: "Quran 16:81", tradition: "muslim" },
  "6-13": { quote: "Even an ant praises Allah in its own way.", ref: "Quran 27:18", tradition: "muslim" },
  "6-14": { quote: "Make someone smile today — it counts as charity.", ref: "Tirmidhi", tradition: "muslim" },
  "6-15": { quote: "Allah created the day for work and the night for rest.", ref: "Quran 78:11", tradition: "muslim" },
  "6-16": { quote: "Respect your elders and be kind to the young.", ref: "Tirmidhi", tradition: "muslim" },
  "6-17": { quote: "Every person is part of one big human family.", ref: "Quran 49:13", tradition: "muslim" },
  "6-18": { quote: "Playing with your siblings is time well spent.", ref: "", tradition: "muslim" },
  "6-19": { quote: "Your father works hard for you — honor him with love.", ref: "Quran 17:23", tradition: "muslim" },
  "6-20": { quote: "The sky is a beautiful ceiling that Allah built.", ref: "Quran 50:6", tradition: "muslim" },
  "6-21": { quote: "On the longest day, thank Allah for the gift of sunlight.", ref: "Quran 71:16", tradition: "muslim" },
  "6-22": { quote: "Invite your friends over and share a meal — it brings baraka.", ref: "Muslim", tradition: "muslim" },
  "6-23": { quote: "Listen when others speak — it shows respect.", ref: "", tradition: "muslim" },
  "6-24": { quote: "Swim, run, and play — keeping your body healthy pleases Allah.", ref: "", tradition: "muslim" },
  "6-25": { quote: "The stars at night are lamps Allah placed in the sky.", ref: "Quran 67:5", tradition: "muslim" },
  "6-26": { quote: "Share your snacks with friends — sharing brings joy.", ref: "", tradition: "muslim" },
  "6-27": { quote: "Allah guides to His light whom He wills.", ref: "Quran 24:35", tradition: "muslim" },
  "6-28": { quote: "A kind heart is the best kind of heart.", ref: "", tradition: "muslim" },
  "6-29": { quote: "Dhikr means remembering Allah — say His name often.", ref: "Quran 33:41", tradition: "muslim" },
  "6-30": { quote: "Thank Allah for summer days full of play and fun.", ref: "", tradition: "muslim" },

  // ── July — Courage, strength, trusting Allah ────────────────────────
  "7-1": { quote: "Allah is the Protector of those who believe.", ref: "Quran 2:257", tradition: "muslim" },
  "7-2": { quote: "Be brave like the prophets — they always trusted Allah.", ref: "", tradition: "muslim" },
  "7-3": { quote: "Ask Allah for courage and He will make you strong.", ref: "", tradition: "muslim" },
  "7-4": { quote: "Stand up for what is right, even when it is hard.", ref: "Quran 4:135", tradition: "muslim" },
  "7-5": { quote: "Ibrahim trusted Allah completely — we can learn from him.", ref: "Quran 2:131", tradition: "muslim" },
  "7-6": { quote: "Allah made you strong enough to handle any challenge.", ref: "Quran 2:286", tradition: "muslim" },
  "7-7": { quote: "Put your trust in Allah — He will never let you down.", ref: "Quran 3:159", tradition: "muslim" },
  "7-8": { quote: "When Musa was afraid, Allah said: Do not fear, I am with you.", ref: "Quran 20:46", tradition: "muslim" },
  "7-9": { quote: "Being brave means doing the right thing, even when scared.", ref: "", tradition: "muslim" },
  "7-10": { quote: "Allah never leaves you — He is always by your side.", ref: "Quran 57:4", tradition: "muslim" },
  "7-11": { quote: "Say Allahu Akbar — Allah is Greater than any worry.", ref: "", tradition: "muslim" },
  "7-12": { quote: "The Prophet Yunus called upon Allah from the belly of the whale.", ref: "Quran 21:87", tradition: "muslim" },
  "7-13": { quote: "Even the darkest night ends with a bright new morning.", ref: "Quran 93:1", tradition: "muslim" },
  "7-14": { quote: "You can be strong and gentle at the same time.", ref: "", tradition: "muslim" },
  "7-15": { quote: "Allah's help is always near.", ref: "Quran 2:214", tradition: "muslim" },
  "7-16": { quote: "Yusuf was patient through hard times and Allah rewarded him.", ref: "Quran 12:90", tradition: "muslim" },
  "7-17": { quote: "Never give up — keep trying and trust in Allah's plan.", ref: "", tradition: "muslim" },
  "7-18": { quote: "Saying La ilaha illa Allah is the best thing you can say.", ref: "Tirmidhi", tradition: "muslim" },
  "7-19": { quote: "Allah is Al-Wakeel — the One you can always depend on.", ref: "Quran 3:173", tradition: "muslim" },
  "7-20": { quote: "Water is a blessing — do not waste it.", ref: "Ibn Majah", tradition: "muslim" },
  "7-21": { quote: "When you feel lost, pray and Allah will show you the way.", ref: "Quran 1:6", tradition: "muslim" },
  "7-22": { quote: "Protect the weak and help the helpless.", ref: "Abu Dawud", tradition: "muslim" },
  "7-23": { quote: "Dawood praised Allah with beautiful songs.", ref: "Quran 34:10", tradition: "muslim" },
  "7-24": { quote: "Stay calm when things go wrong — Allah has a plan for you.", ref: "", tradition: "muslim" },
  "7-25": { quote: "Allah shaped you in the womb — you are His perfect creation.", ref: "Quran 3:6", tradition: "muslim" },
  "7-26": { quote: "Help someone carry their load — you will feel lighter too.", ref: "", tradition: "muslim" },
  "7-27": { quote: "The prophet Nuh built the ark and trusted Allah's plan.", ref: "Quran 11:37", tradition: "muslim" },
  "7-28": { quote: "Make dua when it rains — it is a blessed time.", ref: "Abu Dawud", tradition: "muslim" },
  "7-29": { quote: "Allah is Al-Qawiyy — the Most Strong.", ref: "Quran 22:40", tradition: "muslim" },
  "7-30": { quote: "Face your fears with faith and they will shrink.", ref: "", tradition: "muslim" },
  "7-31": { quote: "Every heartbeat is a gift from Allah.", ref: "", tradition: "muslim" },

  // ── August — Gratitude, creation, wonder ────────────────────────────
  "8-1": { quote: "Look at the clouds — Allah shapes them however He wills.", ref: "Quran 24:43", tradition: "muslim" },
  "8-2": { quote: "Say JazakAllah Khair when someone helps you.", ref: "Tirmidhi", tradition: "muslim" },
  "8-3": { quote: "Allah created the camel, the horse, and every animal.", ref: "Quran 16:8", tradition: "muslim" },
  "8-4": { quote: "Eat what is halal and good — it keeps your body healthy.", ref: "Quran 2:168", tradition: "muslim" },
  "8-5": { quote: "Fruits are a sweet gift from Allah.", ref: "Quran 16:11", tradition: "muslim" },
  "8-6": { quote: "Be thankful for your home — not everyone has one.", ref: "", tradition: "muslim" },
  "8-7": { quote: "The honey bee makes honey by Allah's permission.", ref: "Quran 16:69", tradition: "muslim" },
  "8-8": { quote: "Thank Allah for your family — they are your biggest blessing.", ref: "", tradition: "muslim" },
  "8-9": { quote: "Every child is a gift from Allah to the world.", ref: "", tradition: "muslim" },
  "8-10": { quote: "Wudu washes away mistakes and makes you fresh and clean.", ref: "Muslim", tradition: "muslim" },
  "8-11": { quote: "Allah made the night dark so you can rest well.", ref: "Quran 6:96", tradition: "muslim" },
  "8-12": { quote: "Count your blessings — they are too many to count!", ref: "Quran 16:18", tradition: "muslim" },
  "8-13": { quote: "The ocean is vast and deep — a sign of Allah's greatness.", ref: "Quran 55:24", tradition: "muslim" },
  "8-14": { quote: "Thank Allah for clean water to drink and play in.", ref: "", tradition: "muslim" },
  "8-15": { quote: "Sulayman could understand the language of birds.", ref: "Quran 27:16", tradition: "muslim" },
  "8-16": { quote: "Allah made fruits of every color for you to enjoy.", ref: "Quran 35:27", tradition: "muslim" },
  "8-17": { quote: "When you see a rainbow, remember Allah's beautiful signs.", ref: "", tradition: "muslim" },
  "8-18": { quote: "Sit with your family for dinner — it brings baraka to the food.", ref: "Muslim", tradition: "muslim" },
  "8-19": { quote: "Allah created the fish in the sea and the birds in the sky.", ref: "Quran 16:14", tradition: "muslim" },
  "8-20": { quote: "Eat with your right hand and say Bismillah.", ref: "Bukhari", tradition: "muslim" },
  "8-21": { quote: "The wind carries seeds to new places — that is Allah's plan.", ref: "Quran 15:22", tradition: "muslim" },
  "8-22": { quote: "Thank your friends for being part of your life.", ref: "", tradition: "muslim" },
  "8-23": { quote: "Allah created cattle so people could have milk to drink.", ref: "Quran 16:66", tradition: "muslim" },
  "8-24": { quote: "Shukr means gratitude — say it with your whole heart.", ref: "", tradition: "muslim" },
  "8-25": { quote: "Everything in the heavens and earth praises Allah.", ref: "Quran 57:1", tradition: "muslim" },
  "8-26": { quote: "Share your lunch with a friend who forgot theirs.", ref: "", tradition: "muslim" },
  "8-27": { quote: "Even the tiny spider builds its web by Allah's wisdom.", ref: "Quran 29:41", tradition: "muslim" },
  "8-28": { quote: "When you eat honey, remember Allah gave the bee its skill.", ref: "Quran 16:69", tradition: "muslim" },
  "8-29": { quote: "Be grateful when the sun rises — a new day is a new blessing.", ref: "", tradition: "muslim" },
  "8-30": { quote: "The moon follows a path that Allah set for it.", ref: "Quran 36:39", tradition: "muslim" },
  "8-31": { quote: "Allah made the earth a resting place for you.", ref: "Quran 2:22", tradition: "muslim" },

  // ── September — Back to school, knowledge, learning ─────────────────
  "9-1": { quote: "Say Bismillah before you start anything new.", ref: "", tradition: "muslim" },
  "9-2": { quote: "Allah taught humans what they did not know.", ref: "Quran 96:5", tradition: "muslim" },
  "9-3": { quote: "Be a good student — learning is worship.", ref: "", tradition: "muslim" },
  "9-4": { quote: "The first word revealed to the Prophet was: Read!", ref: "Quran 96:1", tradition: "muslim" },
  "9-5": { quote: "Ask questions and explore — that is how you learn about Allah's world.", ref: "", tradition: "muslim" },
  "9-6": { quote: "A wise person never stops learning.", ref: "", tradition: "muslim" },
  "9-7": { quote: "Be kind to your classmates — everyone is learning.", ref: "", tradition: "muslim" },
  "9-8": { quote: "The pen is one of Allah's greatest gifts.", ref: "Quran 96:4", tradition: "muslim" },
  "9-9": { quote: "Help a friend with their work — teaching is charity.", ref: "Muslim", tradition: "muslim" },
  "9-10": { quote: "Allah gave you a brain to think and a heart to feel.", ref: "Quran 22:46", tradition: "muslim" },
  "9-11": { quote: "Make dua for your teachers — they guide you with love.", ref: "", tradition: "muslim" },
  "9-12": { quote: "Listen carefully and you will learn amazing things.", ref: "", tradition: "muslim" },
  "9-13": { quote: "Prophet Muhammad said: I was sent as a teacher.", ref: "Ibn Majah", tradition: "muslim" },
  "9-14": { quote: "Writing is a gift — practice your letters every day.", ref: "", tradition: "muslim" },
  "9-15": { quote: "Be patient — Allah is with those who are patient.", ref: "Quran 2:153", tradition: "muslim" },
  "9-16": { quote: "Numbers and counting are part of Allah's order in the world.", ref: "", tradition: "muslim" },
  "9-17": { quote: "Allah taught Adam the names of all things.", ref: "Quran 2:31", tradition: "muslim" },
  "9-18": { quote: "Try your best and leave the rest to Allah.", ref: "Tirmidhi", tradition: "muslim" },
  "9-19": { quote: "Be organized — Allah loves those who keep things in order.", ref: "", tradition: "muslim" },
  "9-20": { quote: "A book is a friend that never leaves you.", ref: "", tradition: "muslim" },
  "9-21": { quote: "The Quran is the best book — read it every day.", ref: "Bukhari", tradition: "muslim" },
  "9-22": { quote: "Luqman taught his son to be wise and grateful.", ref: "Quran 31:12", tradition: "muslim" },
  "9-23": { quote: "Practice makes perfect — keep trying!", ref: "", tradition: "muslim" },
  "9-24": { quote: "Share what you learn with others.", ref: "", tradition: "muslim" },
  "9-25": { quote: "Allah raises the rank of those who have knowledge.", ref: "Quran 58:11", tradition: "muslim" },
  "9-26": { quote: "Color, draw, and create — creativity is from Allah.", ref: "", tradition: "muslim" },
  "9-27": { quote: "Say Alhamdulillah when you learn something new.", ref: "", tradition: "muslim" },
  "9-28": { quote: "A scholar's journey starts with a single question.", ref: "", tradition: "muslim" },
  "9-29": { quote: "Ibrahim asked Allah to show him how things work.", ref: "Quran 2:260", tradition: "muslim" },
  "9-30": { quote: "Every day you learn, you grow closer to Allah.", ref: "", tradition: "muslim" },

  // ── October — Harvest, blessings, sharing ───────────────────────────
  "10-1": { quote: "Allah brings the harvest from the earth for you.", ref: "Quran 6:99", tradition: "muslim" },
  "10-2": { quote: "Share the gifts of the earth with everyone.", ref: "", tradition: "muslim" },
  "10-3": { quote: "Olives and dates are blessed foods from Allah.", ref: "Quran 6:141", tradition: "muslim" },
  "10-4": { quote: "Say Bismillah when you eat and Alhamdulillah when you finish.", ref: "Bukhari", tradition: "muslim" },
  "10-5": { quote: "A garden that feeds others is a gift that keeps giving.", ref: "Muslim", tradition: "muslim" },
  "10-6": { quote: "Never waste food — it is a blessing from Allah.", ref: "Ibn Majah", tradition: "muslim" },
  "10-7": { quote: "Allah sends rain from the sky to make plants grow.", ref: "Quran 50:9", tradition: "muslim" },
  "10-8": { quote: "Be thankful for bread — many people worked to make it.", ref: "", tradition: "muslim" },
  "10-9": { quote: "The earth grows food because Allah commands it.", ref: "Quran 80:27", tradition: "muslim" },
  "10-10": { quote: "Pack extra snacks to share with a friend.", ref: "", tradition: "muslim" },
  "10-11": { quote: "Pomegranates are mentioned in the Quran — taste their sweetness.", ref: "Quran 55:68", tradition: "muslim" },
  "10-12": { quote: "Tawakkul means trusting Allah with all your heart.", ref: "Quran 65:3", tradition: "muslim" },
  "10-13": { quote: "The leaves change color because Allah paints the world.", ref: "", tradition: "muslim" },
  "10-14": { quote: "Giving food to the hungry is one of the best deeds.", ref: "Bukhari", tradition: "muslim" },
  "10-15": { quote: "Allah gives rizq to every living creature.", ref: "Quran 11:6", tradition: "muslim" },
  "10-16": { quote: "Grapes, figs, and olives are gifts from Allah's garden.", ref: "Quran 16:11", tradition: "muslim" },
  "10-17": { quote: "Thank the farmer who grows your food.", ref: "", tradition: "muslim" },
  "10-18": { quote: "Contentment is a treasure that never runs out.", ref: "Bukhari", tradition: "muslim" },
  "10-19": { quote: "Allah turns the green leaves to gold in autumn.", ref: "", tradition: "muslim" },
  "10-20": { quote: "Look at the trees — they bow to Allah in the wind.", ref: "Quran 22:18", tradition: "muslim" },
  "10-21": { quote: "Cook a meal with your family and eat together.", ref: "", tradition: "muslim" },
  "10-22": { quote: "The Prophet loved dates — they are sweet and healthy.", ref: "Bukhari", tradition: "muslim" },
  "10-23": { quote: "Help gather food for those who need it.", ref: "", tradition: "muslim" },
  "10-24": { quote: "Allah provides for the birds — they go out hungry and return full.", ref: "Tirmidhi", tradition: "muslim" },
  "10-25": { quote: "Seeds sleep in the earth and Allah wakes them up in spring.", ref: "Quran 36:33", tradition: "muslim" },
  "10-26": { quote: "A warm cup of milk is a simple blessing from Allah.", ref: "", tradition: "muslim" },
  "10-27": { quote: "Barley, wheat, and corn all grow by Allah's command.", ref: "Quran 80:27", tradition: "muslim" },
  "10-28": { quote: "Even the smallest blessing deserves your thanks.", ref: "", tradition: "muslim" },
  "10-29": { quote: "Allah provides everything you need.", ref: "Quran 14:34", tradition: "muslim" },
  "10-30": { quote: "Share your blanket on a cold night — it warms two hearts.", ref: "", tradition: "muslim" },
  "10-31": { quote: "Wrap up warm — Allah made wool and cotton to keep you cozy.", ref: "Quran 16:80", tradition: "muslim" },

  // ── November — Thankfulness, community, giving ──────────────────────
  "11-1": { quote: "Shukr is the key to more blessings.", ref: "Quran 14:7", tradition: "muslim" },
  "11-2": { quote: "Thank the people around you — those who are not grateful to people are not grateful to Allah.", ref: "Abu Dawud", tradition: "muslim" },
  "11-3": { quote: "Allah loves those who give thanks.", ref: "Quran 39:7", tradition: "muslim" },
  "11-4": { quote: "Write down three things you are thankful for today.", ref: "", tradition: "muslim" },
  "11-5": { quote: "A grateful heart is always happy.", ref: "", tradition: "muslim" },
  "11-6": { quote: "Give charity and your wealth will never decrease.", ref: "Muslim", tradition: "muslim" },
  "11-7": { quote: "Be thankful for the roof over your head.", ref: "", tradition: "muslim" },
  "11-8": { quote: "Duas made for others are the most beautiful prayers.", ref: "Muslim", tradition: "muslim" },
  "11-9": { quote: "Allah gave you two hands — one to receive and one to give.", ref: "", tradition: "muslim" },
  "11-10": { quote: "A warm meal shared together is better than a feast eaten alone.", ref: "", tradition: "muslim" },
  "11-11": { quote: "Be a helper in your community — that is true faith.", ref: "", tradition: "muslim" },
  "11-12": { quote: "The Prophet never turned away anyone who asked for help.", ref: "Bukhari", tradition: "muslim" },
  "11-13": { quote: "Even a small act of kindness can change someone's whole day.", ref: "", tradition: "muslim" },
  "11-14": { quote: "Thank Allah for your health — it is your greatest treasure.", ref: "Bukhari", tradition: "muslim" },
  "11-15": { quote: "Volunteering your time is one of the best forms of charity.", ref: "", tradition: "muslim" },
  "11-16": { quote: "Be a peacemaker — Allah loves those who make peace.", ref: "Quran 49:9", tradition: "muslim" },
  "11-17": { quote: "Open your home to guests — it brings baraka.", ref: "Bukhari", tradition: "muslim" },
  "11-18": { quote: "When you say thank you, you are also thanking Allah.", ref: "", tradition: "muslim" },
  "11-19": { quote: "Hold the door for someone and smile.", ref: "", tradition: "muslim" },
  "11-20": { quote: "Sadaqah jariyah is a gift that keeps on giving.", ref: "Muslim", tradition: "muslim" },
  "11-21": { quote: "Thank Allah for your eyes, your ears, and your voice.", ref: "Quran 67:23", tradition: "muslim" },
  "11-22": { quote: "A thankful person finds joy in every moment.", ref: "", tradition: "muslim" },
  "11-23": { quote: "Allah is Ash-Shakoor — the Most Appreciative of your good deeds.", ref: "Quran 35:30", tradition: "muslim" },
  "11-24": { quote: "Gather with your family and say Alhamdulillah together.", ref: "", tradition: "muslim" },
  "11-25": { quote: "Feeding others is one of the highest forms of worship.", ref: "Bukhari", tradition: "muslim" },
  "11-26": { quote: "Thank your grandparents for their love and wisdom.", ref: "", tradition: "muslim" },
  "11-27": { quote: "Every breath you take is a reason to thank Allah.", ref: "", tradition: "muslim" },
  "11-28": { quote: "Charity does not decrease your wealth — it increases it.", ref: "Muslim", tradition: "muslim" },
  "11-29": { quote: "Smile at a stranger and brighten their day.", ref: "Tirmidhi", tradition: "muslim" },
  "11-30": { quote: "End the month with gratitude and start the next with hope.", ref: "", tradition: "muslim" },

  // ── December — Light, hope, reflection, new year ────────────────────
  "12-1": { quote: "Allah is the Light of the heavens and the earth.", ref: "Quran 24:35", tradition: "muslim" },
  "12-2": { quote: "In the cold, remember those without warm clothes — share what you can.", ref: "", tradition: "muslim" },
  "12-3": { quote: "The night sky is filled with stars that Allah placed there.", ref: "Quran 67:5", tradition: "muslim" },
  "12-4": { quote: "Wrap your loved ones in warm hugs — that is charity too.", ref: "", tradition: "muslim" },
  "12-5": { quote: "Even in winter, Allah is preparing the spring.", ref: "", tradition: "muslim" },
  "12-6": { quote: "A candle shares its light without losing any — be like a candle.", ref: "", tradition: "muslim" },
  "12-7": { quote: "Allah is Ar-Rahman — the Most Gracious to all creation.", ref: "Quran 1:3", tradition: "muslim" },
  "12-8": { quote: "Keep warm and thank Allah for the gift of fire.", ref: "Quran 56:71", tradition: "muslim" },
  "12-9": { quote: "Isa (Jesus) was a prophet of Allah who healed the sick.", ref: "Quran 3:49", tradition: "muslim" },
  "12-10": { quote: "Be kind to travelers and those far from home.", ref: "Quran 2:177", tradition: "muslim" },
  "12-11": { quote: "Allah turns the long night into day again — always have hope.", ref: "Quran 3:27", tradition: "muslim" },
  "12-12": { quote: "Maryam was the best of all women — strong and faithful.", ref: "Quran 3:42", tradition: "muslim" },
  "12-13": { quote: "Gather around the fire and tell stories of the prophets.", ref: "", tradition: "muslim" },
  "12-14": { quote: "Give warm clothes to someone who needs them.", ref: "", tradition: "muslim" },
  "12-15": { quote: "The winter rain is a mercy from Allah.", ref: "Quran 42:28", tradition: "muslim" },
  "12-16": { quote: "Reflect on the year — what good deeds have you done?", ref: "", tradition: "muslim" },
  "12-17": { quote: "Hot soup on a cold day is a simple mercy from Allah.", ref: "", tradition: "muslim" },
  "12-18": { quote: "Your family is a garden — water it with love and kindness.", ref: "", tradition: "muslim" },
  "12-19": { quote: "Snow is a blanket that Allah lays on the earth.", ref: "", tradition: "muslim" },
  "12-20": { quote: "Ask Allah to forgive your mistakes and start fresh.", ref: "Quran 3:135", tradition: "muslim" },
  "12-21": { quote: "The shortest day reminds us to cherish every moment of light.", ref: "", tradition: "muslim" },
  "12-22": { quote: "Make a warm drink for someone you love.", ref: "", tradition: "muslim" },
  "12-23": { quote: "Allah is Al-Wadud — the Most Loving.", ref: "Quran 85:14", tradition: "muslim" },
  "12-24": { quote: "Every prophet taught love, mercy, and kindness.", ref: "", tradition: "muslim" },
  "12-25": { quote: "Isa (Jesus) is honored in Islam as a great prophet of Allah.", ref: "Quran 19:30", tradition: "muslim" },
  "12-26": { quote: "Be extra generous this time of year — give what you can.", ref: "", tradition: "muslim" },
  "12-27": { quote: "Reflect on the past year and thank Allah for His blessings.", ref: "", tradition: "muslim" },
  "12-28": { quote: "Make a list of good deeds you want to do next year.", ref: "", tradition: "muslim" },
  "12-29": { quote: "Allah's mercy is greater than any mistake you could ever make.", ref: "Quran 39:53", tradition: "muslim" },
  "12-30": { quote: "Tonight, make dua for a blessed new year.", ref: "", tradition: "muslim" },
  "12-31": { quote: "Thank Allah for this whole year — every single day was a gift.", ref: "", tradition: "muslim" },
};
