import { AffirmationMap } from '../../types';

// Gita, Ramayana, Mahabharata, Upanishads quotes
// Extracted from v1 HINDU_AFFIRMATIONS

export const hinduAffirmations: AffirmationMap = {
  "1-2": { quote: "Give thanks for this new day — it is a gift.", ref: "", tradition: "hindu" },
  "1-4": { quote: "Do good without wanting a reward. That is the highest path.", ref: "Gita 3:19", tradition: "hindu" },
  "1-6": { quote: "Wise ones follow the light wherever it leads them.", ref: "Upanishads", tradition: "hindu" },
  "1-8": { quote: "Love all beings — God lives inside every heart.", ref: "Gita 13:28", tradition: "hindu" },
  "1-10": { quote: "Giving to others is the greatest form of worship.", ref: "Gita 17:20", tradition: "hindu" },
  "1-12": { quote: "Patience is the greatest virtue. Wait, and good will come.", ref: "Mahabharata", tradition: "hindu" },
  "1-16": { quote: "Every good thing in this world comes from the Divine.", ref: "Gita 10:41", tradition: "hindu" },
  "1-18": { quote: "Speak gently. Words have great power.", ref: "Gita 17:15", tradition: "hindu" },
  "1-20": { quote: "Joy lives inside you — it does not need anything from outside.", ref: "Gita 5:21", tradition: "hindu" },
  "1-22": { quote: "Be grateful for everything. Gratitude opens the door to joy.", ref: "Upanishads", tradition: "hindu" },
  "1-24": { quote: "God is with you always — inside your own heart.", ref: "Gita 18:61", tradition: "hindu" },
  "1-26": { quote: "You can do anything when you act from love, not fear.", ref: "Gita 18:66", tradition: "hindu" },
  "1-28": { quote: "Be kind to yourself. The Divine loves you completely.", ref: "Gita 9:29", tradition: "hindu" },
  "2-2": { quote: "Help others carry what is heavy. That is dharma.", ref: "Mahabharata", tradition: "hindu" },
  "2-4": { quote: "Love your family with your whole heart — that is devotion.", ref: "Gita 12:13", tradition: "hindu" },
  "2-6": { quote: "A generous heart is the greatest treasure.", ref: "Gita 16:1", tradition: "hindu" },
  "2-8": { quote: "You are loved beyond all measure — always and forever.", ref: "Gita 9:29", tradition: "hindu" },
  "2-10": { quote: "Love is the bridge between you and all of creation.", ref: "Gita 12:13", tradition: "hindu" },
  "2-12": { quote: "Sing to God with a joyful heart — music is a prayer.", ref: "Bhagavatam", tradition: "hindu" },
  "2-14": { quote: "Pure love is the most powerful force in the universe.", ref: "Gita 12:20", tradition: "hindu" },
  "2-16": { quote: "Pray with a pure heart and God will always hear you.", ref: "Gita 9:26", tradition: "hindu" },
  "2-18": { quote: "God made this world beautiful as a gift of love.", ref: "Upanishads", tradition: "hindu" },
  "2-20": { quote: "Let go of anger. A peaceful heart is a happy heart.", ref: "Gita 16:2", tradition: "hindu" },
  "2-22": { quote: "Truth is the highest virtue. Always speak the truth.", ref: "Mahabharata", tradition: "hindu" },
  "2-24": { quote: "Whatever you do, do it as an offering to God.", ref: "Gita 9:27", tradition: "hindu" },
  "2-26": { quote: "Peace begins in your own heart. Nurture it every day.", ref: "Gita 6:7", tradition: "hindu" },
  "3-4": { quote: "The Divine is dressed in light and wears the universe as a garment.", ref: "Upanishads", tradition: "hindu" },
  "3-6": { quote: "Sing to God! Music carries prayers straight to heaven.", ref: "Bhagavatam", tradition: "hindu" },
  "3-8": { quote: "A mother's love is the closest thing to God's love on earth.", ref: "Mahabharata", tradition: "hindu" },
  "3-10": { quote: "Water is sacred. It gives life to all living things.", ref: "Rigveda", tradition: "hindu" },
  "3-12": { quote: "Laughter is a prayer. Joy is devotion.", ref: "Bhagavatam", tradition: "hindu" },
  "3-14": { quote: "Nature is God's temple. Every flower is an offering.", ref: "Upanishads", tradition: "hindu" },
  "3-16": { quote: "Do good deeds quietly. God sees everything.", ref: "Gita 9:26", tradition: "hindu" },
  "3-18": { quote: "Stand up for what is right, just as Rama always did.", ref: "Ramayana", tradition: "hindu" },
  "3-20": { quote: "Everything is born, grows, and is born again — like spring.", ref: "Gita 2:22", tradition: "hindu" },
  "3-22": { quote: "You are made of light. Let it shine on everyone around you.", ref: "Upanishads", tradition: "hindu" },
  "3-24": { quote: "Lift others up with your words — that is seva, selfless service.", ref: "Gita 3:19", tradition: "hindu" },
  "3-26": { quote: "Good deeds done in secret are the purest kind.", ref: "Gita 17:20", tradition: "hindu" },
  "3-28": { quote: "Offer all your work to God and you will always find peace.", ref: "Gita 9:27", tradition: "hindu" },
  "4-2": { quote: "Serve others as if you are serving God — that is devotion.", ref: "Gita 12:13", tradition: "hindu" },
  "4-4": { quote: "God is always creating new beauty. Open your eyes to see it.", ref: "Gita 10:41", tradition: "hindu" },
  "4-6": { quote: "Be joyful! The Divine is dancing inside your heart.", ref: "Bhagavatam", tradition: "hindu" },
  "4-8": { quote: "Rain is a blessing from heaven. Dance in it gratefully!", ref: "Rigveda", tradition: "hindu" },
  "4-10": { quote: "The soul is like a butterfly — it is always becoming.", ref: "Gita 2:22", tradition: "hindu" },
  "4-12": { quote: "Serve your family lovingly. That is the highest worship.", ref: "Gita 3:19", tradition: "hindu" },
  "4-14": { quote: "A smiling face is the most beautiful face of all.", ref: "Mahabharata", tradition: "hindu" },
  "4-16": { quote: "Love everyone you meet. God lives inside every being.", ref: "Gita 13:28", tradition: "hindu" },
  "4-18": { quote: "God feeds every bird and fish. He will take care of you too.", ref: "Gita 9:22", tradition: "hindu" },
  "4-20": { quote: "Do your very best and offer the results to God.", ref: "Gita 3:30", tradition: "hindu" },
  "4-22": { quote: "The earth is our mother. Take care of her with love.", ref: "Atharva Veda", tradition: "hindu" },
  "4-24": { quote: "Celebrate the goodness in others — that is pure love.", ref: "Gita 12:16", tradition: "hindu" },
  "4-26": { quote: "God shaped you with love from the clay of the earth.", ref: "Upanishads", tradition: "hindu" },
  "4-28": { quote: "Bear others' pain with a compassionate heart.", ref: "Gita 12:13", tradition: "hindu" },
  "4-30": { quote: "Every day is a gift. Be grateful for each one.", ref: "Upanishads", tradition: "hindu" },
  "5-2": { quote: "Flowers are God's smile at the world. Give one today.", ref: "Upanishads", tradition: "hindu" },
  "5-4": { quote: "The sun is God's face shining on us with love.", ref: "Rigveda", tradition: "hindu" },
  "5-6": { quote: "The soul is always growing more beautiful, like a flower.", ref: "Gita 2:22", tradition: "hindu" },
  "5-8": { quote: "Bees teach us to work hard and share our sweetness.", ref: "Mahabharata", tradition: "hindu" },
  "5-10": { quote: "Work with full effort and offer it all to God.", ref: "Gita 3:19", tradition: "hindu" },
  "5-12": { quote: "Sweet words are a gift. Give them freely.", ref: "Gita 17:15", tradition: "hindu" },
  "5-14": { quote: "Every gift you give is an offering to the Divine.", ref: "Gita 9:26", tradition: "hindu" },
  "5-16": { quote: "Be brave like Hanuman — love gives you great strength.", ref: "Ramayana", tradition: "hindu" },
  "5-18": { quote: "Dancing and singing are offerings of joy to God.", ref: "Bhagavatam", tradition: "hindu" },
  "5-20": { quote: "Your spirit is free and high like a kite in the sky.", ref: "Upanishads", tradition: "hindu" },
  "5-22": { quote: "Rest in God's arms like a child. You are always safe.", ref: "Gita 18:66", tradition: "hindu" },
  "5-24": { quote: "Leap with joy! The Divine loves to see you happy.", ref: "Bhagavatam", tradition: "hindu" },
  "5-26": { quote: "Serving the community is serving God.", ref: "Gita 3:19", tradition: "hindu" },
  "5-28": { quote: "Learning is a sacred duty. Honor your teachers.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "5-30": { quote: "God has wonderful things planned for you — trust the path.", ref: "Gita 18:66", tradition: "hindu" },
  "6-2": { quote: "The ocean is vast — and so is God's love for you.", ref: "Upanishads", tradition: "hindu" },
  "6-4": { quote: "Choose joy in all things. Joy is devotion.", ref: "Bhagavatam", tradition: "hindu" },
  "6-6": { quote: "Surya, the sun, blesses us with light and warmth each morning.", ref: "Rigveda", tradition: "hindu" },
  "6-8": { quote: "The river always finds its way to the ocean — so will you.", ref: "Upanishads", tradition: "hindu" },
  "6-10": { quote: "Nritya — sacred dance — is a prayer of the whole body.", ref: "Bhagavatam", tradition: "hindu" },
  "6-12": { quote: "Indra's rainbow is a promise that beauty follows rain.", ref: "Rigveda", tradition: "hindu" },
  "6-14": { quote: "Sweetness is a gift from God. Enjoy it with gratitude.", ref: "Gita 17:9", tradition: "hindu" },
  "6-16": { quote: "All living things praise God — the dolphins leap for joy!", ref: "Bhagavatam", tradition: "hindu" },
  "6-18": { quote: "Varuna holds the sky in place. God holds you too.", ref: "Rigveda", tradition: "hindu" },
  "6-20": { quote: "The ocean shows us how vast God's love truly is.", ref: "Upanishads", tradition: "hindu" },
  "6-22": { quote: "Sweetness is everywhere when your heart is open.", ref: "Gita 5:21", tradition: "hindu" },
  "6-24": { quote: "Flowers offered with love are the greatest gift to God.", ref: "Gita 9:26", tradition: "hindu" },
  "6-26": { quote: "Build your life on a strong foundation of love and truth.", ref: "Mahabharata", tradition: "hindu" },
  "6-28": { quote: "Stay steady and calm — the Divine is your anchor.", ref: "Gita 6:19", tradition: "hindu" },
  "6-30": { quote: "May you go in peace. May peace follow you everywhere.", ref: "Upanishads", tradition: "hindu" },
  "7-2": { quote: "Let your goodness shine like a flag for all to see.", ref: "Gita 10:41", tradition: "hindu" },
  "7-4": { quote: "True freedom comes from knowing God lives inside you.", ref: "Gita 18:66", tradition: "hindu" },
  "7-6": { quote: "Celebrate life! The Divine loves your joyful heart.", ref: "Bhagavatam", tradition: "hindu" },
  "7-8": { quote: "The earth holds you gently. You are always supported.", ref: "Atharva Veda", tradition: "hindu" },
  "7-10": { quote: "Let goodness flow like a great river into the world.", ref: "Mahabharata", tradition: "hindu" },
  "7-12": { quote: "Rest peacefully. God watches over you day and night.", ref: "Gita 9:22", tradition: "hindu" },
  "7-14": { quote: "Every beautiful thing in nature is a gift from God.", ref: "Gita 10:41", tradition: "hindu" },
  "7-16": { quote: "Savor every sweet moment — God put it there for you.", ref: "Gita 5:21", tradition: "hindu" },
  "7-18": { quote: "God crowns the year with beauty. You are part of that beauty.", ref: "Rigveda", tradition: "hindu" },
  "7-20": { quote: "Build your life on truth, love, and service to others.", ref: "Mahabharata", tradition: "hindu" },
  "7-22": { quote: "Nurture what is growing — in the garden and in your heart.", ref: "Gita 3:8", tradition: "hindu" },
  "7-24": { quote: "The earth feeds us. Give thanks to her with every meal.", ref: "Atharva Veda", tradition: "hindu" },
  "7-26": { quote: "Sharing is the most natural expression of love.", ref: "Gita 17:20", tradition: "hindu" },
  "7-28": { quote: "The clouds carry rain as a blessing from Indra above.", ref: "Rigveda", tradition: "hindu" },
  "7-30": { quote: "God's light shines everywhere — even in the firefly's glow.", ref: "Gita 10:36", tradition: "hindu" },
  "8-2": { quote: "Learning is sacred. Your teacher is a form of God.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "8-4": { quote: "Be kind to those who teach you. Knowledge is a great gift.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "8-6": { quote: "Begin each day with gratitude and a joyful heart.", ref: "Bhagavatam", tradition: "hindu" },
  "8-8": { quote: "God made you exactly the right size — perfectly and lovingly.", ref: "Upanishads", tradition: "hindu" },
  "8-10": { quote: "Face the sun and let God's light fill your whole heart.", ref: "Rigveda", tradition: "hindu" },
  "8-12": { quote: "You are always growing and becoming more beautiful.", ref: "Gita 2:22", tradition: "hindu" },
  "8-14": { quote: "Water is sacred. Care for all of creation with love.", ref: "Rigveda", tradition: "hindu" },
  "8-16": { quote: "Leap with joy — the Divine loves to see you happy!", ref: "Bhagavatam", tradition: "hindu" },
  "8-18": { quote: "God painted the world in every color of the rainbow.", ref: "Upanishads", tradition: "hindu" },
  "8-20": { quote: "Every season is sacred. This one too.", ref: "Gita 2:14", tradition: "hindu" },
  "8-22": { quote: "A tiny seed holds the whole tree inside it — so do you.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "8-24": { quote: "The bee collects sweetness wherever it goes. So can you.", ref: "Mahabharata", tradition: "hindu" },
  "8-26": { quote: "Create with your hands as an offering to God.", ref: "Gita 3:9", tradition: "hindu" },
  "8-28": { quote: "Write down your dreams — God gave them to you.", ref: "Upanishads", tradition: "hindu" },
  "8-30": { quote: "Every season is a teacher. Say thank you to each one.", ref: "Gita 2:14", tradition: "hindu" },
  "9-2": { quote: "Nature's beauty is God's art — admire it with gratitude.", ref: "Upanishads", tradition: "hindu" },
  "9-4": { quote: "Approach learning with courage. Knowledge is sacred.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "9-6": { quote: "Each letter you write is a step on the path of wisdom.", ref: "Upanishads", tradition: "hindu" },
  "9-8": { quote: "Every tiny creature is a temple of the Divine.", ref: "Gita 13:28", tradition: "hindu" },
  "9-10": { quote: "God fills the world with good gifts. Gather them with joy.", ref: "Rigveda", tradition: "hindu" },
  "9-12": { quote: "Every creature, even a spider, is filled with God's wisdom.", ref: "Gita 13:28", tradition: "hindu" },
  "9-16": { quote: "The trees are dressed in gold for the joy of God.", ref: "Rigveda", tradition: "hindu" },
  "9-18": { quote: "God moves through the mist and clouds like a loving presence.", ref: "Upanishads", tradition: "hindu" },
  "9-20": { quote: "The earth gives her fruits with an open and loving hand.", ref: "Atharva Veda", tradition: "hindu" },
  "9-22": { quote: "Shout for joy! The whole creation shouts with you.", ref: "Bhagavatam", tradition: "hindu" },
  "9-24": { quote: "Inside you is the whole universe — you are made of stars.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "9-26": { quote: "Give freely and the universe will give back to you.", ref: "Gita 3:10", tradition: "hindu" },
  "9-28": { quote: "The moon is God's gentle light in the night sky.", ref: "Gita 10:21", tradition: "hindu" },
  "10-2": { quote: "Jump for joy! The whole creation celebrates with you.", ref: "Bhagavatam", tradition: "hindu" },
  "10-4": { quote: "Every creature is a child of God. Be kind to all of them.", ref: "Gita 13:28", tradition: "hindu" },
  "10-6": { quote: "Cooking for others is an act of love and devotion.", ref: "Gita 9:26", tradition: "hindu" },
  "10-8": { quote: "The pumpkin grew slowly and perfectly — just like you.", ref: "Upanishads", tradition: "hindu" },
  "10-10": { quote: "Watch the sky at dusk — God is painting just for you.", ref: "Rigveda", tradition: "hindu" },
  "10-12": { quote: "Create beauty from what nature gives you — that is sacred art.", ref: "Gita 3:9", tradition: "hindu" },
  "10-14": { quote: "Even something small holds all of God's greatness inside.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "10-16": { quote: "Crisp autumn air is God breathing freshness into the world.", ref: "Upanishads", tradition: "hindu" },
  "10-18": { quote: "Leap into joy — God delights in your happiness!", ref: "Bhagavatam", tradition: "hindu" },
  "10-20": { quote: "God fills the world with every color. Look and be amazed.", ref: "Rigveda", tradition: "hindu" },
  "10-24": { quote: "Make colorful patterns like Lakshmi's rangoli — for God's joy.", ref: "Diwali", tradition: "hindu" },
  "10-26": { quote: "Wisdom is the greatest color — wear it always.", ref: "Gita 4:38", tradition: "hindu" },
  "10-28": { quote: "Do not be afraid. God is with you always.", ref: "Gita 18:66", tradition: "hindu" },
  "10-30": { quote: "The stars are God's eyes watching over you with love.", ref: "Gita 10:21", tradition: "hindu" },
  "11-2": { quote: "Give thanks for the small things. They add up to everything.", ref: "Upanishads", tradition: "hindu" },
  "11-4": { quote: "Count your blessings. God has given you so very many.", ref: "Gita 16:1", tradition: "hindu" },
  "11-6": { quote: "The smell of good food is an offering to the Divine.", ref: "Gita 9:26", tradition: "hindu" },
  "11-10": { quote: "Your light is like a diya — it can light up the whole world.", ref: "Diwali", tradition: "hindu" },
  "11-12": { quote: "All trees rest and wake again — the soul is the same.", ref: "Gita 2:22", tradition: "hindu" },
  "11-14": { quote: "Prepare wisely for what is coming. That is the dharmic way.", ref: "Mahabharata", tradition: "hindu" },
  "11-16": { quote: "Even a pinecone holds a forest. You hold greatness too.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "11-18": { quote: "A loving hug is the warmest form of seva.", ref: "Mahabharata", tradition: "hindu" },
  "11-20": { quote: "Setting the table beautifully is an act of love and service.", ref: "Gita 3:19", tradition: "hindu" },
  "11-22": { quote: "Eat with gratitude. Every meal is prasad — a gift from God.", ref: "Gita 9:26", tradition: "hindu" },
  "11-24": { quote: "Honor your ancestors. Their love lives on inside you.", ref: "Mahabharata", tradition: "hindu" },
  "11-26": { quote: "Give thanks for all you have. Gratitude is the highest prayer.", ref: "Gita 16:1", tradition: "hindu" },
  "11-28": { quote: "Rest is sacred. Even God rests between acts of creation.", ref: "Upanishads", tradition: "hindu" },
  "11-30": { quote: "Give thanks for this whole month. Every day was a blessing.", ref: "Upanishads", tradition: "hindu" },
  "12-2": { quote: "Each snowflake is unique — God made you one of a kind too.", ref: "Upanishads", tradition: "hindu" },
  "12-4": { quote: "A lamp chases away darkness — just as love chases away fear.", ref: "Gita 10:11", tradition: "hindu" },
  "12-6": { quote: "Giving is an act of worship. Give something today.", ref: "Gita 17:20", tradition: "hindu" },
  "12-8": { quote: "Sweet things are gifts from God. Make and share them.", ref: "Gita 17:9", tradition: "hindu" },
  "12-10": { quote: "Your family is your first sangha — your first community of love.", ref: "Mahabharata", tradition: "hindu" },
  "12-12": { quote: "God counts every star and remembers every act of love.", ref: "Gita 10:21", tradition: "hindu" },
  "12-14": { quote: "Wrap your gifts with love. The love is the real present.", ref: "Gita 9:26", tradition: "hindu" },
  "12-16": { quote: "Peace is the greatest gift. Share it with everyone.", ref: "Gita 6:7", tradition: "hindu" },
  "12-18": { quote: "Making sweet things for others is a form of devotion.", ref: "Gita 9:26", tradition: "hindu" },
  "12-20": { quote: "Follow the light wherever it leads — it always leads to God.", ref: "Gita 10:11", tradition: "hindu" },
  "12-22": { quote: "Circle of lights, circle of love — God is in every ring.", ref: "Upanishads", tradition: "hindu" },
  "12-24": { quote: "On the eve of something wonderful, joy fills the whole sky.", ref: "Bhagavatam", tradition: "hindu" },
  "12-26": { quote: "Share your joy freely. Joy multiplies when it is given away.", ref: "Gita 5:21", tradition: "hindu" },
  "12-28": { quote: "Your inner light can never be put out. It shines forever.", ref: "Gita 2:20", tradition: "hindu" },
  "12-30": { quote: "Give thanks for every single day. Each one was a gift.", ref: "Upanishads", tradition: "hindu" },
};
