import { AffirmationMap } from '../../types';

// Gita, Ramayana, Mahabharata, Upanishads quotes
// Extracted from v1 HINDU_AFFIRMATIONS

export const hinduAffirmations: AffirmationMap = {
  // ===== JANUARY (31 days) — Winter, new beginnings =====
  "1-1": { quote: "A new year begins! Every sunrise is a fresh gift from God.", ref: "Rigveda", tradition: "hindu" },
  "1-2": { quote: "Give thanks for this new day — it is a gift.", ref: "", tradition: "hindu" },
  "1-3": { quote: "Your heart is a lamp. Let it glow with kindness today.", ref: "Upanishads", tradition: "hindu" },
  "1-4": { quote: "Do good without wanting a reward. That is the highest path.", ref: "Gita 3:19", tradition: "hindu" },
  "1-5": { quote: "The Divine sees all the good you do, even in secret.", ref: "Gita 9:26", tradition: "hindu" },
  "1-6": { quote: "Wise ones follow the light wherever it leads them.", ref: "Upanishads", tradition: "hindu" },
  "1-7": { quote: "Be steady like the mountains. God made you strong.", ref: "Gita 10:25", tradition: "hindu" },
  "1-8": { quote: "Love all beings — God lives inside every heart.", ref: "Gita 13:28", tradition: "hindu" },
  "1-9": { quote: "A warm blanket and a kind word both chase away the cold.", ref: "Mahabharata", tradition: "hindu" },
  "1-10": { quote: "Giving to others is the greatest form of worship.", ref: "Gita 17:20", tradition: "hindu" },
  "1-11": { quote: "Even in winter, the sun returns. Hope always shines again.", ref: "Rigveda", tradition: "hindu" },
  "1-12": { quote: "Patience is the greatest virtue. Wait, and good will come.", ref: "Mahabharata", tradition: "hindu" },
  "1-13": { quote: "Share your food with others. That is the sweetest offering.", ref: "Gita 9:26", tradition: "hindu" },
  "1-14": { quote: "Fly high like a kite! Your spirit is free and joyful.", ref: "Upanishads", tradition: "hindu" },
  "1-15": { quote: "A kind heart melts the coldest winter day.", ref: "Mahabharata", tradition: "hindu" },
  "1-16": { quote: "Every good thing in this world comes from the Divine.", ref: "Gita 10:41", tradition: "hindu" },
  "1-17": { quote: "Sit quietly and listen. God speaks in the silence.", ref: "Upanishads", tradition: "hindu" },
  "1-18": { quote: "Speak gently. Words have great power.", ref: "Gita 17:15", tradition: "hindu" },
  "1-19": { quote: "Like a river flowing to the sea, your love flows to all.", ref: "Upanishads", tradition: "hindu" },
  "1-20": { quote: "Joy lives inside you — it does not need anything from outside.", ref: "Gita 5:21", tradition: "hindu" },
  "1-21": { quote: "The fire inside you keeps you warm. That fire is the Divine.", ref: "Rigveda", tradition: "hindu" },
  "1-22": { quote: "Be grateful for everything. Gratitude opens the door to joy.", ref: "Upanishads", tradition: "hindu" },
  "1-23": { quote: "Help someone today. Helping is the truest form of prayer.", ref: "Gita 3:19", tradition: "hindu" },
  "1-24": { quote: "God is with you always — inside your own heart.", ref: "Gita 18:61", tradition: "hindu" },
  "1-25": { quote: "Every creature is part of one big family.", ref: "Gita 6:29", tradition: "hindu" },
  "1-26": { quote: "You can do anything when you act from love, not fear.", ref: "Gita 18:66", tradition: "hindu" },
  "1-27": { quote: "Be brave like Arjuna. Stand up for what is right.", ref: "Gita 2:3", tradition: "hindu" },
  "1-28": { quote: "Be kind to yourself. The Divine loves you completely.", ref: "Gita 9:29", tradition: "hindu" },
  "1-29": { quote: "The winter trees rest and wait. Soon they will bloom again.", ref: "Gita 2:22", tradition: "hindu" },
  "1-30": { quote: "Every act of love warms the world around you.", ref: "Mahabharata", tradition: "hindu" },
  "1-31": { quote: "This month was full of blessings. Carry them into the next.", ref: "Upanishads", tradition: "hindu" },

  // ===== FEBRUARY (28 days) — Love, devotion =====
  "2-1": { quote: "A new month begins with new blessings from God.", ref: "Upanishads", tradition: "hindu" },
  "2-2": { quote: "Help others carry what is heavy. That is dharma.", ref: "Mahabharata", tradition: "hindu" },
  "2-3": { quote: "Your smile is a lamp that lights up everyone around you.", ref: "Bhagavatam", tradition: "hindu" },
  "2-4": { quote: "Love your family with your whole heart — that is devotion.", ref: "Gita 12:13", tradition: "hindu" },
  "2-5": { quote: "God made your heart to love. Let it love freely.", ref: "Gita 12:20", tradition: "hindu" },
  "2-6": { quote: "A generous heart is the greatest treasure.", ref: "Gita 16:1", tradition: "hindu" },
  "2-7": { quote: "Friendship is one of God's most beautiful gifts.", ref: "Mahabharata", tradition: "hindu" },
  "2-8": { quote: "You are loved beyond all measure — always and forever.", ref: "Gita 9:29", tradition: "hindu" },
  "2-9": { quote: "Be like the lotus — bloom beautifully wherever you are.", ref: "Gita 5:10", tradition: "hindu" },
  "2-10": { quote: "Love is the bridge between you and all of creation.", ref: "Gita 12:13", tradition: "hindu" },
  "2-11": { quote: "A hug is a prayer your body makes. Give one today.", ref: "Mahabharata", tradition: "hindu" },
  "2-12": { quote: "Sing to God with a joyful heart — music is a prayer.", ref: "Bhagavatam", tradition: "hindu" },
  "2-13": { quote: "Kindness to animals is kindness to God.", ref: "Gita 13:28", tradition: "hindu" },
  "2-14": { quote: "Pure love is the most powerful force in the universe.", ref: "Gita 12:20", tradition: "hindu" },
  "2-15": { quote: "Hold your loved ones close. They are gifts from God.", ref: "Mahabharata", tradition: "hindu" },
  "2-16": { quote: "Pray with a pure heart and God will always hear you.", ref: "Gita 9:26", tradition: "hindu" },
  "2-17": { quote: "Your words can be soft like a flower. Choose them with care.", ref: "Gita 17:15", tradition: "hindu" },
  "2-18": { quote: "God made this world beautiful as a gift of love.", ref: "Upanishads", tradition: "hindu" },
  "2-19": { quote: "Even the smallest act of kindness ripples out forever.", ref: "Mahabharata", tradition: "hindu" },
  "2-20": { quote: "Let go of anger. A peaceful heart is a happy heart.", ref: "Gita 16:2", tradition: "hindu" },
  "2-21": { quote: "You are never alone. The Divine walks beside you always.", ref: "Gita 18:61", tradition: "hindu" },
  "2-22": { quote: "Truth is the highest virtue. Always speak the truth.", ref: "Mahabharata", tradition: "hindu" },
  "2-23": { quote: "Devotion is love in action. Show your love today.", ref: "Gita 12:2", tradition: "hindu" },
  "2-24": { quote: "Whatever you do, do it as an offering to God.", ref: "Gita 9:27", tradition: "hindu" },
  "2-25": { quote: "A gentle voice is sweeter than any music.", ref: "Gita 17:15", tradition: "hindu" },
  "2-26": { quote: "Peace begins in your own heart. Nurture it every day.", ref: "Gita 6:7", tradition: "hindu" },
  "2-27": { quote: "Share a story with someone you love. Stories are sacred.", ref: "Ramayana", tradition: "hindu" },
  "2-28": { quote: "Thank this month for all its love. A new one is coming.", ref: "Upanishads", tradition: "hindu" },

  // ===== MARCH (31 days) — Spring, Holi, renewal =====
  "3-1": { quote: "Spring is coming! The world is waking up with new life.", ref: "Rigveda", tradition: "hindu" },
  "3-2": { quote: "Every color in the world is a blessing from God.", ref: "Bhagavatam", tradition: "hindu" },
  "3-3": { quote: "Throw colors of joy into the sky — God loves to see you play!", ref: "Bhagavatam", tradition: "hindu" },
  "3-4": { quote: "The Divine is dressed in light and wears the universe as a garment.", ref: "Upanishads", tradition: "hindu" },
  "3-5": { quote: "Be colorful like Holi! Let your joy splash everywhere.", ref: "Bhagavatam", tradition: "hindu" },
  "3-6": { quote: "Sing to God! Music carries prayers straight to heaven.", ref: "Bhagavatam", tradition: "hindu" },
  "3-7": { quote: "New leaves on the trees are like new hopes in your heart.", ref: "Gita 2:22", tradition: "hindu" },
  "3-8": { quote: "A mother's love is the closest thing to God's love on earth.", ref: "Mahabharata", tradition: "hindu" },
  "3-9": { quote: "The birds sing because they are grateful. Sing with them!", ref: "Rigveda", tradition: "hindu" },
  "3-10": { quote: "Water is sacred. It gives life to all living things.", ref: "Rigveda", tradition: "hindu" },
  "3-11": { quote: "Plant a seed with love and watch God make it grow.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "3-12": { quote: "Laughter is a prayer. Joy is devotion.", ref: "Bhagavatam", tradition: "hindu" },
  "3-13": { quote: "The spring breeze carries blessings to everyone.", ref: "Rigveda", tradition: "hindu" },
  "3-14": { quote: "Nature is God's temple. Every flower is an offering.", ref: "Upanishads", tradition: "hindu" },
  "3-15": { quote: "Dance with joy like the peacock in the rain.", ref: "Bhagavatam", tradition: "hindu" },
  "3-16": { quote: "Do good deeds quietly. God sees everything.", ref: "Gita 9:26", tradition: "hindu" },
  "3-17": { quote: "Green is the color of new life. God paints the earth green in spring.", ref: "Rigveda", tradition: "hindu" },
  "3-18": { quote: "Stand up for what is right, just as Rama always did.", ref: "Ramayana", tradition: "hindu" },
  "3-19": { quote: "The butterfly was once a caterpillar. You are always becoming more.", ref: "Gita 2:22", tradition: "hindu" },
  "3-20": { quote: "Everything is born, grows, and is born again — like spring.", ref: "Gita 2:22", tradition: "hindu" },
  "3-21": { quote: "Open your arms wide to the new season. God has gifts for you.", ref: "Upanishads", tradition: "hindu" },
  "3-22": { quote: "You are made of light. Let it shine on everyone around you.", ref: "Upanishads", tradition: "hindu" },
  "3-23": { quote: "Every raindrop is a blessing falling from the sky.", ref: "Rigveda", tradition: "hindu" },
  "3-24": { quote: "Lift others up with your words — that is seva, selfless service.", ref: "Gita 3:19", tradition: "hindu" },
  "3-25": { quote: "The garden grows because God sends the sun and rain.", ref: "Rigveda", tradition: "hindu" },
  "3-26": { quote: "Good deeds done in secret are the purest kind.", ref: "Gita 17:20", tradition: "hindu" },
  "3-27": { quote: "Be gentle with every living thing. All life is sacred.", ref: "Gita 16:2", tradition: "hindu" },
  "3-28": { quote: "Offer all your work to God and you will always find peace.", ref: "Gita 9:27", tradition: "hindu" },
  "3-29": { quote: "The river sings as it flows. Let your heart sing too.", ref: "Rigveda", tradition: "hindu" },
  "3-30": { quote: "God hides wonders in every corner of the world. Go find them!", ref: "Upanishads", tradition: "hindu" },
  "3-31": { quote: "Spring has arrived! Thank God for this season of new life.", ref: "Rigveda", tradition: "hindu" },

  // ===== APRIL (30 days) — Spring, Ram Navami, growth =====
  "4-1": { quote: "April showers bring beautiful flowers. God sends both.", ref: "Rigveda", tradition: "hindu" },
  "4-2": { quote: "Serve others as if you are serving God — that is devotion.", ref: "Gita 12:13", tradition: "hindu" },
  "4-3": { quote: "Listen to the rain. It is the earth singing a thank-you song.", ref: "Rigveda", tradition: "hindu" },
  "4-4": { quote: "God is always creating new beauty. Open your eyes to see it.", ref: "Gita 10:41", tradition: "hindu" },
  "4-5": { quote: "A seedling pushes through the earth with courage. So can you.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "4-6": { quote: "Be joyful! The Divine is dancing inside your heart.", ref: "Bhagavatam", tradition: "hindu" },
  "4-7": { quote: "Rama always kept his promises. Keep yours too.", ref: "Ramayana", tradition: "hindu" },
  "4-8": { quote: "Rain is a blessing from heaven. Dance in it gratefully!", ref: "Rigveda", tradition: "hindu" },
  "4-9": { quote: "Every flower that opens is saying thank you to the sun.", ref: "Rigveda", tradition: "hindu" },
  "4-10": { quote: "The soul is like a butterfly — it is always becoming.", ref: "Gita 2:22", tradition: "hindu" },
  "4-11": { quote: "Help a plant grow today. Caring for nature is caring for God.", ref: "Atharva Veda", tradition: "hindu" },
  "4-12": { quote: "Serve your family lovingly. That is the highest worship.", ref: "Gita 3:19", tradition: "hindu" },
  "4-13": { quote: "The world is fresh and new after the rain. So is your heart.", ref: "Rigveda", tradition: "hindu" },
  "4-14": { quote: "A smiling face is the most beautiful face of all.", ref: "Mahabharata", tradition: "hindu" },
  "4-15": { quote: "Hanuman served with his whole heart. Serve with yours too.", ref: "Ramayana", tradition: "hindu" },
  "4-16": { quote: "Love everyone you meet. God lives inside every being.", ref: "Gita 13:28", tradition: "hindu" },
  "4-17": { quote: "Sita was brave and patient. You can be brave and patient too.", ref: "Ramayana", tradition: "hindu" },
  "4-18": { quote: "God feeds every bird and fish. He will take care of you too.", ref: "Gita 9:22", tradition: "hindu" },
  "4-19": { quote: "Watch the clouds float by. God holds them all in place.", ref: "Rigveda", tradition: "hindu" },
  "4-20": { quote: "Do your very best and offer the results to God.", ref: "Gita 3:30", tradition: "hindu" },
  "4-21": { quote: "A tree gives shade to everyone. Be generous like a tree.", ref: "Mahabharata", tradition: "hindu" },
  "4-22": { quote: "The earth is our mother. Take care of her with love.", ref: "Atharva Veda", tradition: "hindu" },
  "4-23": { quote: "Splash in the puddles! God made them just for you to enjoy.", ref: "Bhagavatam", tradition: "hindu" },
  "4-24": { quote: "Celebrate the goodness in others — that is pure love.", ref: "Gita 12:16", tradition: "hindu" },
  "4-25": { quote: "The frog sings after the rain. Sing your own joyful song!", ref: "Rigveda", tradition: "hindu" },
  "4-26": { quote: "God shaped you with love from the clay of the earth.", ref: "Upanishads", tradition: "hindu" },
  "4-27": { quote: "Share your umbrella. Sharing is an act of love.", ref: "Gita 17:20", tradition: "hindu" },
  "4-28": { quote: "Bear others' pain with a compassionate heart.", ref: "Gita 12:13", tradition: "hindu" },
  "4-29": { quote: "Look at the rainbow! God painted it just for you.", ref: "Rigveda", tradition: "hindu" },
  "4-30": { quote: "Every day is a gift. Be grateful for each one.", ref: "Upanishads", tradition: "hindu" },

  // ===== MAY (31 days) — Late spring, warmth, nature =====
  "5-1": { quote: "May brings warmth and flowers. God is smiling on the earth.", ref: "Rigveda", tradition: "hindu" },
  "5-2": { quote: "Flowers are God's smile at the world. Give one today.", ref: "Upanishads", tradition: "hindu" },
  "5-3": { quote: "Your mother is your first teacher. Honor her with love.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "5-4": { quote: "The sun is God's face shining on us with love.", ref: "Rigveda", tradition: "hindu" },
  "5-5": { quote: "Every garden grows because someone cared. Be someone who cares.", ref: "Gita 3:8", tradition: "hindu" },
  "5-6": { quote: "The soul is always growing more beautiful, like a flower.", ref: "Gita 2:22", tradition: "hindu" },
  "5-7": { quote: "Hold your mother's hand today. Her love is a form of God's love.", ref: "Mahabharata", tradition: "hindu" },
  "5-8": { quote: "Bees teach us to work hard and share our sweetness.", ref: "Mahabharata", tradition: "hindu" },
  "5-9": { quote: "The ladybug is tiny but full of God's beauty.", ref: "Gita 13:28", tradition: "hindu" },
  "5-10": { quote: "Work with full effort and offer it all to God.", ref: "Gita 3:19", tradition: "hindu" },
  "5-11": { quote: "A mother's heart never stops loving. Thank her today.", ref: "Mahabharata", tradition: "hindu" },
  "5-12": { quote: "Sweet words are a gift. Give them freely.", ref: "Gita 17:15", tradition: "hindu" },
  "5-13": { quote: "Chase a butterfly with your eyes. It carries a prayer on its wings.", ref: "Upanishads", tradition: "hindu" },
  "5-14": { quote: "Every gift you give is an offering to the Divine.", ref: "Gita 9:26", tradition: "hindu" },
  "5-15": { quote: "Sit under a tree and feel God's peace surround you.", ref: "Gita 6:11", tradition: "hindu" },
  "5-16": { quote: "Be brave like Hanuman — love gives you great strength.", ref: "Ramayana", tradition: "hindu" },
  "5-17": { quote: "The warm breeze is God's gentle hand on your cheek.", ref: "Rigveda", tradition: "hindu" },
  "5-18": { quote: "Dancing and singing are offerings of joy to God.", ref: "Bhagavatam", tradition: "hindu" },
  "5-19": { quote: "Watch the ants work together. Teamwork is a gift from God.", ref: "Mahabharata", tradition: "hindu" },
  "5-20": { quote: "Your spirit is free and high like a kite in the sky.", ref: "Upanishads", tradition: "hindu" },
  "5-21": { quote: "Pick a flower and thank God for its colors and smell.", ref: "Rigveda", tradition: "hindu" },
  "5-22": { quote: "Rest in God's arms like a child. You are always safe.", ref: "Gita 18:66", tradition: "hindu" },
  "5-23": { quote: "Play outside and feel God's world all around you.", ref: "Upanishads", tradition: "hindu" },
  "5-24": { quote: "Leap with joy! The Divine loves to see you happy.", ref: "Bhagavatam", tradition: "hindu" },
  "5-25": { quote: "The mango is sweet because God filled it with love.", ref: "Upanishads", tradition: "hindu" },
  "5-26": { quote: "Serving the community is serving God.", ref: "Gita 3:19", tradition: "hindu" },
  "5-27": { quote: "Every sunset is God saying goodnight with beauty.", ref: "Rigveda", tradition: "hindu" },
  "5-28": { quote: "Learning is a sacred duty. Honor your teachers.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "5-29": { quote: "Climb a tree and look at the world God made. It is beautiful!", ref: "Upanishads", tradition: "hindu" },
  "5-30": { quote: "God has wonderful things planned for you — trust the path.", ref: "Gita 18:66", tradition: "hindu" },
  "5-31": { quote: "This month was full of warmth and sunshine. Thank God for it all.", ref: "Upanishads", tradition: "hindu" },

  // ===== JUNE (30 days) — Summer, sun, water =====
  "6-1": { quote: "Summer is here! The long sunny days are God's gift.", ref: "Rigveda", tradition: "hindu" },
  "6-2": { quote: "The ocean is vast — and so is God's love for you.", ref: "Upanishads", tradition: "hindu" },
  "6-3": { quote: "Cool water on a hot day is a blessing from above.", ref: "Rigveda", tradition: "hindu" },
  "6-4": { quote: "Choose joy in all things. Joy is devotion.", ref: "Bhagavatam", tradition: "hindu" },
  "6-5": { quote: "Run and play in the sunshine. God delights in your laughter.", ref: "Bhagavatam", tradition: "hindu" },
  "6-6": { quote: "Surya, the sun, blesses us with light and warmth each morning.", ref: "Rigveda", tradition: "hindu" },
  "6-7": { quote: "Your father protects you with love. Honor him with kindness.", ref: "Mahabharata", tradition: "hindu" },
  "6-8": { quote: "The river always finds its way to the ocean — so will you.", ref: "Upanishads", tradition: "hindu" },
  "6-9": { quote: "Lie on the grass and look at the sky. God is above and below.", ref: "Gita 13:13", tradition: "hindu" },
  "6-10": { quote: "Nritya — sacred dance — is a prayer of the whole body.", ref: "Bhagavatam", tradition: "hindu" },
  "6-11": { quote: "A good friend is a treasure. Treasure your friends today.", ref: "Mahabharata", tradition: "hindu" },
  "6-12": { quote: "Indra's rainbow is a promise that beauty follows rain.", ref: "Rigveda", tradition: "hindu" },
  "6-13": { quote: "The firefly carries God's light in its tiny body.", ref: "Gita 10:36", tradition: "hindu" },
  "6-14": { quote: "Sweetness is a gift from God. Enjoy it with gratitude.", ref: "Gita 17:9", tradition: "hindu" },
  "6-15": { quote: "Splash in the water! Water is sacred and joyful.", ref: "Rigveda", tradition: "hindu" },
  "6-16": { quote: "All living things praise God — the dolphins leap for joy!", ref: "Bhagavatam", tradition: "hindu" },
  "6-17": { quote: "The longest day has the most sunshine. Fill it with love.", ref: "Rigveda", tradition: "hindu" },
  "6-18": { quote: "Varuna holds the sky in place. God holds you too.", ref: "Rigveda", tradition: "hindu" },
  "6-19": { quote: "Your father's love is strong like a great tree. Rest in its shade.", ref: "Mahabharata", tradition: "hindu" },
  "6-20": { quote: "The ocean shows us how vast God's love truly is.", ref: "Upanishads", tradition: "hindu" },
  "6-21": { quote: "Today the sun shines longest. Shine your light the longest too!", ref: "Rigveda", tradition: "hindu" },
  "6-22": { quote: "Sweetness is everywhere when your heart is open.", ref: "Gita 5:21", tradition: "hindu" },
  "6-23": { quote: "God made the stars to guide you, even on the darkest night.", ref: "Gita 10:21", tradition: "hindu" },
  "6-24": { quote: "Flowers offered with love are the greatest gift to God.", ref: "Gita 9:26", tradition: "hindu" },
  "6-25": { quote: "Eat the sweet fruits of summer. God grew them just for you.", ref: "Upanishads", tradition: "hindu" },
  "6-26": { quote: "Build your life on a strong foundation of love and truth.", ref: "Mahabharata", tradition: "hindu" },
  "6-27": { quote: "The parrot's bright colors show God's love of beauty.", ref: "Bhagavatam", tradition: "hindu" },
  "6-28": { quote: "Stay steady and calm — the Divine is your anchor.", ref: "Gita 6:19", tradition: "hindu" },
  "6-29": { quote: "Every creature finds its home. God has a home for you too.", ref: "Upanishads", tradition: "hindu" },
  "6-30": { quote: "May you go in peace. May peace follow you everywhere.", ref: "Upanishads", tradition: "hindu" },

  // ===== JULY (31 days) — Monsoon, rain, freedom =====
  "7-1": { quote: "The monsoon clouds gather. Rain is God's gift to the thirsty earth.", ref: "Rigveda", tradition: "hindu" },
  "7-2": { quote: "Let your goodness shine like a flag for all to see.", ref: "Gita 10:41", tradition: "hindu" },
  "7-3": { quote: "Dance in the rain! Every drop is a blessing from the sky.", ref: "Rigveda", tradition: "hindu" },
  "7-4": { quote: "True freedom comes from knowing God lives inside you.", ref: "Gita 18:66", tradition: "hindu" },
  "7-5": { quote: "The peacock dances when the rain falls. Dance with joy today!", ref: "Bhagavatam", tradition: "hindu" },
  "7-6": { quote: "Celebrate life! The Divine loves your joyful heart.", ref: "Bhagavatam", tradition: "hindu" },
  "7-7": { quote: "Listen to the thunder. It is God's drum beating with power.", ref: "Rigveda", tradition: "hindu" },
  "7-8": { quote: "The earth holds you gently. You are always supported.", ref: "Atharva Veda", tradition: "hindu" },
  "7-9": { quote: "The frog sings when the rains come. Sing your song of thanks!", ref: "Rigveda", tradition: "hindu" },
  "7-10": { quote: "Let goodness flow like a great river into the world.", ref: "Mahabharata", tradition: "hindu" },
  "7-11": { quote: "Puddles are little mirrors showing God's sky. Splash in them!", ref: "Upanishads", tradition: "hindu" },
  "7-12": { quote: "Rest peacefully. God watches over you day and night.", ref: "Gita 9:22", tradition: "hindu" },
  "7-13": { quote: "The lotus blooms in muddy water. Beauty rises from everywhere.", ref: "Gita 5:10", tradition: "hindu" },
  "7-14": { quote: "Every beautiful thing in nature is a gift from God.", ref: "Gita 10:41", tradition: "hindu" },
  "7-15": { quote: "The rain fills the rivers. Kindness fills your heart.", ref: "Rigveda", tradition: "hindu" },
  "7-16": { quote: "Savor every sweet moment — God put it there for you.", ref: "Gita 5:21", tradition: "hindu" },
  "7-17": { quote: "Watch the snail move slowly and patiently. Patience is wisdom.", ref: "Mahabharata", tradition: "hindu" },
  "7-18": { quote: "God crowns the year with beauty. You are part of that beauty.", ref: "Rigveda", tradition: "hindu" },
  "7-19": { quote: "The wet earth smells sweet after rain. Breathe in God's gift.", ref: "Rigveda", tradition: "hindu" },
  "7-20": { quote: "Build your life on truth, love, and service to others.", ref: "Mahabharata", tradition: "hindu" },
  "7-21": { quote: "An umbrella shared is love doubled. Share yours today.", ref: "Gita 17:20", tradition: "hindu" },
  "7-22": { quote: "Nurture what is growing — in the garden and in your heart.", ref: "Gita 3:8", tradition: "hindu" },
  "7-23": { quote: "The rainbow after the storm is God's smile in the sky.", ref: "Rigveda", tradition: "hindu" },
  "7-24": { quote: "The earth feeds us. Give thanks to her with every meal.", ref: "Atharva Veda", tradition: "hindu" },
  "7-25": { quote: "Jump over the puddles! Life is an adventure with God.", ref: "Bhagavatam", tradition: "hindu" },
  "7-26": { quote: "Sharing is the most natural expression of love.", ref: "Gita 17:20", tradition: "hindu" },
  "7-27": { quote: "The monsoon rain makes everything green and alive again.", ref: "Rigveda", tradition: "hindu" },
  "7-28": { quote: "The clouds carry rain as a blessing from Indra above.", ref: "Rigveda", tradition: "hindu" },
  "7-29": { quote: "Sit quietly and watch the rain fall. God is near.", ref: "Upanishads", tradition: "hindu" },
  "7-30": { quote: "God's light shines everywhere — even in the firefly's glow.", ref: "Gita 10:36", tradition: "hindu" },
  "7-31": { quote: "The monsoon month ends. Thank God for every raindrop.", ref: "Rigveda", tradition: "hindu" },

  // ===== AUGUST (31 days) — Late monsoon, Krishna Janmashtami, learning =====
  "8-1": { quote: "A new month of blessings begins. Open your heart to receive them.", ref: "Upanishads", tradition: "hindu" },
  "8-2": { quote: "Learning is sacred. Your teacher is a form of God.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "8-3": { quote: "Little Krishna loved butter and love. Share something sweet today.", ref: "Bhagavatam", tradition: "hindu" },
  "8-4": { quote: "Be kind to those who teach you. Knowledge is a great gift.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "8-5": { quote: "Krishna played his flute and the whole world listened with love.", ref: "Bhagavatam", tradition: "hindu" },
  "8-6": { quote: "Begin each day with gratitude and a joyful heart.", ref: "Bhagavatam", tradition: "hindu" },
  "8-7": { quote: "Respect your elders. Their wisdom is a treasure.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "8-8": { quote: "God made you exactly the right size — perfectly and lovingly.", ref: "Upanishads", tradition: "hindu" },
  "8-9": { quote: "The cow gives milk freely. Give your love freely too.", ref: "Mahabharata", tradition: "hindu" },
  "8-10": { quote: "Face the sun and let God's light fill your whole heart.", ref: "Rigveda", tradition: "hindu" },
  "8-11": { quote: "Tie a rakhi of love around your brother or sister's wrist.", ref: "Mahabharata", tradition: "hindu" },
  "8-12": { quote: "You are always growing and becoming more beautiful.", ref: "Gita 2:22", tradition: "hindu" },
  "8-13": { quote: "Brothers and sisters are God's way of giving you a forever friend.", ref: "Mahabharata", tradition: "hindu" },
  "8-14": { quote: "Water is sacred. Care for all of creation with love.", ref: "Rigveda", tradition: "hindu" },
  "8-15": { quote: "Freedom is a sacred gift. Be grateful for it every day.", ref: "Gita 18:66", tradition: "hindu" },
  "8-16": { quote: "Leap with joy — the Divine loves to see you happy!", ref: "Bhagavatam", tradition: "hindu" },
  "8-17": { quote: "Every book you read opens a door to God's wisdom.", ref: "Upanishads", tradition: "hindu" },
  "8-18": { quote: "God painted the world in every color of the rainbow.", ref: "Upanishads", tradition: "hindu" },
  "8-19": { quote: "A pencil in your hand is a tool for making beautiful things.", ref: "Upanishads", tradition: "hindu" },
  "8-20": { quote: "Every season is sacred. This one too.", ref: "Gita 2:14", tradition: "hindu" },
  "8-21": { quote: "Count the colors in a butterfly's wings. God painted each one.", ref: "Upanishads", tradition: "hindu" },
  "8-22": { quote: "A tiny seed holds the whole tree inside it — so do you.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "8-23": { quote: "Krishna lifted a whole mountain with one finger. Faith moves mountains!", ref: "Bhagavatam", tradition: "hindu" },
  "8-24": { quote: "The bee collects sweetness wherever it goes. So can you.", ref: "Mahabharata", tradition: "hindu" },
  "8-25": { quote: "Draw a picture for God today. Art is a prayer.", ref: "Gita 3:9", tradition: "hindu" },
  "8-26": { quote: "Create with your hands as an offering to God.", ref: "Gita 3:9", tradition: "hindu" },
  "8-27": { quote: "The monsoon rains are slowing. Thank God for the gift of water.", ref: "Rigveda", tradition: "hindu" },
  "8-28": { quote: "Write down your dreams — God gave them to you.", ref: "Upanishads", tradition: "hindu" },
  "8-29": { quote: "A new school year is a new adventure. Walk it with God.", ref: "Upanishads", tradition: "hindu" },
  "8-30": { quote: "Every season is a teacher. Say thank you to each one.", ref: "Gita 2:14", tradition: "hindu" },
  "8-31": { quote: "This month brought learning and love. Carry both into the next.", ref: "Taittiriya Upanishad", tradition: "hindu" },

  // ===== SEPTEMBER (30 days) — Harvest begins, Ganesh Chaturthi, learning =====
  "9-1": { quote: "A new month of harvest and joy. Thank God for the food we eat.", ref: "Rigveda", tradition: "hindu" },
  "9-2": { quote: "Nature's beauty is God's art — admire it with gratitude.", ref: "Upanishads", tradition: "hindu" },
  "9-3": { quote: "Ganesha removes all obstacles. Ask for his help today.", ref: "Bhagavatam", tradition: "hindu" },
  "9-4": { quote: "Approach learning with courage. Knowledge is sacred.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "9-5": { quote: "Your teacher opens the door. You walk through it with courage.", ref: "Taittiriya Upanishad", tradition: "hindu" },
  "9-6": { quote: "Each letter you write is a step on the path of wisdom.", ref: "Upanishads", tradition: "hindu" },
  "9-7": { quote: "Ganesha loves sweets and kindness. Offer both today.", ref: "Bhagavatam", tradition: "hindu" },
  "9-8": { quote: "Every tiny creature is a temple of the Divine.", ref: "Gita 13:28", tradition: "hindu" },
  "9-9": { quote: "The apple falls from the tree at just the right time. So will your dreams.", ref: "Upanishads", tradition: "hindu" },
  "9-10": { quote: "God fills the world with good gifts. Gather them with joy.", ref: "Rigveda", tradition: "hindu" },
  "9-11": { quote: "Be wise like Ganesha. Think before you act.", ref: "Mahabharata", tradition: "hindu" },
  "9-12": { quote: "Every creature, even a spider, is filled with God's wisdom.", ref: "Gita 13:28", tradition: "hindu" },
  "9-13": { quote: "The harvest moon shines bright. God lights the way for you.", ref: "Gita 10:21", tradition: "hindu" },
  "9-14": { quote: "Share the harvest with your neighbors. Sharing is dharma.", ref: "Gita 3:10", tradition: "hindu" },
  "9-15": { quote: "Every grain of rice is a gift from God. Eat with gratitude.", ref: "Gita 9:26", tradition: "hindu" },
  "9-16": { quote: "The trees are dressed in gold for the joy of God.", ref: "Rigveda", tradition: "hindu" },
  "9-17": { quote: "Collect the falling leaves. Each one is painted by God.", ref: "Upanishads", tradition: "hindu" },
  "9-18": { quote: "God moves through the mist and clouds like a loving presence.", ref: "Upanishads", tradition: "hindu" },
  "9-19": { quote: "Squirrels gather acorns wisely. Be wise with your gifts too.", ref: "Mahabharata", tradition: "hindu" },
  "9-20": { quote: "The earth gives her fruits with an open and loving hand.", ref: "Atharva Veda", tradition: "hindu" },
  "9-21": { quote: "The cool morning air is God breathing freshness into the world.", ref: "Rigveda", tradition: "hindu" },
  "9-22": { quote: "Shout for joy! The whole creation shouts with you.", ref: "Bhagavatam", tradition: "hindu" },
  "9-23": { quote: "Day and night are equal today. Find balance in your heart.", ref: "Upanishads", tradition: "hindu" },
  "9-24": { quote: "Inside you is the whole universe — you are made of stars.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "9-25": { quote: "A warm cup of milk is God's comfort on a cool morning.", ref: "Bhagavatam", tradition: "hindu" },
  "9-26": { quote: "Give freely and the universe will give back to you.", ref: "Gita 3:10", tradition: "hindu" },
  "9-27": { quote: "The wind carries seeds far and wide. God carries your prayers too.", ref: "Rigveda", tradition: "hindu" },
  "9-28": { quote: "The moon is God's gentle light in the night sky.", ref: "Gita 10:21", tradition: "hindu" },
  "9-29": { quote: "Be like a lamp that never goes out. Shine every day.", ref: "Upanishads", tradition: "hindu" },
  "9-30": { quote: "September brought harvest and learning. Thank God for both.", ref: "Rigveda", tradition: "hindu" },

  // ===== OCTOBER (31 days) — Navratri, Dussehra, Diwali prep, autumn =====
  "10-1": { quote: "October begins! The festival season fills the air with joy.", ref: "Bhagavatam", tradition: "hindu" },
  "10-2": { quote: "Jump for joy! The whole creation celebrates with you.", ref: "Bhagavatam", tradition: "hindu" },
  "10-3": { quote: "Durga is strong and loving. She protects all who call her name.", ref: "Bhagavatam", tradition: "hindu" },
  "10-4": { quote: "Every creature is a child of God. Be kind to all of them.", ref: "Gita 13:28", tradition: "hindu" },
  "10-5": { quote: "Navratri is nine nights of devotion. Dance your prayers tonight!", ref: "Bhagavatam", tradition: "hindu" },
  "10-6": { quote: "Cooking for others is an act of love and devotion.", ref: "Gita 9:26", tradition: "hindu" },
  "10-7": { quote: "Dress in bright colors for the festival. God loves color and joy!", ref: "Bhagavatam", tradition: "hindu" },
  "10-8": { quote: "The pumpkin grew slowly and perfectly — just like you.", ref: "Upanishads", tradition: "hindu" },
  "10-9": { quote: "Clap your hands for Garba! Dancing together is praying together.", ref: "Bhagavatam", tradition: "hindu" },
  "10-10": { quote: "Watch the sky at dusk — God is painting just for you.", ref: "Rigveda", tradition: "hindu" },
  "10-11": { quote: "Good wins over bad. That is what Dussehra teaches us.", ref: "Ramayana", tradition: "hindu" },
  "10-12": { quote: "Create beauty from what nature gives you — that is sacred art.", ref: "Gita 3:9", tradition: "hindu" },
  "10-13": { quote: "Rama's victory teaches us that truth always wins in the end.", ref: "Ramayana", tradition: "hindu" },
  "10-14": { quote: "Even something small holds all of God's greatness inside.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "10-15": { quote: "Light a lamp of love in your heart. It will never go out.", ref: "Upanishads", tradition: "hindu" },
  "10-16": { quote: "Crisp autumn air is God breathing freshness into the world.", ref: "Upanishads", tradition: "hindu" },
  "10-17": { quote: "Make sweets for your family. Sweet food is a form of love.", ref: "Gita 9:26", tradition: "hindu" },
  "10-18": { quote: "Leap into joy — God delights in your happiness!", ref: "Bhagavatam", tradition: "hindu" },
  "10-19": { quote: "Draw a rangoli at your door. Invite beauty into your home.", ref: "Bhagavatam", tradition: "hindu" },
  "10-20": { quote: "God fills the world with every color. Look and be amazed.", ref: "Rigveda", tradition: "hindu" },
  "10-21": { quote: "Clean your home with love. A clean home welcomes Lakshmi.", ref: "Bhagavatam", tradition: "hindu" },
  "10-22": { quote: "Light every diya with a prayer. Each flame is a wish for good.", ref: "Upanishads", tradition: "hindu" },
  "10-23": { quote: "Fireworks light up the sky like God's joy bursting out!", ref: "Bhagavatam", tradition: "hindu" },
  "10-24": { quote: "Make colorful patterns like Lakshmi's rangoli — for God's joy.", ref: "Diwali", tradition: "hindu" },
  "10-25": { quote: "Diwali reminds us that light always wins over darkness.", ref: "Ramayana", tradition: "hindu" },
  "10-26": { quote: "Wisdom is the greatest color — wear it always.", ref: "Gita 4:38", tradition: "hindu" },
  "10-27": { quote: "Share your Diwali sweets with friends. Joy grows when it is shared.", ref: "Gita 17:20", tradition: "hindu" },
  "10-28": { quote: "Do not be afraid. God is with you always.", ref: "Gita 18:66", tradition: "hindu" },
  "10-29": { quote: "Lakshmi brings good fortune to those whose hearts are pure.", ref: "Bhagavatam", tradition: "hindu" },
  "10-30": { quote: "The stars are God's eyes watching over you with love.", ref: "Gita 10:21", tradition: "hindu" },
  "10-31": { quote: "October was a month of light and festivals. Thank God for the joy.", ref: "Bhagavatam", tradition: "hindu" },

  // ===== NOVEMBER (30 days) — Late autumn, gratitude, Diwali season =====
  "11-1": { quote: "November begins. Wrap yourself in God's warmth and love.", ref: "Upanishads", tradition: "hindu" },
  "11-2": { quote: "Give thanks for the small things. They add up to everything.", ref: "Upanishads", tradition: "hindu" },
  "11-3": { quote: "Your inner diya burns brighter than any outer lamp.", ref: "Upanishads", tradition: "hindu" },
  "11-4": { quote: "Count your blessings. God has given you so very many.", ref: "Gita 16:1", tradition: "hindu" },
  "11-5": { quote: "The last leaves fall gently. God catches every one.", ref: "Gita 9:22", tradition: "hindu" },
  "11-6": { quote: "The smell of good food is an offering to the Divine.", ref: "Gita 9:26", tradition: "hindu" },
  "11-7": { quote: "Light a lamp for someone who is sad. Your light will lift them.", ref: "Upanishads", tradition: "hindu" },
  "11-8": { quote: "God wraps the earth in a cozy blanket of leaves.", ref: "Atharva Veda", tradition: "hindu" },
  "11-9": { quote: "Warm chai on a cold day is God's hug in a cup.", ref: "Upanishads", tradition: "hindu" },
  "11-10": { quote: "Your light is like a diya — it can light up the whole world.", ref: "Diwali", tradition: "hindu" },
  "11-11": { quote: "Two ones side by side — like you and God, always together.", ref: "Gita 18:61", tradition: "hindu" },
  "11-12": { quote: "All trees rest and wake again — the soul is the same.", ref: "Gita 2:22", tradition: "hindu" },
  "11-13": { quote: "Snuggle close to your family. Togetherness is a blessing.", ref: "Mahabharata", tradition: "hindu" },
  "11-14": { quote: "Prepare wisely for what is coming. That is the dharmic way.", ref: "Mahabharata", tradition: "hindu" },
  "11-15": { quote: "Tell someone you love them today. Love is the greatest mantra.", ref: "Gita 12:20", tradition: "hindu" },
  "11-16": { quote: "Even a pinecone holds a forest. You hold greatness too.", ref: "Chandogya Upanishad", tradition: "hindu" },
  "11-17": { quote: "Gratitude turns a simple meal into a feast.", ref: "Gita 9:26", tradition: "hindu" },
  "11-18": { quote: "A loving hug is the warmest form of seva.", ref: "Mahabharata", tradition: "hindu" },
  "11-19": { quote: "God made cozy evenings for stories and togetherness.", ref: "Ramayana", tradition: "hindu" },
  "11-20": { quote: "Setting the table beautifully is an act of love and service.", ref: "Gita 3:19", tradition: "hindu" },
  "11-21": { quote: "Say a prayer before you eat. Gratitude makes food taste sweeter.", ref: "Gita 9:26", tradition: "hindu" },
  "11-22": { quote: "Eat with gratitude. Every meal is prasad — a gift from God.", ref: "Gita 9:26", tradition: "hindu" },
  "11-23": { quote: "Thank God for your home. It is a temple of love.", ref: "Upanishads", tradition: "hindu" },
  "11-24": { quote: "Honor your ancestors. Their love lives on inside you.", ref: "Mahabharata", tradition: "hindu" },
  "11-25": { quote: "A thankful heart is like a magnet for more blessings.", ref: "Upanishads", tradition: "hindu" },
  "11-26": { quote: "Give thanks for all you have. Gratitude is the highest prayer.", ref: "Gita 16:1", tradition: "hindu" },
  "11-27": { quote: "When the nights grow long, God fills them with stars.", ref: "Gita 10:21", tradition: "hindu" },
  "11-28": { quote: "Rest is sacred. Even God rests between acts of creation.", ref: "Upanishads", tradition: "hindu" },
  "11-29": { quote: "Be thankful for the year so far. God has been with you every step.", ref: "Gita 18:61", tradition: "hindu" },
  "11-30": { quote: "Give thanks for this whole month. Every day was a blessing.", ref: "Upanishads", tradition: "hindu" },

  // ===== DECEMBER (31 days) — Winter, light in darkness, year's end =====
  "12-1": { quote: "December brings the shortest days. But God's light never fades.", ref: "Gita 10:11", tradition: "hindu" },
  "12-2": { quote: "Each snowflake is unique — God made you one of a kind too.", ref: "Upanishads", tradition: "hindu" },
  "12-3": { quote: "Light a diya in the darkness. One small flame changes everything.", ref: "Upanishads", tradition: "hindu" },
  "12-4": { quote: "A lamp chases away darkness — just as love chases away fear.", ref: "Gita 10:11", tradition: "hindu" },
  "12-5": { quote: "Warm mittens, warm heart. God keeps you cozy and safe.", ref: "Gita 9:22", tradition: "hindu" },
  "12-6": { quote: "Giving is an act of worship. Give something today.", ref: "Gita 17:20", tradition: "hindu" },
  "12-7": { quote: "Hot kheer on a cold night is God's love in a bowl.", ref: "Bhagavatam", tradition: "hindu" },
  "12-8": { quote: "Sweet things are gifts from God. Make and share them.", ref: "Gita 17:9", tradition: "hindu" },
  "12-9": { quote: "Sing a song by the fire. God loves the sound of your voice.", ref: "Bhagavatam", tradition: "hindu" },
  "12-10": { quote: "Your family is your first sangha — your first community of love.", ref: "Mahabharata", tradition: "hindu" },
  "12-11": { quote: "Even on the coldest days, God's love keeps you warm inside.", ref: "Gita 9:29", tradition: "hindu" },
  "12-12": { quote: "God counts every star and remembers every act of love.", ref: "Gita 10:21", tradition: "hindu" },
  "12-13": { quote: "Make something with your hands for someone you love.", ref: "Gita 3:9", tradition: "hindu" },
  "12-14": { quote: "Wrap your gifts with love. The love is the real present.", ref: "Gita 9:26", tradition: "hindu" },
  "12-15": { quote: "The winter sky is clear and full of God's brightest stars.", ref: "Gita 10:21", tradition: "hindu" },
  "12-16": { quote: "Peace is the greatest gift. Share it with everyone.", ref: "Gita 6:7", tradition: "hindu" },
  "12-17": { quote: "Read a story with someone you love. Stories carry God's wisdom.", ref: "Ramayana", tradition: "hindu" },
  "12-18": { quote: "Making sweet things for others is a form of devotion.", ref: "Gita 9:26", tradition: "hindu" },
  "12-19": { quote: "God's love is like a warm fire on the coldest night.", ref: "Upanishads", tradition: "hindu" },
  "12-20": { quote: "Follow the light wherever it leads — it always leads to God.", ref: "Gita 10:11", tradition: "hindu" },
  "12-21": { quote: "The longest night ends. Tomorrow the light begins to grow again.", ref: "Rigveda", tradition: "hindu" },
  "12-22": { quote: "Circle of lights, circle of love — God is in every ring.", ref: "Upanishads", tradition: "hindu" },
  "12-23": { quote: "Hold your family close tonight. You are each other's greatest gift.", ref: "Mahabharata", tradition: "hindu" },
  "12-24": { quote: "On the eve of something wonderful, joy fills the whole sky.", ref: "Bhagavatam", tradition: "hindu" },
  "12-25": { quote: "Today is a day of love and peace for the whole world.", ref: "Upanishads", tradition: "hindu" },
  "12-26": { quote: "Share your joy freely. Joy multiplies when it is given away.", ref: "Gita 5:21", tradition: "hindu" },
  "12-27": { quote: "Look back on this year with a grateful heart.", ref: "Upanishads", tradition: "hindu" },
  "12-28": { quote: "Your inner light can never be put out. It shines forever.", ref: "Gita 2:20", tradition: "hindu" },
  "12-29": { quote: "God has been with you every day this year. He will be there next year too.", ref: "Gita 18:61", tradition: "hindu" },
  "12-30": { quote: "Give thanks for every single day. Each one was a gift.", ref: "Upanishads", tradition: "hindu" },
  "12-31": { quote: "The year ends in God's arms. A beautiful new one begins tomorrow.", ref: "Upanishads", tradition: "hindu" },
};
