import { AffirmationMap } from '../../types';

// Catholic affirmations — 365 entries, one per day
// ~240 Bible verses (shared Christian heritage) + ~120 saint quotes & Catholic-specific content
// Saint quotes placed on or near feast days; Catholic concepts scattered throughout

export const christianCatholicAffirmations: AffirmationMap = {
  // ── JANUARY ──
  "1-1": { quote: "I am making everything new!", ref: "Rev 21:5", tradition: "christian-catholic" },
  "1-2": { quote: "Mary kept all these things in her heart.", ref: "Luke 2:19", tradition: "christian-catholic" },
  "1-3": { quote: "A cheerful heart makes you feel good.", ref: "Prov 17:22", tradition: "christian-catholic" },
  "1-4": { quote: "Do everything in love.", ref: "1 Cor 16:14", tradition: "christian-catholic" },
  "1-5": { quote: "The earth is full of God's love.", ref: "Ps 33:5", tradition: "christian-catholic" },
  "1-6": { quote: "Wise men followed a star to find the light.", ref: "Epiphany", tradition: "christian-catholic" },
  "1-7": { quote: "Be who God meant you to be, and you will set the world on fire.", ref: "St. Catherine of Siena", tradition: "christian-catholic" },
  "1-8": { quote: "Love each other just as I have loved you.", ref: "John 15:12", tradition: "christian-catholic" },
  "1-9": { quote: "The skies tell about the amazing things God does.", ref: "Ps 19:1", tradition: "christian-catholic" },
  "1-10": { quote: "It is more blessed to give than to receive.", ref: "Acts 20:35", tradition: "christian-catholic" },
  "1-11": { quote: "Kind words are like honey — sweet to your heart.", ref: "Prov 16:24", tradition: "christian-catholic" },
  "1-12": { quote: "Those who trust in God will get new strength.", ref: "Isa 40:31", tradition: "christian-catholic" },
  "1-13": { quote: "Shout for joy to the Lord!", ref: "Ps 100:1", tradition: "christian-catholic" },
  "1-14": { quote: "Pray, hope, and don't worry.", ref: "St. Padre Pio", tradition: "christian-catholic" },
  "1-15": { quote: "We become what we love.", ref: "St. Clare of Assisi", tradition: "christian-catholic" },
  "1-16": { quote: "Every good and perfect gift comes down from God.", ref: "James 1:17", tradition: "christian-catholic" },
  "1-17": { quote: "The Lord is my shepherd. He gives me everything I need.", ref: "Ps 23:1", tradition: "christian-catholic" },
  "1-18": { quote: "A gentle answer turns away anger.", ref: "Prov 15:1", tradition: "christian-catholic" },
  "1-19": { quote: "Love your neighbor as you love yourself.", ref: "Mark 12:31", tradition: "christian-catholic" },
  "1-20": { quote: "Let nothing disturb you. God alone is enough.", ref: "St. Teresa of Ávila", tradition: "christian-catholic" },
  "1-21": { quote: "Honor your father and mother.", ref: "Exod 20:12", tradition: "christian-catholic" },
  "1-22": { quote: "God loved the world so much that he gave his one and only Son.", ref: "John 3:16", tradition: "christian-catholic" },
  "1-23": { quote: "Be quick to listen and slow to speak.", ref: "James 1:19", tradition: "christian-catholic" },
  "1-24": { quote: "God your Lord is with you everywhere you go.", ref: "Josh 1:9", tradition: "christian-catholic" },
  "1-25": { quote: "Help each other be strong in the faith.", ref: "1 Thess 5:11", tradition: "christian-catholic" },
  "1-26": { quote: "I can do everything by the power of Christ who gives me strength.", ref: "Phil 4:13", tradition: "christian-catholic" },
  "1-27": { quote: "Miss no single opportunity of making some small sacrifice.", ref: "St. Thérèse of Lisieux", tradition: "christian-catholic" },
  "1-28": { quote: "To one who has faith, no explanation is necessary.", ref: "St. Thomas Aquinas", tradition: "christian-catholic" },
  "1-29": { quote: "God made the stars — he knows each one by name.", ref: "Ps 147:4", tradition: "christian-catholic" },
  "1-30": { quote: "Go forth and set the world on fire.", ref: "St. Ignatius of Loyola", tradition: "christian-catholic" },
  "1-31": { quote: "This is the day the Lord has made. Let's be joyful today!", ref: "Ps 118:24", tradition: "christian-catholic" },

  // ── FEBRUARY ──
  "2-1": { quote: "I would be a saint if I could only find enough people to love.", ref: "St. Brigid of Kildare", tradition: "christian-catholic" },
  "2-2": { quote: "Help carry each other's heavy loads.", ref: "Gal 6:2", tradition: "christian-catholic" },
  "2-3": { quote: "Kind words are like honey — sweet and good.", ref: "Prov 16:24", tradition: "christian-catholic" },
  "2-4": { quote: "More than anything, love one another deeply.", ref: "Col 3:14", tradition: "christian-catholic" },
  "2-5": { quote: "Where you go, I will go.", ref: "Ruth 1:16", tradition: "christian-catholic" },
  "2-6": { quote: "Give to others and it will be given to you.", ref: "Luke 6:38", tradition: "christian-catholic" },
  "2-7": { quote: "God, create a pure heart in me.", ref: "Ps 51:10", tradition: "christian-catholic" },
  "2-8": { quote: "I have loved you with a love that lasts forever.", ref: "Jer 31:3", tradition: "christian-catholic" },
  "2-9": { quote: "If you judge people, you have no time to love them.", ref: "St. Teresa of Calcutta", tradition: "christian-catholic" },
  "2-10": { quote: "There is no fear in love.", ref: "1 John 4:18", tradition: "christian-catholic" },
  "2-11": { quote: "Our Lady of Lourdes, pray for us and help us to be kind.", ref: "Our Lady of Lourdes", tradition: "christian-catholic" },
  "2-12": { quote: "Sing a new song to the Lord!", ref: "Ps 96:1", tradition: "christian-catholic" },
  "2-13": { quote: "How you made me is amazing and wonderful!", ref: "Ps 139:14", tradition: "christian-catholic" },
  "2-14": { quote: "Dear friends, let us love one another, because love comes from God.", ref: "1 John 4:7", tradition: "christian-catholic" },
  "2-15": { quote: "Love never gives up.", ref: "1 Cor 13:8", tradition: "christian-catholic" },
  "2-16": { quote: "Pray for each other.", ref: "James 5:16", tradition: "christian-catholic" },
  "2-17": { quote: "You are all one in Christ Jesus.", ref: "Gal 3:28", tradition: "christian-catholic" },
  "2-18": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "2-19": { quote: "Let your light shine so others can see it.", ref: "Matt 5:16", tradition: "christian-catholic" },
  "2-20": { quote: "Forgive, and you will be forgiven.", ref: "Luke 6:37", tradition: "christian-catholic" },
  "2-21": { quote: "Nothing is impossible with God.", ref: "Matt 19:26", tradition: "christian-catholic" },
  "2-22": { quote: "The truth will set you free.", ref: "John 8:32", tradition: "christian-catholic" },
  "2-23": { quote: "You have made us for yourself, O Lord, and our hearts are restless until they rest in you.", ref: "St. Augustine", tradition: "christian-catholic" },
  "2-24": { quote: "Work at everything you do with all your heart.", ref: "Col 3:23", tradition: "christian-catholic" },
  "2-25": { quote: "Give thanks to the Lord because he is good.", ref: "Ps 107:1", tradition: "christian-catholic" },
  "2-26": { quote: "Blessed are those who make peace.", ref: "Matt 5:9", tradition: "christian-catholic" },
  "2-27": { quote: "You have done a good job! You are a good and faithful helper!", ref: "Matt 25:21", tradition: "christian-catholic" },
  "2-28": { quote: "This is the day the Lord has made. Let's be joyful today!", ref: "Ps 118:24", tradition: "christian-catholic" },

  // ── MARCH ──
  "3-1": { quote: "Winter is past. The rains are over and gone.", ref: "Song 2:11", tradition: "christian-catholic" },
  "3-2": { quote: "Start by doing what's necessary, then what's possible, and suddenly you are doing the impossible.", ref: "St. Francis of Assisi", tradition: "christian-catholic" },
  "3-3": { quote: "The Holy Spirit fills our hearts with love and peace.", ref: "Rom 5:5", tradition: "christian-catholic" },
  "3-4": { quote: "God, you are dressed in glory and majesty.", ref: "Ps 104:1", tradition: "christian-catholic" },
  "3-5": { quote: "A good person takes care of their animals.", ref: "Prov 12:10", tradition: "christian-catholic" },
  "3-6": { quote: "Shout for joy to the Lord!", ref: "Ps 100:1", tradition: "christian-catholic" },
  "3-7": { quote: "See how the flowers grow. They don't work or worry — but God dresses them beautifully!", ref: "Matt 6:28", tradition: "christian-catholic" },
  "3-8": { quote: "Her children stand up and say good things about her.", ref: "Prov 31:28", tradition: "christian-catholic" },
  "3-9": { quote: "Those who trust in God will get new strength.", ref: "Isa 40:31", tradition: "christian-catholic" },
  "3-10": { quote: "God sends streams into the valleys.", ref: "Ps 104:10", tradition: "christian-catholic" },
  "3-11": { quote: "Two people are better than one.", ref: "Eccl 4:9", tradition: "christian-catholic" },
  "3-12": { quote: "A cheerful heart makes you feel good.", ref: "Prov 17:22", tradition: "christian-catholic" },
  "3-13": { quote: "Be strong and brave.", ref: "Josh 1:9", tradition: "christian-catholic" },
  "3-14": { quote: "Flowers are appearing on the earth.", ref: "Song 2:12", tradition: "christian-catholic" },
  "3-15": { quote: "Give to others and it will be given to you.", ref: "Luke 6:38", tradition: "christian-catholic" },
  "3-16": { quote: "When you give to someone, do it secretly.", ref: "Matt 6:3", tradition: "christian-catholic" },
  "3-17": { quote: "Christ is beside me, Christ is before me, Christ is behind me.", ref: "St. Patrick", tradition: "christian-catholic" },
  "3-18": { quote: "Be strong and very brave.", ref: "Josh 1:6", tradition: "christian-catholic" },
  "3-19": { quote: "St. Joseph was a good and caring father who protected his family.", ref: "St. Joseph", tradition: "christian-catholic" },
  "3-20": { quote: "Anyone who believes in Christ is a new creation.", ref: "2 Cor 5:17", tradition: "christian-catholic" },
  "3-21": { quote: "I planted the seed. Someone else watered it. But God made it grow.", ref: "1 Cor 3:6", tradition: "christian-catholic" },
  "3-22": { quote: "Let your light shine so others can see it.", ref: "Matt 5:16", tradition: "christian-catholic" },
  "3-23": { quote: "Be not afraid.", ref: "St. John Paul II", tradition: "christian-catholic" },
  "3-24": { quote: "Help each other every day.", ref: "Heb 3:13", tradition: "christian-catholic" },
  "3-25": { quote: "Mary said, 'I am the Lord's servant. Let it happen to me as you have said.'", ref: "Luke 1:38", tradition: "christian-catholic" },
  "3-26": { quote: "Your Father who sees what is done in secret will reward you.", ref: "Matt 6:4", tradition: "christian-catholic" },
  "3-27": { quote: "The earth belongs to the Lord — and everything in it.", ref: "Ps 24:1", tradition: "christian-catholic" },
  "3-28": { quote: "Work at everything you do with all your heart.", ref: "Col 3:23", tradition: "christian-catholic" },
  "3-29": { quote: "Turn all your worries over to God. He cares about you.", ref: "1 Pet 5:7", tradition: "christian-catholic" },
  "3-30": { quote: "Count your blessings — name them one by one.", ref: "Hymn", tradition: "christian-catholic" },
  "3-31": { quote: "This is the day the Lord has made. Let's be joyful today!", ref: "Ps 118:24", tradition: "christian-catholic" },

  // ── APRIL ──
  "4-1": { quote: "And hope never makes us ashamed.", ref: "Rom 5:5", tradition: "christian-catholic" },
  "4-2": { quote: "Jesus knelt down and washed his friends' feet to show his love.", ref: "John 13:5", tradition: "christian-catholic" },
  "4-3": { quote: "No one has greater love than the one who gives their life for their friends.", ref: "John 15:13", tradition: "christian-catholic" },
  "4-4": { quote: "I am doing something new! Do you see it happening?", ref: "Isa 43:19", tradition: "christian-catholic" },
  "4-5": { quote: "I am the resurrection and the life.", ref: "John 11:25", tradition: "christian-catholic" },
  "4-6": { quote: "Be joyful in the Lord always. I will say it again — be joyful!", ref: "Phil 4:4", tradition: "christian-catholic" },
  "4-7": { quote: "A person will harvest what they plant.", ref: "Gal 6:7", tradition: "christian-catholic" },
  "4-8": { quote: "God sends rain on good people and bad people alike.", ref: "Matt 5:45", tradition: "christian-catholic" },
  "4-9": { quote: "Look at the birds in the sky. Your Father in heaven feeds them.", ref: "Matt 6:26", tradition: "christian-catholic" },
  "4-10": { quote: "Anyone who believes in Christ is a new creation.", ref: "2 Cor 5:17", tradition: "christian-catholic" },
  "4-11": { quote: "Find your delight in the Lord.", ref: "Ps 37:4", tradition: "christian-catholic" },
  "4-12": { quote: "Serve one another in a spirit of love.", ref: "Gal 5:13", tradition: "christian-catholic" },
  "4-13": { quote: "The Lord God put the man in the Garden of Eden to take care of it.", ref: "Gen 2:15", tradition: "christian-catholic" },
  "4-14": { quote: "A happy heart makes a face look cheerful.", ref: "Prov 15:13", tradition: "christian-catholic" },
  "4-15": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "4-16": { quote: "Love each other just as I have loved you.", ref: "John 15:12", tradition: "christian-catholic" },
  "4-17": { quote: "The skies tell about the amazing things God does.", ref: "Ps 19:1", tradition: "christian-catholic" },
  "4-18": { quote: "God gives food to every creature.", ref: "Ps 136:25", tradition: "christian-catholic" },
  "4-19": { quote: "The earth belongs to the Lord — and everything in it.", ref: "Ps 24:1", tradition: "christian-catholic" },
  "4-20": { quote: "We become what we love.", ref: "St. Clare of Assisi", tradition: "christian-catholic" },
  "4-21": { quote: "Ask and it will be given to you. Search and you will find.", ref: "Matt 7:7", tradition: "christian-catholic" },
  "4-22": { quote: "The Lord God put the man in the Garden of Eden to take care of it.", ref: "Gen 2:15", tradition: "christian-catholic" },
  "4-23": { quote: "God's words are sweeter than honey.", ref: "Ps 119:103", tradition: "christian-catholic" },
  "4-24": { quote: "Be joyful with those who are joyful.", ref: "Rom 12:15", tradition: "christian-catholic" },
  "4-25": { quote: "Be patient and stand firm.", ref: "James 5:7", tradition: "christian-catholic" },
  "4-26": { quote: "The Lord God formed the man from the dust of the ground.", ref: "Gen 2:7", tradition: "christian-catholic" },
  "4-27": { quote: "Be still and know that I am God.", ref: "Ps 46:10", tradition: "christian-catholic" },
  "4-28": { quote: "Help carry each other's heavy loads.", ref: "Gal 6:2", tradition: "christian-catholic" },
  "4-29": { quote: "Be who God meant you to be, and you will set the world on fire.", ref: "St. Catherine of Siena", tradition: "christian-catholic" },
  "4-30": { quote: "This is the day the Lord has made. Let's be joyful today!", ref: "Ps 118:24", tradition: "christian-catholic" },

  // ── MAY ──
  "5-1": { quote: "St. Joseph worked hard with his hands and loved his family.", ref: "St. Joseph the Worker", tradition: "christian-catholic" },
  "5-2": { quote: "See how the flowers grow! Even Solomon was not dressed as beautifully as one of these.", ref: "Matt 6:29", tradition: "christian-catholic" },
  "5-3": { quote: "The Lord God is like the sun that gives us light.", ref: "Ps 84:11", tradition: "christian-catholic" },
  "5-4": { quote: "As a mother comforts her child, I will comfort you.", ref: "Isa 66:13", tradition: "christian-catholic" },
  "5-5": { quote: "The rosary is a prayer that helps us think about Jesus and Mary.", ref: "The Rosary", tradition: "christian-catholic" },
  "5-6": { quote: "Let everything that has breath praise the Lord!", ref: "Ps 150:6", tradition: "christian-catholic" },
  "5-7": { quote: "I am the vine. You are the branches.", ref: "John 15:5", tradition: "christian-catholic" },
  "5-8": { quote: "God's words are sweeter than honey.", ref: "Ps 119:103", tradition: "christian-catholic" },
  "5-9": { quote: "Her children stand up and say good things about her.", ref: "Prov 31:28", tradition: "christian-catholic" },
  "5-10": { quote: "Mary is our heavenly mother. She loves and prays for us always.", ref: "Blessed Virgin Mary", tradition: "christian-catholic" },
  "5-11": { quote: "Honor your father and mother.", ref: "Exod 20:12", tradition: "christian-catholic" },
  "5-12": { quote: "Kind words are like honey — sweet and good.", ref: "Prov 16:24", tradition: "christian-catholic" },
  "5-13": { quote: "Our Lady of Fatima asked us to pray the rosary and be kind to everyone.", ref: "Our Lady of Fatima", tradition: "christian-catholic" },
  "5-14": { quote: "Every good and perfect gift comes down from God.", ref: "James 1:17", tradition: "christian-catholic" },
  "5-15": { quote: "That person is like a tree planted by streams of water.", ref: "Ps 1:3", tradition: "christian-catholic" },
  "5-16": { quote: "Be strong and brave! I commanded you to be strong and brave!", ref: "Josh 1:9", tradition: "christian-catholic" },
  "5-17": { quote: "A good person takes care of their animals.", ref: "Prov 12:10", tradition: "christian-catholic" },
  "5-18": { quote: "The joy of the Lord makes you strong.", ref: "Neh 8:10", tradition: "christian-catholic" },
  "5-19": { quote: "If the Lord does not build the house, the builders are working for nothing.", ref: "Ps 127:1", tradition: "christian-catholic" },
  "5-20": { quote: "They will soar on wings like eagles.", ref: "Isa 40:31", tradition: "christian-catholic" },
  "5-21": { quote: "God began a good work in you. I am sure he will carry it on until it is finished.", ref: "Phil 1:6", tradition: "christian-catholic" },
  "5-22": { quote: "Be still and know that I am God.", ref: "Ps 46:10", tradition: "christian-catholic" },
  "5-23": { quote: "Pray, hope, and don't worry.", ref: "St. Padre Pio", tradition: "christian-catholic" },
  "5-24": { quote: "Be joyful in the Lord always!", ref: "Phil 4:4", tradition: "christian-catholic" },
  "5-25": { quote: "He leads me beside quiet waters.", ref: "Ps 23:2", tradition: "christian-catholic" },
  "5-26": { quote: "Look out for the interests of others, not just your own.", ref: "Phil 2:4", tradition: "christian-catholic" },
  "5-27": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "5-28": { quote: "The most important thing is to get wisdom.", ref: "Prov 4:7", tradition: "christian-catholic" },
  "5-29": { quote: "A wise child makes his father glad.", ref: "Prov 10:1", tradition: "christian-catholic" },
  "5-30": { quote: "I am not afraid. I was born to do this.", ref: "St. Joan of Arc", tradition: "christian-catholic" },
  "5-31": { quote: "Mary went to visit her cousin Elizabeth and they were filled with joy.", ref: "Luke 1:39-40", tradition: "christian-catholic" },

  // ── JUNE ──
  "6-1": { quote: "This is the day the Lord has made. Let's be joyful today!", ref: "Ps 118:24", tradition: "christian-catholic" },
  "6-2": { quote: "God calmed the storm and made the waves quiet.", ref: "Ps 107:29", tradition: "christian-catholic" },
  "6-3": { quote: "The Sacred Heart of Jesus is full of love for every person.", ref: "Sacred Heart", tradition: "christian-catholic" },
  "6-4": { quote: "Always be joyful!", ref: "1 Thess 5:16", tradition: "christian-catholic" },
  "6-5": { quote: "God calmed the storm and made the waves quiet.", ref: "Ps 107:29", tradition: "christian-catholic" },
  "6-6": { quote: "The Lord God is like the sun that gives us light.", ref: "Ps 84:11", tradition: "christian-catholic" },
  "6-7": { quote: "God counts all the stars and knows each one by name.", ref: "Ps 147:4", tradition: "christian-catholic" },
  "6-8": { quote: "He leads me beside quiet waters.", ref: "Ps 23:2", tradition: "christian-catholic" },
  "6-9": { quote: "God, you are dressed in glory and majesty.", ref: "Ps 104:1", tradition: "christian-catholic" },
  "6-10": { quote: "Let them praise God's name with dancing!", ref: "Ps 149:3", tradition: "christian-catholic" },
  "6-11": { quote: "Go forth and set the world on fire.", ref: "St. Ignatius of Loyola", tradition: "christian-catholic" },
  "6-12": { quote: "I have put my rainbow in the clouds.", ref: "Gen 9:13", tradition: "christian-catholic" },
  "6-13": { quote: "When you look for something with all your heart, you will find it.", ref: "St. Anthony of Padua", tradition: "christian-catholic" },
  "6-14": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "6-15": { quote: "Honor your father and mother.", ref: "Exod 20:12", tradition: "christian-catholic" },
  "6-16": { quote: "Let everything that has breath praise the Lord!", ref: "Ps 150:6", tradition: "christian-catholic" },
  "6-17": { quote: "From where the sun rises to where it sets, people praise the Lord.", ref: "Ps 113:3", tradition: "christian-catholic" },
  "6-18": { quote: "God fills the sky with clouds.", ref: "Job 37:11", tradition: "christian-catholic" },
  "6-19": { quote: "Announce freedom for everyone in the land.", ref: "Lev 25:10", tradition: "christian-catholic" },
  "6-20": { quote: "The sea is huge! It is wide! It is full of more creatures than you can count.", ref: "Ps 104:25", tradition: "christian-catholic" },
  "6-21": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "6-22": { quote: "I die the king's good servant, but God's first.", ref: "St. Thomas More", tradition: "christian-catholic" },
  "6-23": { quote: "The earth is full of your riches, Lord.", ref: "Ps 104:24", tradition: "christian-catholic" },
  "6-24": { quote: "See how the flowers grow! God dresses them beautifully!", ref: "Matt 6:28", tradition: "christian-catholic" },
  "6-25": { quote: "Lord, you have made so many things! How wise you were when you made all of them!", ref: "Ps 104:24", tradition: "christian-catholic" },
  "6-26": { quote: "A wise person builds their house on the rock.", ref: "Matt 7:24", tradition: "christian-catholic" },
  "6-27": { quote: "Look at the birds in the sky. Your Father in heaven feeds them.", ref: "Matt 6:26", tradition: "christian-catholic" },
  "6-28": { quote: "We have this hope as an anchor for our souls.", ref: "Heb 6:19", tradition: "christian-catholic" },
  "6-29": { quote: "God created the large sea creatures.", ref: "Gen 1:21", tradition: "christian-catholic" },
  "6-30": { quote: "May the Lord bless you and take care of you.", ref: "Num 6:24", tradition: "christian-catholic" },

  // ── JULY ──
  "7-1": { quote: "Get up and shine! Your light has come!", ref: "Isa 60:1", tradition: "christian-catholic" },
  "7-2": { quote: "Let your light shine so others can see it.", ref: "Matt 5:16", tradition: "christian-catholic" },
  "7-3": { quote: "The joy of the Lord makes you strong.", ref: "Neh 8:10", tradition: "christian-catholic" },
  "7-4": { quote: "Announce freedom for everyone in the land.", ref: "Lev 25:10", tradition: "christian-catholic" },
  "7-5": { quote: "They will soar on wings like eagles.", ref: "Isa 40:31", tradition: "christian-catholic" },
  "7-6": { quote: "Be joyful in the Lord always!", ref: "Phil 4:4", tradition: "christian-catholic" },
  "7-7": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "7-8": { quote: "He lets me lie down in fields of green grass.", ref: "Ps 23:2", tradition: "christian-catholic" },
  "7-9": { quote: "The Lord God is like the sun that gives us light.", ref: "Ps 84:11", tradition: "christian-catholic" },
  "7-10": { quote: "Let fair treatment flow like a river!", ref: "Amos 5:24", tradition: "christian-catholic" },
  "7-11": { quote: "Pray and work — both are gifts from God.", ref: "St. Benedict", tradition: "christian-catholic" },
  "7-12": { quote: "God gives sleep to those he loves.", ref: "Ps 127:2", tradition: "christian-catholic" },
  "7-13": { quote: "Be very glad and joyful!", ref: "Matt 5:12", tradition: "christian-catholic" },
  "7-14": { quote: "The earth is full of your riches, Lord.", ref: "Ps 104:24", tradition: "christian-catholic" },
  "7-15": { quote: "A cheerful heart makes you feel good.", ref: "Prov 17:22", tradition: "christian-catholic" },
  "7-16": { quote: "Our guardian angel watches over us day and night.", ref: "Guardian Angels", tradition: "christian-catholic" },
  "7-17": { quote: "The Lord God formed man of the dust of the ground.", ref: "Gen 2:7", tradition: "christian-catholic" },
  "7-18": { quote: "God crowns the year with his good gifts.", ref: "Ps 65:11", tradition: "christian-catholic" },
  "7-19": { quote: "From where the sun rises to where it sets, people praise the Lord.", ref: "Ps 113:3", tradition: "christian-catholic" },
  "7-20": { quote: "A wise person builds their house on the rock.", ref: "Matt 7:24", tradition: "christian-catholic" },
  "7-21": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "7-22": { quote: "She went to the tomb early while it was still dark, because she loved Jesus so much.", ref: "St. Mary Magdalene", tradition: "christian-catholic" },
  "7-23": { quote: "Get up and shine! Your light has come!", ref: "Isa 60:1", tradition: "christian-catholic" },
  "7-24": { quote: "The earth produced plants and trees, just as God had planned.", ref: "Gen 1:12", tradition: "christian-catholic" },
  "7-25": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "7-26": { quote: "Blessed are the ones who are persecuted because they do what is right.", ref: "Matt 5:10", tradition: "christian-catholic" },
  "7-27": { quote: "They will soar on wings like eagles.", ref: "Isa 40:31", tradition: "christian-catholic" },
  "7-28": { quote: "God fills the sky with clouds.", ref: "Job 37:11", tradition: "christian-catholic" },
  "7-29": { quote: "He leads me beside quiet waters.", ref: "Ps 23:2", tradition: "christian-catholic" },
  "7-30": { quote: "Your word is like a lamp that shows me the way.", ref: "Ps 119:105", tradition: "christian-catholic" },
  "7-31": { quote: "Go forth and set the world on fire.", ref: "St. Ignatius of Loyola", tradition: "christian-catholic" },

  // ── AUGUST ──
  "8-1": { quote: "I know the plans I have for you. I will give you hope and a good future.", ref: "Jer 29:11", tradition: "christian-catholic" },
  "8-2": { quote: "The most important thing is to get wisdom.", ref: "Prov 4:7", tradition: "christian-catholic" },
  "8-3": { quote: "Your word is like a lamp that shows me the way.", ref: "Ps 119:105", tradition: "christian-catholic" },
  "8-4": { quote: "When we receive Holy Communion, Jesus comes to live in our hearts.", ref: "The Eucharist", tradition: "christian-catholic" },
  "8-5": { quote: "Get wisdom. No matter what it costs, get understanding.", ref: "Prov 4:7", tradition: "christian-catholic" },
  "8-6": { quote: "This is the day the Lord has made. Let's be joyful today!", ref: "Ps 118:24", tradition: "christian-catholic" },
  "8-7": { quote: "God, you are dressed in glory and majesty.", ref: "Ps 104:1", tradition: "christian-catholic" },
  "8-8": { quote: "A person who only prays is never alone.", ref: "St. Dominic", tradition: "christian-catholic" },
  "8-9": { quote: "The Lord God is like the sun that gives us light.", ref: "Ps 84:11", tradition: "christian-catholic" },
  "8-10": { quote: "Get up and shine! Your light has come!", ref: "Isa 60:1", tradition: "christian-catholic" },
  "8-11": { quote: "We become what we love.", ref: "St. Clare of Assisi", tradition: "christian-catholic" },
  "8-12": { quote: "God began a good work in you. I am sure he will carry it on until it is finished.", ref: "Phil 1:6", tradition: "christian-catholic" },
  "8-13": { quote: "Lord, you have made so many things!", ref: "Ps 104:24", tradition: "christian-catholic" },
  "8-14": { quote: "God sends streams into the valleys.", ref: "Ps 104:10", tradition: "christian-catholic" },
  "8-15": { quote: "Mary was taken up to heaven, where she prays for all of us.", ref: "Assumption of Mary", tradition: "christian-catholic" },
  "8-16": { quote: "Be very glad and joyful!", ref: "Matt 5:12", tradition: "christian-catholic" },
  "8-17": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "8-18": { quote: "The earth is full of your riches, Lord.", ref: "Ps 104:24", tradition: "christian-catholic" },
  "8-19": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "8-20": { quote: "There is a time for everything.", ref: "Eccl 3:1", tradition: "christian-catholic" },
  "8-21": { quote: "Miss no single opportunity of making some small sacrifice.", ref: "St. Thérèse of Lisieux", tradition: "christian-catholic" },
  "8-22": { quote: "If your faith is as small as a mustard seed, nothing will be impossible for you.", ref: "Matt 17:20", tradition: "christian-catholic" },
  "8-23": { quote: "Lord, you have made so many things! How wise you were when you made all of them!", ref: "Ps 104:24", tradition: "christian-catholic" },
  "8-24": { quote: "God's words taste sweeter than honey.", ref: "Ps 119:103", tradition: "christian-catholic" },
  "8-25": { quote: "Be joyful in the Lord always!", ref: "Phil 4:4", tradition: "christian-catholic" },
  "8-26": { quote: "Whatever your hand finds to do, do it with all your might.", ref: "Eccl 9:10", tradition: "christian-catholic" },
  "8-27": { quote: "Some friends are more loyal than brothers.", ref: "Prov 18:24", tradition: "christian-catholic" },
  "8-28": { quote: "You have made us for yourself, O Lord, and our hearts are restless until they rest in you.", ref: "St. Augustine", tradition: "christian-catholic" },
  "8-29": { quote: "A person who wants friends must be friendly.", ref: "Prov 18:24", tradition: "christian-catholic" },
  "8-30": { quote: "There is a time for everything.", ref: "Eccl 3:1", tradition: "christian-catholic" },
  "8-31": { quote: "I know the plans I have for you. I will give you hope and a good future.", ref: "Jer 29:11", tradition: "christian-catholic" },

  // ── SEPTEMBER ──
  "9-1": { quote: "There is a time for everything.", ref: "Eccl 3:1", tradition: "christian-catholic" },
  "9-2": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "9-3": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "9-4": { quote: "Be strong and brave. Do not be terrified.", ref: "Josh 1:9", tradition: "christian-catholic" },
  "9-5": { quote: "If you judge people, you have no time to love them.", ref: "St. Teresa of Calcutta", tradition: "christian-catholic" },
  "9-6": { quote: "Write down the message I am going to show you.", ref: "Hab 2:2", tradition: "christian-catholic" },
  "9-7": { quote: "Look at the ant! Think about how it lives and become wise.", ref: "Prov 6:6", tradition: "christian-catholic" },
  "9-8": { quote: "Happy birthday, Mary! Today we celebrate the birth of our Blessed Mother.", ref: "Nativity of Mary", tradition: "christian-catholic" },
  "9-9": { quote: "God makes the grass grow.", ref: "Ps 104:14", tradition: "christian-catholic" },
  "9-10": { quote: "God crowns the year with his good gifts.", ref: "Ps 65:11", tradition: "christian-catholic" },
  "9-11": { quote: "He will command his angels to take care of you.", ref: "Ps 91:11", tradition: "christian-catholic" },
  "9-12": { quote: "Lord, you have made so many things! How wise you were when you made all of them!", ref: "Ps 104:24", tradition: "christian-catholic" },
  "9-13": { quote: "The Lord gives wisdom. Knowledge and understanding come from his mouth.", ref: "Prov 2:6", tradition: "christian-catholic" },
  "9-14": { quote: "The cross reminds us of how much Jesus loves us.", ref: "Exaltation of the Holy Cross", tradition: "christian-catholic" },
  "9-15": { quote: "Be very glad and joyful!", ref: "Matt 5:12", tradition: "christian-catholic" },
  "9-16": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "9-17": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "9-18": { quote: "God fills the sky with clouds.", ref: "Job 37:11", tradition: "christian-catholic" },
  "9-19": { quote: "Be still and know that I am God.", ref: "Ps 46:10", tradition: "christian-catholic" },
  "9-20": { quote: "The earth produced plants and trees, just as God had planned.", ref: "Gen 1:12", tradition: "christian-catholic" },
  "9-21": { quote: "God made the moon to mark the seasons.", ref: "Ps 104:19", tradition: "christian-catholic" },
  "9-22": { quote: "Shout for joy to the Lord!", ref: "Ps 100:1", tradition: "christian-catholic" },
  "9-23": { quote: "Pray, hope, and don't worry.", ref: "St. Padre Pio", tradition: "christian-catholic" },
  "9-24": { quote: "How you made me is amazing and wonderful!", ref: "Ps 139:14", tradition: "christian-catholic" },
  "9-25": { quote: "A cheerful heart makes you feel good.", ref: "Prov 17:22", tradition: "christian-catholic" },
  "9-26": { quote: "Give to others and it will be given to you.", ref: "Luke 6:38", tradition: "christian-catholic" },
  "9-27": { quote: "Be strong and brave.", ref: "Josh 1:9", tradition: "christian-catholic" },
  "9-28": { quote: "God made the moon to mark the seasons.", ref: "Ps 104:19", tradition: "christian-catholic" },
  "9-29": { quote: "Angels are God's helpers. He sends them to watch over us.", ref: "Feast of the Archangels", tradition: "christian-catholic" },
  "9-30": { quote: "Give thanks no matter what happens.", ref: "1 Thess 5:18", tradition: "christian-catholic" },

  // ── OCTOBER ──
  "10-1": { quote: "I will do small things with great love.", ref: "St. Thérèse of Lisieux", tradition: "christian-catholic" },
  "10-2": { quote: "Our guardian angel watches over us day and night.", ref: "Feast of Guardian Angels", tradition: "christian-catholic" },
  "10-3": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "10-4": { quote: "Lord, make me an instrument of your peace.", ref: "St. Francis of Assisi", tradition: "christian-catholic" },
  "10-5": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "10-6": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "10-7": { quote: "The rosary is like a beautiful garden of prayers to Mary.", ref: "Our Lady of the Rosary", tradition: "christian-catholic" },
  "10-8": { quote: "The earth produced plants and trees, just as God had planned.", ref: "Gen 1:12", tradition: "christian-catholic" },
  "10-9": { quote: "Shout for joy to the Lord!", ref: "Ps 100:1", tradition: "christian-catholic" },
  "10-10": { quote: "From the rising of the sun unto the going down of the same.", ref: "Ps 113:3", tradition: "christian-catholic" },
  "10-11": { quote: "God your Lord is with you everywhere you go.", ref: "Josh 1:9", tradition: "christian-catholic" },
  "10-12": { quote: "Work at everything you do with all your heart.", ref: "Eccl 9:10", tradition: "christian-catholic" },
  "10-13": { quote: "Ask and it will be given to you. Search and you will find.", ref: "Matt 7:7", tradition: "christian-catholic" },
  "10-14": { quote: "If your faith is as small as a mustard seed, nothing will be impossible for you.", ref: "Matt 17:20", tradition: "christian-catholic" },
  "10-15": { quote: "Let nothing disturb you. God alone is enough.", ref: "St. Teresa of Ávila", tradition: "christian-catholic" },
  "10-16": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "10-17": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "10-18": { quote: "Be joyful in the Lord always!", ref: "Phil 4:4", tradition: "christian-catholic" },
  "10-19": { quote: "God makes everything beautiful at just the right time.", ref: "Eccl 3:11", tradition: "christian-catholic" },
  "10-20": { quote: "He clotheth himself with light as with a garment.", ref: "Ps 104:2", tradition: "christian-catholic" },
  "10-21": { quote: "Be not afraid.", ref: "St. John Paul II", tradition: "christian-catholic" },
  "10-22": { quote: "Be strong and brave. Do not be terrified.", ref: "Josh 1:9", tradition: "christian-catholic" },
  "10-23": { quote: "Your word is like a lamp that shows me the way.", ref: "Ps 119:105", tradition: "christian-catholic" },
  "10-24": { quote: "Work at everything you do with all your heart.", ref: "Col 3:23", tradition: "christian-catholic" },
  "10-25": { quote: "A cheerful heart makes you feel good.", ref: "Prov 17:22", tradition: "christian-catholic" },
  "10-26": { quote: "Get wisdom. No matter what it costs, get understanding.", ref: "Prov 4:7", tradition: "christian-catholic" },
  "10-27": { quote: "Lord, you have made so many things!", ref: "Ps 104:24", tradition: "christian-catholic" },
  "10-28": { quote: "Do not be afraid. I am with you.", ref: "Isa 41:10", tradition: "christian-catholic" },
  "10-29": { quote: "There is a time for everything.", ref: "Eccl 3:1", tradition: "christian-catholic" },
  "10-30": { quote: "God counts all the stars and knows each one by name.", ref: "Ps 147:4", tradition: "christian-catholic" },
  "10-31": { quote: "Love your neighbor as you love yourself.", ref: "Mark 12:31", tradition: "christian-catholic" },

  // ── NOVEMBER ──
  "11-1": { quote: "The saints are our friends in heaven. They cheer for us every day!", ref: "All Saints' Day", tradition: "christian-catholic" },
  "11-2": { quote: "We pray for our loved ones who have gone to be with God.", ref: "All Souls' Day", tradition: "christian-catholic" },
  "11-3": { quote: "It is no great thing to be humble when you are brought low; but to be humble when you are praised is a great thing.", ref: "St. Martin de Porres", tradition: "christian-catholic" },
  "11-4": { quote: "Give thanks to the Lord because he is good.", ref: "Ps 107:1", tradition: "christian-catholic" },
  "11-5": { quote: "Look at the ant! Think about how it lives and become wise.", ref: "Prov 6:6", tradition: "christian-catholic" },
  "11-6": { quote: "Taste and see that the Lord is good.", ref: "Ps 34:8", tradition: "christian-catholic" },
  "11-7": { quote: "God's words taste sweeter than honey.", ref: "Ps 119:103", tradition: "christian-catholic" },
  "11-8": { quote: "You are the light of the world — a city on a hill cannot be hidden.", ref: "Matt 5:14", tradition: "christian-catholic" },
  "11-9": { quote: "The church is God's house where we go to pray and be together.", ref: "Dedication of the Lateran Basilica", tradition: "christian-catholic" },
  "11-10": { quote: "Your word is like a lamp that shows me the way.", ref: "Ps 119:105", tradition: "christian-catholic" },
  "11-11": { quote: "No one has greater love than the one who gives their life for their friends.", ref: "John 15:13", tradition: "christian-catholic" },
  "11-12": { quote: "There is a time for everything.", ref: "Eccl 3:1", tradition: "christian-catholic" },
  "11-13": { quote: "Start by doing what's necessary, then what's possible, and suddenly you are doing the impossible.", ref: "St. Francis of Assisi", tradition: "christian-catholic" },
  "11-14": { quote: "A wise person sees danger ahead and avoids it.", ref: "Prov 22:3", tradition: "christian-catholic" },
  "11-15": { quote: "How good and pleasant it is when God's people live together in peace!", ref: "Ps 133:1", tradition: "christian-catholic" },
  "11-16": { quote: "The earth is full of your riches, Lord.", ref: "Ps 104:24", tradition: "christian-catholic" },
  "11-17": { quote: "I am the bread of life.", ref: "John 6:35", tradition: "christian-catholic" },
  "11-18": { quote: "Love each other just as I have loved you.", ref: "John 15:12", tradition: "christian-catholic" },
  "11-19": { quote: "Love your neighbor as you love yourself.", ref: "Mark 12:31", tradition: "christian-catholic" },
  "11-20": { quote: "You prepare a feast for me.", ref: "Ps 23:5", tradition: "christian-catholic" },
  "11-21": { quote: "The works of mercy help us care for others just as Jesus did.", ref: "Works of Mercy", tradition: "christian-catholic" },
  "11-22": { quote: "Sing to God with joy! Music is a gift from heaven.", ref: "St. Cecilia", tradition: "christian-catholic" },
  "11-23": { quote: "You are blessed because you believed the Lord would keep his promises to you.", ref: "Luke 1:45", tradition: "christian-catholic" },
  "11-24": { quote: "Remember the days of long ago. Think about what happened in each generation.", ref: "Deut 32:7", tradition: "christian-catholic" },
  "11-25": { quote: "Give thanks to the Lord because he is good.", ref: "Ps 107:1", tradition: "christian-catholic" },
  "11-26": { quote: "Every good and perfect gift comes down from God.", ref: "James 1:17", tradition: "christian-catholic" },
  "11-27": { quote: "Give to others and it will be given to you.", ref: "Luke 6:38", tradition: "christian-catholic" },
  "11-28": { quote: "He lets me lie down in fields of green grass. He gives me new strength.", ref: "Ps 23:2", tradition: "christian-catholic" },
  "11-29": { quote: "When hope is put off, it makes your heart sick. But when dreams come true, it is like eating fruit from the tree of life.", ref: "Prov 13:12", tradition: "christian-catholic" },
  "11-30": { quote: "Give thanks no matter what happens.", ref: "1 Thess 5:18", tradition: "christian-catholic" },

  // ── DECEMBER ──
  "12-1": { quote: "The people who walked in darkness have seen a great light.", ref: "Isa 9:2", tradition: "christian-catholic" },
  "12-2": { quote: "How you made me is amazing and wonderful!", ref: "Ps 139:14", tradition: "christian-catholic" },
  "12-3": { quote: "It is more blessed to give than to receive.", ref: "Acts 20:35", tradition: "christian-catholic" },
  "12-4": { quote: "Your word is like a lamp that shows me the way.", ref: "Ps 119:105", tradition: "christian-catholic" },
  "12-5": { quote: "Let nothing disturb you. God alone is enough.", ref: "St. Teresa of Ávila", tradition: "christian-catholic" },
  "12-6": { quote: "St. Nicholas gave gifts in secret to help those in need.", ref: "St. Nicholas", tradition: "christian-catholic" },
  "12-7": { quote: "Let everything that has breath praise the Lord!", ref: "Ps 150:6", tradition: "christian-catholic" },
  "12-8": { quote: "Mary was full of grace from the very beginning. God made her special.", ref: "Immaculate Conception", tradition: "christian-catholic" },
  "12-9": { quote: "A star will come from Jacob's family.", ref: "Num 24:17", tradition: "christian-catholic" },
  "12-10": { quote: "How good and pleasant it is when God's people live together in peace!", ref: "Ps 133:1", tradition: "christian-catholic" },
  "12-11": { quote: "Love your neighbor as you love yourself.", ref: "Mark 12:31", tradition: "christian-catholic" },
  "12-12": { quote: "Our Lady of Guadalupe showed her love for all God's children.", ref: "Our Lady of Guadalupe", tradition: "christian-catholic" },
  "12-13": { quote: "St. Lucy brought light and hope to those in the dark.", ref: "St. Lucy", tradition: "christian-catholic" },
  "12-14": { quote: "In the dark night of the soul, God's light still shines.", ref: "St. John of the Cross", tradition: "christian-catholic" },
  "12-15": { quote: "A child is born to us. A son is given to us.", ref: "Isa 9:6", tradition: "christian-catholic" },
  "12-16": { quote: "Glory to God in the highest! And peace on earth to those he is pleased with.", ref: "Luke 2:14", tradition: "christian-catholic" },
  "12-17": { quote: "The shepherds said to one another — let's go to Bethlehem!", ref: "Luke 2:15", tradition: "christian-catholic" },
  "12-18": { quote: "A cheerful heart makes you feel good.", ref: "Prov 17:22", tradition: "christian-catholic" },
  "12-19": { quote: "We saw his star when it rose. We have come to worship him.", ref: "Matt 2:2", tradition: "christian-catholic" },
  "12-20": { quote: "Give to others and it will be given to you.", ref: "Luke 6:38", tradition: "christian-catholic" },
  "12-21": { quote: "They bowed down and worshiped him. Then they opened their treasures and gave him gifts.", ref: "Matt 2:11", tradition: "christian-catholic" },
  "12-22": { quote: "The joy of the Lord makes you strong.", ref: "Neh 8:10", tradition: "christian-catholic" },
  "12-23": { quote: "A child is born to us. A son is given to us!", ref: "Isa 9:6", tradition: "christian-catholic" },
  "12-24": { quote: "Today a Savior has been born to you. He is the Messiah, the Lord.", ref: "Luke 2:11", tradition: "christian-catholic" },
  "12-25": { quote: "God loved the world so much that he gave his one and only Son.", ref: "John 3:16", tradition: "christian-catholic" },
  "12-26": { quote: "It is more blessed to give than to receive.", ref: "Acts 20:35", tradition: "christian-catholic" },
  "12-27": { quote: "I leave my peace with you. I give my peace to you.", ref: "John 14:27", tradition: "christian-catholic" },
  "12-28": { quote: "Get up and shine! Your light has come!", ref: "Isa 60:1", tradition: "christian-catholic" },
  "12-29": { quote: "I will remember what the Lord has done.", ref: "Ps 77:11", tradition: "christian-catholic" },
  "12-30": { quote: "Give thanks no matter what happens.", ref: "1 Thess 5:18", tradition: "christian-catholic" },
  "12-31": { quote: "I am making everything new!", ref: "Rev 21:5", tradition: "christian-catholic" },
};
